// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#ifndef _UI_COMP_ROLLERSMALL_H
#define _UI_COMP_ROLLERSMALL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT RollerSmall
#define UI_COMP_CONTAINER____ROLLERSMALL_CONTAINER____ROLLERSMALL 0
#define UI_COMP_CONTAINER____ROLLERSMALL_LABEL____TITLE 1
#define UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER 2
#define _UI_COMP_CONTAINER____ROLLERSMALL_NUM 3
lv_obj_t * ui_Container____RollerSmall_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
