// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#ifndef _UI_COMP__H
#define _UI_COMP__H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

void get_component_child_event_cb(lv_event_t * e);
void del_component_child_event_cb(lv_event_t * e);

lv_obj_t * ui_comp_get_child(lv_obj_t * comp, uint32_t child_idx);
extern uint32_t LV_EVENT_GET_COMP_CHILD;
#include "ui_comp_backmenu.h"
#include "ui_comp_checkboxoption.h"
#include "ui_comp_contorlbutton.h"
#include "ui_comp_dropdown.h"
#include "ui_comp_header.h"
#include "ui_comp_input.h"
#include "ui_comp_keyboardl.h"
#include "ui_comp_menu.h"
#include "ui_comp_menubutton.h"
#include "ui_comp_numpad_m.h"
#include "ui_comp_popup.h"
#include "ui_comp_primarybtn.h"
#include "ui_comp_rollercard.h"
#include "ui_comp_rollersmall.h"
#include "ui_comp_secondarybtn.h"
#include "ui_comp_switch.h"
#include "ui_comp_tabbutton.h"
#include "ui_comp_tabcontentinitial.h"

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
