// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#ifndef _UI_COMP_MENUBUTTON_H
#define _UI_COMP_MENUBUTTON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT MenuButton
#define UI_COMP_BUTTON____MENUBUTTON_BUTTON____MENUBUTTON 0
#define UI_COMP_BUTTON____MENUBUTTON_IMAGE____ICON 1
#define UI_COMP_BUTTON____MENUBUTTON_LABEL____LABEL 2
#define _UI_COMP_BUTTON____MENUBUTTON_NUM 3
lv_obj_t * ui_Button____MenuButton_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
