// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#ifndef _UI_COMP_SWITCH_H
#define _UI_COMP_SWITCH_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Switch
#define UI_COMP_CONTAINER____SWITCH_CONTAINER____SWITCH 0
#define UI_COMP_CONTAINER____SWITCH_LABEL____LABEL23 1
#define UI_COMP_CONTAINER____SWITCH_SWITCH____SWITCH3 2
#define _UI_COMP_CONTAINER____SWITCH_NUM 3
lv_obj_t * ui_Container____Switch_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
