// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "../ui.h"


// COMPONENT Header

lv_obj_t * ui_Container____Header_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Container____Header;
    cui_Container____Header = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_Container____Header);
    lv_obj_set_height(cui_Container____Header, 40);
    lv_obj_set_width(cui_Container____Header, lv_pct(100));
    lv_obj_set_align(cui_Container____Header, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(cui_Container____Header, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Container____Header, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_Container____Header, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(cui_Container____Header, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Container____Header, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Container____Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Container____Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Button____Back_Button;
    cui_Button____Back_Button = lv_button_create(cui_Container____Header);
    lv_obj_set_height(cui_Button____Back_Button, lv_pct(100));
    lv_obj_set_width(cui_Button____Back_Button, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(cui_Button____Back_Button, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Button____Back_Button, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Button____Back_Button, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(cui_Button____Back_Button, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_Button____Back_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Button____Back_Button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Button____Back_Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_Button____Back_Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Button____Back_Button, 48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Button____Back_Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Button____Back_Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_Button____Back_Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_Button____Back_Button, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Image____icon;
    cui_Image____icon = lv_image_create(cui_Button____Back_Button);
    lv_image_set_src(cui_Image____icon, ui_img_back_png);
    lv_obj_set_width(cui_Image____icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image____icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Image____icon, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Image____icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label____Back;
    cui_Label____Back = lv_label_create(cui_Button____Back_Button);
    lv_obj_set_width(cui_Label____Back, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label____Back, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label____Back, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_Label____Back, "BACK");
    ui_object_set_themeable_style_property(cui_Label____Back, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(cui_Label____Back, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_letter_space(cui_Label____Back, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(cui_Label____Back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label____Back, &ui_font_P3_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label____Title;
    cui_Label____Title = lv_label_create(cui_Container____Header);
    lv_obj_set_width(cui_Label____Title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label____Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label____Title, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_Label____Title, "Title");
    ui_object_set_themeable_style_property(cui_Label____Title, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(cui_Label____Title, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_letter_space(cui_Label____Title, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(cui_Label____Title, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label____Title, &ui_font_P1_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Container____Container84;
    cui_Container____Container84 = lv_obj_create(cui_Container____Header);
    lv_obj_remove_style_all(cui_Container____Container84);
    lv_obj_set_height(cui_Container____Container84, lv_pct(100));
    lv_obj_set_flex_grow(cui_Container____Container84, 1);
    lv_obj_set_align(cui_Container____Container84, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Container____Container84, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Container____Icons;
    cui_Container____Icons = lv_obj_create(cui_Container____Header);
    lv_obj_remove_style_all(cui_Container____Icons);
    lv_obj_set_height(cui_Container____Icons, lv_pct(100));
    lv_obj_set_width(cui_Container____Icons, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(cui_Container____Icons, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(cui_Container____Icons, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Container____Icons, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Container____Icons, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(cui_Container____Icons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_Container____Icons, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Image____USB;
    cui_Image____USB = lv_image_create(cui_Container____Icons);
    lv_image_set_src(cui_Image____USB, ui_img_home_menus_usb_png);
    lv_obj_set_width(cui_Image____USB, LV_SIZE_CONTENT);   /// 31
    lv_obj_set_height(cui_Image____USB, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_align(cui_Image____USB, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image____USB, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_Image____USB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Image____Ethernet;
    cui_Image____Ethernet = lv_image_create(cui_Container____Icons);
    lv_image_set_src(cui_Image____Ethernet, ui_img_home_menus_desktop_png);
    lv_obj_set_width(cui_Image____Ethernet, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image____Ethernet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Image____Ethernet, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image____Ethernet, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_Image____Ethernet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Image____Wifi;
    cui_Image____Wifi = lv_image_create(cui_Container____Icons);
    lv_image_set_src(cui_Image____Wifi, ui_img_home_menus_wifi_png);
    lv_obj_set_width(cui_Image____Wifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image____Wifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Image____Wifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image____Wifi, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_Image____Wifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINER____HEADER_NUM);
    children[UI_COMP_CONTAINER____HEADER_CONTAINER____HEADER] = cui_Container____Header;
    children[UI_COMP_CONTAINER____HEADER_BUTTON____BACK_BUTTON] = cui_Button____Back_Button;
    children[UI_COMP_CONTAINER____HEADER_BUTTON____BACK_BUTTON_IMAGE____ICON] = cui_Image____icon;
    children[UI_COMP_CONTAINER____HEADER_BUTTON____BACK_BUTTON_LABEL____BACK] = cui_Label____Back;
    children[UI_COMP_CONTAINER____HEADER_LABEL____TITLE] = cui_Label____Title;
    children[UI_COMP_CONTAINER____HEADER_CONTAINER____CONTAINER84] = cui_Container____Container84;
    children[UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS] = cui_Container____Icons;
    children[UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____USB] = cui_Image____USB;
    children[UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____ETHERNET] = cui_Image____Ethernet;
    children[UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____WIFI] = cui_Image____Wifi;
    lv_obj_add_event_cb(cui_Container____Header, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Container____Header, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Container____Header_create_hook(cui_Container____Header);
    return cui_Container____Header;
}

