// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#ifndef _UI_COMP_NUMPAD_M_H
#define _UI_COMP_NUMPAD_M_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Numpad M
#define UI_COMP_KEYBOARD____NUMPAD_M_KEYBOARD____NUMPAD_M 0
#define _UI_COMP_KEYBOARD____NUMPAD_M_NUM 1
lv_obj_t * ui_Keyboard____Numpad_M_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
