// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#ifndef _UI_COMP_POPUP_H
#define _UI_COMP_POPUP_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Popup
#define UI_COMP_PANEL____POPUP_PANEL____POPUP 0
#define UI_COMP_PANEL____POPUP_PANEL____CARD 1
#define UI_COMP_PANEL____POPUP_PANEL____CARD_LABEL____TITLE 2
#define UI_COMP_PANEL____POPUP_PANEL____CARD_CONTAINER____CONTAINER11 3
#define UI_COMP_PANEL____POPUP_PANEL____CARD_CONTAINER____CONTAINER11_LABEL____TEXT 4
#define UI_COMP_PANEL____POPUP_PANEL____CARD_CONTAINER____CONTAINER18 5
#define UI_COMP_PANEL____POPUP_SECONDARYBTN____CANCEL 6
#define UI_COMP_PANEL____POPUP_SECONDARYBTN____CANCEL_LABEL____CANCEL_LABEL 7
#define UI_COMP_PANEL____POPUP_PRIMARYBTN____NEXT 8
#define UI_COMP_PANEL____POPUP_PRIMARYBTN____NEXT_LABEL____NEXT_LABEL 9
#define _UI_COMP_PANEL____POPUP_NUM 10
lv_obj_t * ui_Panel____Popup_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
