// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#ifndef _UI_COMP_HEADER_H
#define _UI_COMP_HEADER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Header
#define UI_COMP_CONTAINER____HEADER_CONTAINER____HEADER 0
#define UI_COMP_CONTAINER____HEADER_BUTTON____BACK_BUTTON 1
#define UI_COMP_CONTAINER____HEADER_BUTTON____BACK_BUTTON_IMAGE____ICON 2
#define UI_COMP_CONTAINER____HEADER_BUTTON____BACK_BUTTON_LABEL____BACK 3
#define UI_COMP_CONTAINER____HEADER_LABEL____TITLE 4
#define UI_COMP_CONTAINER____HEADER_CONTAINER____CONTAINER84 5
#define UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS 6
#define UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____USB 7
#define UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____ETHERNET 8
#define UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____WIFI 9
#define _UI_COMP_CONTAINER____HEADER_NUM 10
lv_obj_t * ui_Container____Header_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
