// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "../ui.h"


// COMPONENT Checkboxoption

lv_obj_t * ui_Container____Checkboxoption_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Container____Checkboxoption;
    cui_Container____Checkboxoption = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_Container____Checkboxoption);
    lv_obj_set_height(cui_Container____Checkboxoption, 48);
    lv_obj_set_width(cui_Container____Checkboxoption, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(cui_Container____Checkboxoption, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Container____Checkboxoption, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Container____Checkboxoption, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_Container____Checkboxoption, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(cui_Container____Checkboxoption, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_Container____Checkboxoption, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Container____Checkbox_frame;
    cui_Container____Checkbox_frame = lv_obj_create(cui_Container____Checkboxoption);
    lv_obj_remove_style_all(cui_Container____Checkbox_frame);
    lv_obj_set_width(cui_Container____Checkbox_frame, 48);
    lv_obj_set_height(cui_Container____Checkbox_frame, 48);
    lv_obj_set_align(cui_Container____Checkbox_frame, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Container____Checkbox_frame, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Checkbox____Checkbox1;
    cui_Checkbox____Checkbox1 = lv_checkbox_create(cui_Container____Checkbox_frame);
    lv_obj_set_width(cui_Checkbox____Checkbox1, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(cui_Checkbox____Checkbox1, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(cui_Checkbox____Checkbox1, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Checkbox____Checkbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_radius(cui_Checkbox____Checkbox1, 6, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Checkbox____Checkbox1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Checkbox____Checkbox1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Checkbox____Checkbox1, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(cui_Checkbox____Checkbox1, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Blue);
    lv_obj_set_style_border_width(cui_Checkbox____Checkbox1, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_Checkbox____Checkbox1, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Checkbox____Checkbox1, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Checkbox____Checkbox1, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Checkbox____Checkbox1, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Checkbox____Checkbox1, LV_PART_INDICATOR | LV_STATE_CHECKED,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(cui_Checkbox____Checkbox1, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Blue);
    lv_obj_set_style_bg_image_src(cui_Checkbox____Checkbox1, ui_img_checkbox_checked_vector_png,
                                  LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_pad_left(cui_Checkbox____Checkbox1, 12, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_pad_right(cui_Checkbox____Checkbox1, 12, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_pad_top(cui_Checkbox____Checkbox1, 12, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_pad_bottom(cui_Checkbox____Checkbox1, 12, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_t * cui_Label____Label1;
    cui_Label____Label1 = lv_label_create(cui_Container____Checkboxoption);
    lv_obj_set_width(cui_Label____Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label____Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label____Label1, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label____Label1, "Pressure Transducer");
    ui_object_set_themeable_style_property(cui_Label____Label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(cui_Label____Label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(cui_Label____Label1, &ui_font_P2_SBold, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINER____CHECKBOXOPTION_NUM);
    children[UI_COMP_CONTAINER____CHECKBOXOPTION_CONTAINER____CHECKBOXOPTION] = cui_Container____Checkboxoption;
    children[UI_COMP_CONTAINER____CHECKBOXOPTION_CONTAINER____CHECKBOX_FRAME] = cui_Container____Checkbox_frame;
    children[UI_COMP_CONTAINER____CHECKBOXOPTION_CONTAINER____CHECKBOX_FRAME_CHECKBOX____CHECKBOX1] =
        cui_Checkbox____Checkbox1;
    children[UI_COMP_CONTAINER____CHECKBOXOPTION_LABEL____LABEL1] = cui_Label____Label1;
    lv_obj_add_event_cb(cui_Container____Checkboxoption, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Container____Checkboxoption, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Container____Checkboxoption_create_hook(cui_Container____Checkboxoption);
    return cui_Container____Checkboxoption;
}

