// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "../ui.h"


// COMPONENT Secondarybtn

lv_obj_t * ui_Button____Secondarybtn_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Button____Secondarybtn;
    cui_Button____Secondarybtn = lv_button_create(comp_parent);
    lv_obj_set_width(cui_Button____Secondarybtn, 199);
    lv_obj_set_height(cui_Button____Secondarybtn, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_align(cui_Button____Secondarybtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Button____Secondarybtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_Button____Secondarybtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Button____Secondarybtn, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Button____Secondarybtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Button____Secondarybtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Button____Secondarybtn, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(cui_Button____Secondarybtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_border_width(cui_Button____Secondarybtn, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_Button____Secondarybtn, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Button____Secondarybtn, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Button____Secondarybtn, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Button____Secondarybtn, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_Button____Secondarybtn, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_Button____Secondarybtn, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Button____Secondarybtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(cui_Button____Secondarybtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(cui_Button____Secondarybtn, &ui_font_P2_SBold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_height(cui_Button____Secondarybtn, 74, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_height(cui_Button____Secondarybtn, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Button____Secondarybtn, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(cui_Button____Secondarybtn, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Blue);
    lv_obj_set_style_border_width(cui_Button____Secondarybtn, 3, LV_PART_MAIN | LV_STATE_PRESSED);
    ui_object_set_themeable_style_property(cui_Button____Secondarybtn, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(cui_Button____Secondarybtn, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Blue);
    ui_object_set_themeable_style_property(cui_Button____Secondarybtn, LV_PART_MAIN | LV_STATE_DISABLED,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Disabled);
    ui_object_set_themeable_style_property(cui_Button____Secondarybtn, LV_PART_MAIN | LV_STATE_DISABLED,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Disabled);
    ui_object_set_themeable_style_property(cui_Button____Secondarybtn, LV_PART_MAIN | LV_STATE_DISABLED,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Disabled_font);
    ui_object_set_themeable_style_property(cui_Button____Secondarybtn, LV_PART_MAIN | LV_STATE_DISABLED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Disabled_font);

    lv_obj_t * cui_Label____Label;
    cui_Label____Label = lv_label_create(cui_Button____Secondarybtn);
    lv_obj_set_width(cui_Label____Label, lv_pct(100));
    lv_obj_set_height(cui_Label____Label, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(cui_Label____Label, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label____Label, "Next");
    lv_obj_set_style_text_align(cui_Label____Label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON____SECONDARYBTN_NUM);
    children[UI_COMP_BUTTON____SECONDARYBTN_BUTTON____SECONDARYBTN] = cui_Button____Secondarybtn;
    children[UI_COMP_BUTTON____SECONDARYBTN_LABEL____LABEL] = cui_Label____Label;
    lv_obj_add_event_cb(cui_Button____Secondarybtn, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Button____Secondarybtn, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Button____Secondarybtn_create_hook(cui_Button____Secondarybtn);
    return cui_Button____Secondarybtn;
}

