// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#ifndef _UI_COMP_SECONDARYBTN_H
#define _UI_COMP_SECONDARYBTN_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Secondarybtn
#define UI_COMP_BUTTON____SECONDARYBTN_BUTTON____SECONDARYBTN 0
#define UI_COMP_BUTTON____SECONDARYBTN_LABEL____LABEL 1
#define _UI_COMP_BUTTON____SECONDARYBTN_NUM 2
lv_obj_t * ui_Button____Secondarybtn_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
