// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#ifndef _UI_COMP_PRIMARYBTN_H
#define _UI_COMP_PRIMARYBTN_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Primarybtn
#define UI_COMP_BUTTON____PRIMARYBTN_BUTTON____PRIMARYBTN 0
#define UI_COMP_BUTTON____PRIMARYBTN_LABEL____LABEL 1
#define _UI_COMP_BUTTON____PRIMARYBTN_NUM 2
lv_obj_t * ui_Button____Primarybtn_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
