// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#ifndef _UI_COMP_INPUT_H
#define _UI_COMP_INPUT_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Input
#define UI_COMP_CONTAINER____INPUT_CONTAINER____INPUT 0
#define UI_COMP_CONTAINER____INPUT_CONTAINER____LABEL_PADDING 1
#define UI_COMP_CONTAINER____INPUT_CONTAINER____LABEL_PADDING_LABEL____LABEL 2
#define UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1 3
#define _UI_COMP_CONTAINER____INPUT_NUM 4
lv_obj_t * ui_Container____Input_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
