// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "../ui.h"

void ui_comp_Container____BackMenu_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Container____Checkboxoption_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Button____ContorlButton_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Container____Dropdown_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Container____Header_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Container____Input_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Keyboard____KeyboardL_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Container____Menu_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Button____MenuButton_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Keyboard____Numpad_M_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Panel____Popup_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Button____Primarybtn_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Panel____RollerCard_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Container____RollerSmall_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Button____Secondarybtn_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Container____Switch_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Button____TabButton_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Container____TabContentInitial_create_hook(lv_obj_t * comp)
{
}
