// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#ifndef _UI_COMP_CONTORLBUTTON_H
#define _UI_COMP_CONTORLBUTTON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ContorlButton
#define UI_COMP_BUTTON____CONTORLBUTTON_BUTTON____CONTORLBUTTON 0
#define _UI_COMP_BUTTON____CONTORLBUTTON_NUM 1
lv_obj_t * ui_Button____ContorlButton_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
