// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "../ui.h"


// COMPONENT BackMenu

lv_obj_t * ui_Container____BackMenu_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Container____BackMenu;
    cui_Container____BackMenu = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_Container____BackMenu);
    lv_obj_set_width(cui_Container____BackMenu, lv_pct(100));
    lv_obj_set_flex_grow(cui_Container____BackMenu, 1);
    lv_obj_set_align(cui_Container____BackMenu, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Container____BackMenu, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Container____BackMenu, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Container____BackMenu, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_White);
    ui_object_set_themeable_style_property(cui_Container____BackMenu, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_White);
    lv_obj_set_style_clip_corner(cui_Container____BackMenu, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Container____BackMenu, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_OUTLINE_COLOR, _ui_theme_color_Border);
    ui_object_set_themeable_style_property(cui_Container____BackMenu, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_OUTLINE_OPA,
                                           _ui_theme_alpha_Border);
    lv_obj_set_style_outline_width(cui_Container____BackMenu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(cui_Container____BackMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_Container____BackMenu, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_Container____BackMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Button____Button;
    cui_Button____Button = lv_button_create(cui_Container____BackMenu);
    lv_obj_set_width(cui_Button____Button, 100);
    lv_obj_set_height(cui_Button____Button, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(cui_Button____Button, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Button____Button, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_Button____Button, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(cui_Button____Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_Button____Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Button____Button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Button____Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_Button____Button, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_Button____Button, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Image____Icon;
    cui_Image____Icon = lv_image_create(cui_Button____Button);
    lv_image_set_src(cui_Image____Icon, ui_img_back_png);
    lv_obj_set_width(cui_Image____Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image____Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Image____Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image____Icon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_Image____Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label____Label;
    cui_Label____Label = lv_label_create(cui_Button____Button);
    lv_obj_set_width(cui_Label____Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label____Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label____Label, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label____Label, "BACK");
    ui_object_set_themeable_style_property(cui_Label____Label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(cui_Label____Label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(cui_Label____Label, &ui_font_P3_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINER____BACKMENU_NUM);
    children[UI_COMP_CONTAINER____BACKMENU_CONTAINER____BACKMENU] = cui_Container____BackMenu;
    children[UI_COMP_CONTAINER____BACKMENU_BUTTON____BUTTON] = cui_Button____Button;
    children[UI_COMP_CONTAINER____BACKMENU_BUTTON____BUTTON_IMAGE____ICON] = cui_Image____Icon;
    children[UI_COMP_CONTAINER____BACKMENU_BUTTON____BUTTON_LABEL____LABEL] = cui_Label____Label;
    lv_obj_add_event_cb(cui_Container____BackMenu, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Container____BackMenu, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Container____BackMenu_create_hook(cui_Container____BackMenu);
    return cui_Container____BackMenu;
}

