// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "../ui.h"


// COMPONENT ContorlButton

lv_obj_t * ui_Button____ContorlButton_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Button____ContorlButton;
    cui_Button____ContorlButton = lv_button_create(comp_parent);
    lv_obj_set_width(cui_Button____ContorlButton, 200);
    lv_obj_set_height(cui_Button____ContorlButton, 80);
    lv_obj_set_align(cui_Button____ContorlButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Button____ContorlButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_Button____ContorlButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Button____ContorlButton, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Button____ContorlButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(cui_Button____ContorlButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_bg_image_src(cui_Button____ContorlButton, ui_img_home_chevron_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Button____ContorlButton, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(cui_Button____ContorlButton, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Blue);
    lv_obj_set_style_bg_image_src(cui_Button____ContorlButton, ui_img_home_chevron_down_png,
                                  LV_PART_MAIN | LV_STATE_USER_1);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON____CONTORLBUTTON_NUM);
    children[UI_COMP_BUTTON____CONTORLBUTTON_BUTTON____CONTORLBUTTON] = cui_Button____ContorlButton;
    lv_obj_add_event_cb(cui_Button____ContorlButton, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Button____ContorlButton, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Button____ContorlButton_create_hook(cui_Button____ContorlButton);
    return cui_Button____ContorlButton;
}

