// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "../ui.h"


// COMPONENT RollerCard

lv_obj_t * ui_Panel____RollerCard_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Panel____RollerCard;
    cui_Panel____RollerCard = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_Panel____RollerCard, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(cui_Panel____RollerCard, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(cui_Panel____RollerCard, -104);
    lv_obj_set_y(cui_Panel____RollerCard, 99);
    lv_obj_set_align(cui_Panel____RollerCard, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Panel____RollerCard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Panel____RollerCard, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Container____Rollers;
    cui_Container____Rollers = lv_obj_create(cui_Panel____RollerCard);
    lv_obj_remove_style_all(cui_Container____Rollers);
    lv_obj_set_width(cui_Container____Rollers, 531);
    lv_obj_set_height(cui_Container____Rollers, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(cui_Container____Rollers, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Container____Rollers, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Container____Rollers, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_Container____Rollers, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(cui_Container____Rollers, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Container____Rollers, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Container____Rollers, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Container____Rollers, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_Container____Rollers, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_Container____Rollers, 42, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_RollerSmall____RollerSmall;
    cui_RollerSmall____RollerSmall = ui_Container____RollerSmall_create(cui_Container____Rollers);
    lv_obj_set_x(cui_RollerSmall____RollerSmall, -281);
    lv_obj_set_y(cui_RollerSmall____RollerSmall, 91);

    lv_obj_t * cui_RollerSmall____RollerSmall1;
    cui_RollerSmall____RollerSmall1 = ui_Container____RollerSmall_create(cui_Container____Rollers);
    lv_obj_set_x(cui_RollerSmall____RollerSmall1, -281);
    lv_obj_set_y(cui_RollerSmall____RollerSmall1, 91);

    lv_label_set_text(ui_comp_get_child(cui_RollerSmall____RollerSmall1, UI_COMP_CONTAINER____ROLLERSMALL_LABEL____TITLE),
                      "Stroke \nLength");

    lv_roller_set_options(ui_comp_get_child(cui_RollerSmall____RollerSmall1,
                                            UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER), "0.125\n0.25\n0.5", LV_ROLLER_MODE_NORMAL);

    lv_obj_t * cui_RollerSmall____RollerSmall2;
    cui_RollerSmall____RollerSmall2 = ui_Container____RollerSmall_create(cui_Container____Rollers);
    lv_obj_set_x(cui_RollerSmall____RollerSmall2, -281);
    lv_obj_set_y(cui_RollerSmall____RollerSmall2, 91);

    lv_label_set_text(ui_comp_get_child(cui_RollerSmall____RollerSmall2, UI_COMP_CONTAINER____ROLLERSMALL_LABEL____TITLE),
                      "Wetted \nParts");

    lv_roller_set_options(ui_comp_get_child(cui_RollerSmall____RollerSmall2,
                                            UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER), "Stainless (M)\nPEEK (I)\nHastelloy-C (MH)", LV_ROLLER_MODE_NORMAL);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_PANEL____ROLLERCARD_NUM);
    children[UI_COMP_PANEL____ROLLERCARD_PANEL____ROLLERCARD] = cui_Panel____RollerCard;
    children[UI_COMP_PANEL____ROLLERCARD_CONTAINER____ROLLERS] = cui_Container____Rollers;
    children[UI_COMP_PANEL____ROLLERCARD_ROLLERSMALL____ROLLERSMALL] = cui_RollerSmall____RollerSmall;
    children[UI_COMP_PANEL____ROLLERCARD_ROLLERSMALL____ROLLERSMALL_LABEL____ROLLERSMALL_TITLE] = ui_comp_get_child(
                                                                                                      cui_RollerSmall____RollerSmall, UI_COMP_CONTAINER____ROLLERSMALL_LABEL____TITLE);
    children[UI_COMP_PANEL____ROLLERCARD_ROLLERSMALL____ROLLERSMALL_ROLLER____ROLLERSMALL_ROLLER] = ui_comp_get_child(
                                                                                                        cui_RollerSmall____RollerSmall, UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER);
    children[UI_COMP_PANEL____ROLLERCARD_ROLLERSMALL____ROLLERSMALL1] = cui_RollerSmall____RollerSmall1;
    children[UI_COMP_PANEL____ROLLERCARD_ROLLERSMALL____ROLLERSMALL1_LABEL____ROLLERSMALL1_TITLE] = ui_comp_get_child(
                                                                                                        cui_RollerSmall____RollerSmall1, UI_COMP_CONTAINER____ROLLERSMALL_LABEL____TITLE);
    children[UI_COMP_PANEL____ROLLERCARD_ROLLERSMALL____ROLLERSMALL1_ROLLER____ROLLERSMALL1_ROLLER] = ui_comp_get_child(
                                                                                                          cui_RollerSmall____RollerSmall1, UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER);
    children[UI_COMP_PANEL____ROLLERCARD_ROLLERSMALL____ROLLERSMALL2] = cui_RollerSmall____RollerSmall2;
    children[UI_COMP_PANEL____ROLLERCARD_ROLLERSMALL____ROLLERSMALL2_LABEL____ROLLERSMALL2_TITLE] = ui_comp_get_child(
                                                                                                        cui_RollerSmall____RollerSmall2, UI_COMP_CONTAINER____ROLLERSMALL_LABEL____TITLE);
    children[UI_COMP_PANEL____ROLLERCARD_ROLLERSMALL____ROLLERSMALL2_ROLLER____ROLLERSMALL2_ROLLER] = ui_comp_get_child(
                                                                                                          cui_RollerSmall____RollerSmall2, UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER);
    lv_obj_add_event_cb(cui_Panel____RollerCard, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Panel____RollerCard, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Panel____RollerCard_create_hook(cui_Panel____RollerCard);
    return cui_Panel____RollerCard;
}

