// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#ifndef _UI_COMP_DROPDOWN_H
#define _UI_COMP_DROPDOWN_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Dropdown
#define UI_COMP_CONTAINER____DROPDOWN_CONTAINER____DROPDOWN 0
#define UI_COMP_CONTAINER____DROPDOWN_CONTAINER____LABEL_GROUP 1
#define UI_COMP_CONTAINER____DROPDOWN_CONTAINER____LABEL_GROUP_LABEL____TITLE 2
#define UI_COMP_CONTAINER____DROPDOWN_DROPDOWN____DROP 3
#define _UI_COMP_CONTAINER____DROPDOWN_NUM 4
lv_obj_t * ui_Container____Dropdown_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
