// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "../ui.h"


// COMPONENT Input

lv_obj_t * ui_Container____Input_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Container____Input;
    cui_Container____Input = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_Container____Input);
    lv_obj_set_width(cui_Container____Input, 258);
    lv_obj_set_height(cui_Container____Input, LV_SIZE_CONTENT);    /// 86
    lv_obj_set_align(cui_Container____Input, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Container____Input, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_Container____Input, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_Container____Input, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(cui_Container____Input, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_Container____Input, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Container____Label_padding;
    cui_Container____Label_padding = lv_obj_create(cui_Container____Input);
    lv_obj_remove_style_all(cui_Container____Label_padding);
    lv_obj_set_width(cui_Container____Label_padding, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(cui_Container____Label_padding, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Container____Label_padding, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Container____Label_padding, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label____Label;
    cui_Label____Label = lv_label_create(cui_Container____Label_padding);
    lv_obj_set_width(cui_Label____Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label____Label, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_align(cui_Label____Label, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label____Label, "Serial Number");
    ui_object_set_themeable_style_property(cui_Label____Label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(cui_Label____Label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(cui_Label____Label, &ui_font_P3_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_Label____Label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Label____Label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Label____Label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Label____Label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Textarea____TextArea1;
    cui_Textarea____TextArea1 = lv_textarea_create(cui_Container____Input);
    lv_obj_set_width(cui_Textarea____TextArea1, lv_pct(100));
    lv_obj_set_height(cui_Textarea____TextArea1, LV_SIZE_CONTENT);    /// 56
    lv_obj_set_x(cui_Textarea____TextArea1, -157);
    lv_obj_set_y(cui_Textarea____TextArea1, -12);
    lv_obj_set_align(cui_Textarea____TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(cui_Textarea____TextArea1, "0-99999");
    lv_textarea_set_one_line(cui_Textarea____TextArea1, true);
    ui_object_set_themeable_style_property(cui_Textarea____TextArea1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(cui_Textarea____TextArea1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(cui_Textarea____TextArea1, &ui_font_P2_Med, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_Textarea____TextArea1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Textarea____TextArea1, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Purple);
    ui_object_set_themeable_style_property(cui_Textarea____TextArea1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple);
    lv_obj_set_style_border_width(cui_Textarea____TextArea1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_Textarea____TextArea1, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Textarea____TextArea1, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Textarea____TextArea1, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Textarea____TextArea1, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Textarea____TextArea1, &ui_font_P2_Med, LV_PART_MAIN | LV_STATE_FOCUSED);
    ui_object_set_themeable_style_property(cui_Textarea____TextArea1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BG_Purple);
    ui_object_set_themeable_style_property(cui_Textarea____TextArea1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BG_Purple);
    ui_object_set_themeable_style_property(cui_Textarea____TextArea1, LV_PART_MAIN | LV_STATE_FOCUSED,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Purple);
    ui_object_set_themeable_style_property(cui_Textarea____TextArea1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple);
    lv_obj_set_style_border_width(cui_Textarea____TextArea1, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_left(cui_Textarea____TextArea1, 14, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_right(cui_Textarea____TextArea1, 14, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_top(cui_Textarea____TextArea1, 13, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_bottom(cui_Textarea____TextArea1, 13, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_object_set_themeable_style_property(cui_Textarea____TextArea1, LV_PART_SELECTED | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Purple);
    ui_object_set_themeable_style_property(cui_Textarea____TextArea1, LV_PART_SELECTED | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Purple);
    lv_obj_set_style_border_width(cui_Textarea____TextArea1, 4, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(cui_Textarea____TextArea1, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Placeholder);
    ui_object_set_themeable_style_property(cui_Textarea____TextArea1, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Placeholder);
    lv_obj_set_style_text_font(cui_Textarea____TextArea1, &ui_font_P2_Med, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINER____INPUT_NUM);
    children[UI_COMP_CONTAINER____INPUT_CONTAINER____INPUT] = cui_Container____Input;
    children[UI_COMP_CONTAINER____INPUT_CONTAINER____LABEL_PADDING] = cui_Container____Label_padding;
    children[UI_COMP_CONTAINER____INPUT_CONTAINER____LABEL_PADDING_LABEL____LABEL] = cui_Label____Label;
    children[UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1] = cui_Textarea____TextArea1;
    lv_obj_add_event_cb(cui_Container____Input, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Container____Input, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Container____Input_create_hook(cui_Container____Input);
    return cui_Container____Input;
}

