// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "../ui.h"


// COMPONENT MenuButton

lv_obj_t * ui_Button____MenuButton_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Button____MenuButton;
    cui_Button____MenuButton = lv_button_create(comp_parent);
    lv_obj_set_width(cui_Button____MenuButton, lv_pct(100));
    lv_obj_set_flex_grow(cui_Button____MenuButton, 1);
    lv_obj_set_align(cui_Button____MenuButton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Button____MenuButton, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_Button____MenuButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(cui_Button____MenuButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_Button____MenuButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(cui_Button____MenuButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_White);
    ui_object_set_themeable_style_property(cui_Button____MenuButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_White);
    lv_obj_set_style_pad_left(cui_Button____MenuButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Button____MenuButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Button____MenuButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Button____MenuButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_Button____MenuButton, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_Button____MenuButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Button____MenuButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(cui_Button____MenuButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(cui_Button____MenuButton, &ui_font_P3_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Button____MenuButton, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Purple);
    ui_object_set_themeable_style_property(cui_Button____MenuButton, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Purple);
    ui_object_set_themeable_style_property(cui_Button____MenuButton, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_White);
    ui_object_set_themeable_style_property(cui_Button____MenuButton, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_White);

    lv_obj_t * cui_Image____Icon;
    cui_Image____Icon = lv_image_create(cui_Button____MenuButton);
    lv_image_set_src(cui_Image____Icon, ui_img_home_house_png);
    lv_obj_set_width(cui_Image____Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image____Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Image____Icon, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Image____Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(cui_Image____Icon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(cui_Image____Icon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA,
                                           _ui_theme_alpha_Dark_blue);
    ui_object_set_themeable_style_property(cui_Image____Icon, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_White);
    ui_object_set_themeable_style_property(cui_Image____Icon, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_IMAGE_RECOLOR_OPA,
                                           _ui_theme_alpha_White);

    lv_obj_t * cui_Label____Label;
    cui_Label____Label = lv_label_create(cui_Button____MenuButton);
    lv_obj_set_width(cui_Label____Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label____Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label____Label, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label____Label, "MENU");

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON____MENUBUTTON_NUM);
    children[UI_COMP_BUTTON____MENUBUTTON_BUTTON____MENUBUTTON] = cui_Button____MenuButton;
    children[UI_COMP_BUTTON____MENUBUTTON_IMAGE____ICON] = cui_Image____Icon;
    children[UI_COMP_BUTTON____MENUBUTTON_LABEL____LABEL] = cui_Label____Label;
    lv_obj_add_event_cb(cui_Button____MenuButton, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Button____MenuButton, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Button____MenuButton_create_hook(cui_Button____MenuButton);
    return cui_Button____MenuButton;
}

