// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "../ui.h"


// COMPONENT Menu

lv_obj_t * ui_Container____Menu_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Container____Menu;
    cui_Container____Menu = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_Container____Menu);
    lv_obj_set_width(cui_Container____Menu, lv_pct(100));
    lv_obj_set_flex_grow(cui_Container____Menu, 1);
    lv_obj_set_align(cui_Container____Menu, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Container____Menu, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_Container____Menu, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_Container____Menu, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Container____Menu, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Container____Menu, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Border);
    ui_object_set_themeable_style_property(cui_Container____Menu, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Border);
    lv_obj_set_style_clip_corner(cui_Container____Menu, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Container____Menu, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_OUTLINE_COLOR,
                                           _ui_theme_color_Border);
    ui_object_set_themeable_style_property(cui_Container____Menu, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_OUTLINE_OPA,
                                           _ui_theme_alpha_Border);
    lv_obj_set_style_outline_width(cui_Container____Menu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(cui_Container____Menu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_Container____Menu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_Container____Menu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_MenuButton____Menu_Button_Home;
    cui_MenuButton____Menu_Button_Home = ui_Button____MenuButton_create(cui_Container____Menu);
    lv_obj_set_x(cui_MenuButton____Menu_Button_Home, 0);
    lv_obj_set_y(cui_MenuButton____Menu_Button_Home, 0);

    lv_obj_t * cui_MenuButton____Menu_Button_Pump;
    cui_MenuButton____Menu_Button_Pump = ui_Button____MenuButton_create(cui_Container____Menu);
    lv_obj_set_x(cui_MenuButton____Menu_Button_Pump, 0);
    lv_obj_set_y(cui_MenuButton____Menu_Button_Pump, 0);

    lv_image_set_src(ui_comp_get_child(cui_MenuButton____Menu_Button_Pump, UI_COMP_BUTTON____MENUBUTTON_IMAGE____ICON),
                     ui_img_home_pump_png);

    lv_label_set_text(ui_comp_get_child(cui_MenuButton____Menu_Button_Pump, UI_COMP_BUTTON____MENUBUTTON_LABEL____LABEL),
                      "PUMP");

    lv_obj_t * cui_MenuButton____Menu_Button_Setup;
    cui_MenuButton____Menu_Button_Setup = ui_Button____MenuButton_create(cui_Container____Menu);
    lv_obj_set_x(cui_MenuButton____Menu_Button_Setup, 0);
    lv_obj_set_y(cui_MenuButton____Menu_Button_Setup, 0);

    lv_image_set_src(ui_comp_get_child(cui_MenuButton____Menu_Button_Setup, UI_COMP_BUTTON____MENUBUTTON_IMAGE____ICON),
                     ui_img_home_setup_png);

    lv_label_set_text(ui_comp_get_child(cui_MenuButton____Menu_Button_Setup, UI_COMP_BUTTON____MENUBUTTON_LABEL____LABEL),
                      "SETUP");

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINER____MENU_NUM);
    children[UI_COMP_CONTAINER____MENU_CONTAINER____MENU] = cui_Container____Menu;
    children[UI_COMP_CONTAINER____MENU_MENUBUTTON____MENU_BUTTON_HOME] = cui_MenuButton____Menu_Button_Home;
    children[UI_COMP_CONTAINER____MENU_MENUBUTTON____MENU_BUTTON_HOME_IMAGE____MENU_BUTTON_HOME_ICON] = ui_comp_get_child(
                                                                                                            cui_MenuButton____Menu_Button_Home, UI_COMP_BUTTON____MENUBUTTON_IMAGE____ICON);
    children[UI_COMP_CONTAINER____MENU_MENUBUTTON____MENU_BUTTON_HOME_LABEL____MENU_BUTTON_HOME_LABEL] = ui_comp_get_child(
                                                                                                             cui_MenuButton____Menu_Button_Home, UI_COMP_BUTTON____MENUBUTTON_LABEL____LABEL);
    children[UI_COMP_CONTAINER____MENU_MENUBUTTON____MENU_BUTTON_PUMP] = cui_MenuButton____Menu_Button_Pump;
    children[UI_COMP_CONTAINER____MENU_MENUBUTTON____MENU_BUTTON_PUMP_IMAGE____MENU_BUTTON_PUMP_ICON] = ui_comp_get_child(
                                                                                                            cui_MenuButton____Menu_Button_Pump, UI_COMP_BUTTON____MENUBUTTON_IMAGE____ICON);
    children[UI_COMP_CONTAINER____MENU_MENUBUTTON____MENU_BUTTON_PUMP_LABEL____MENU_BUTTON_PUMP_LABEL] = ui_comp_get_child(
                                                                                                             cui_MenuButton____Menu_Button_Pump, UI_COMP_BUTTON____MENUBUTTON_LABEL____LABEL);
    children[UI_COMP_CONTAINER____MENU_MENUBUTTON____MENU_BUTTON_SETUP] = cui_MenuButton____Menu_Button_Setup;
    children[UI_COMP_CONTAINER____MENU_MENUBUTTON____MENU_BUTTON_SETUP_IMAGE____MENU_BUTTON_SETUP_ICON] = ui_comp_get_child(
                                                                                                              cui_MenuButton____Menu_Button_Setup, UI_COMP_BUTTON____MENUBUTTON_IMAGE____ICON);
    children[UI_COMP_CONTAINER____MENU_MENUBUTTON____MENU_BUTTON_SETUP_LABEL____MENU_BUTTON_SETUP_LABEL] =
        ui_comp_get_child(cui_MenuButton____Menu_Button_Setup, UI_COMP_BUTTON____MENUBUTTON_LABEL____LABEL);
    lv_obj_add_event_cb(cui_Container____Menu, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Container____Menu, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Container____Menu_create_hook(cui_Container____Menu);
    return cui_Container____Menu;
}

