// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "../ui.h"


// COMPONENT Switch

lv_obj_t * ui_Container____Switch_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Container____Switch;
    cui_Container____Switch = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_Container____Switch);
    lv_obj_set_width(cui_Container____Switch, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(cui_Container____Switch, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Container____Switch, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Container____Switch, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_Container____Switch, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Container____Switch, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(cui_Container____Switch, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_Container____Switch, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label____Label23;
    cui_Label____Label23 = lv_label_create(cui_Container____Switch);
    lv_obj_set_width(cui_Label____Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label____Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label____Label23, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label____Label23, "Restart on Power UP");
    ui_object_set_themeable_style_property(cui_Label____Label23, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(cui_Label____Label23, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_align(cui_Label____Label23, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label____Label23, &ui_font_P2_Med, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_width(cui_Label____Label23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_width(cui_Label____Label23, 160, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Switch____Switch3;
    cui_Switch____Switch3 = lv_switch_create(cui_Container____Switch);
    lv_obj_set_width(cui_Switch____Switch3, 84);
    lv_obj_set_height(cui_Switch____Switch3, 40);
    lv_obj_set_align(cui_Switch____Switch3, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(cui_Switch____Switch3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Switch____Switch3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Disabled);
    ui_object_set_themeable_style_property(cui_Switch____Switch3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Disabled);

    lv_obj_set_style_radius(cui_Switch____Switch3, 100, LV_PART_INDICATOR | LV_STATE_CHECKED);
    ui_object_set_themeable_style_property(cui_Switch____Switch3, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Green);
    ui_object_set_themeable_style_property(cui_Switch____Switch3, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Green);

    lv_obj_set_style_radius(cui_Switch____Switch3, 100, LV_PART_KNOB | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Switch____Switch3, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_White);
    ui_object_set_themeable_style_property(cui_Switch____Switch3, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_White);
    ui_object_set_themeable_style_property(cui_Switch____Switch3, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_Shadow);
    ui_object_set_themeable_style_property(cui_Switch____Switch3, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_Shadow);
    lv_obj_set_style_shadow_width(cui_Switch____Switch3, 14, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(cui_Switch____Switch3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_Switch____Switch3, -3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Switch____Switch3, -3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Switch____Switch3, -3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Switch____Switch3, -3, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINER____SWITCH_NUM);
    children[UI_COMP_CONTAINER____SWITCH_CONTAINER____SWITCH] = cui_Container____Switch;
    children[UI_COMP_CONTAINER____SWITCH_LABEL____LABEL23] = cui_Label____Label23;
    children[UI_COMP_CONTAINER____SWITCH_SWITCH____SWITCH3] = cui_Switch____Switch3;
    lv_obj_add_event_cb(cui_Container____Switch, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Container____Switch, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Container____Switch_create_hook(cui_Container____Switch);
    return cui_Container____Switch;
}

