// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "../ui.h"


// IMAGE DATA: assets/Checkbox/checked_Vector.png
const char * ui_img_checkbox_checked_vector_png = "S:assets/Checkbox/checked_Vector.png";
