// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "../ui.h"


// IMAGE DATA: assets/SplashFrames/Eldex-Splash-02.png
const char * ui_img_1103710656 = "S:assets/SplashFrames/Eldex-Splash-02.png";

//const char * ui_img_1103710656 = "./assets/SplashFrames/Eldex-Splash-02.png";
