// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "../ui.h"


// IMAGE DATA: assets/SplashFrames/Eldex-Splash-01.png
const char * ui_img_1103707581 = "S:assets/SplashFrames/Eldex-Splash-01.png";

//const char * ui_img_1103707581 = "./assets/SplashFrames/Eldex-Splash-01.png";
