// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "../ui.h"


// IMAGE DATA: assets/Home/Chevron_down.png
const char * ui_img_home_chevron_down_png = "S:assets/Home/Chevron_down.png";
