// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "../ui.h"


// IMAGE DATA: assets/SplashFrames/Eldex-Splash-14.png
const char * ui_img_1184774493 = "S:assets/SplashFrames/Eldex-Splash-14.png";

//const char * ui_img_1184774493 = "./assets/SplashFrames/Eldex-Splash-14.png";
