// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "../ui.h"


// IMAGE DATA: assets/Logo.png
const char * ui_img_logo_png = "S:assets/Logo.png";
