// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "../ui.h"


// IMAGE DATA: assets/arrow.png
const char * ui_img_arrow_png = "S:assets/arrow.png";
