// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void SplashVideo_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_Screen__StartupSplash
void ui_Screen__StartupSplash_screen_init(void);
void ui_event_Screen__StartupSplash(lv_event_t * e);
lv_obj_t * ui_Screen__StartupSplash;
lv_obj_t * ui_Image__StartupSplash__LogoVideo;
lv_obj_t * ui_Label__StartupSplash__FirwareVersion;
lv_obj_t * ui_Label__StartupSplash__GUIversion;
// CUSTOM VARIABLES


// SCREEN: ui_Screen__Initial_Setup
void ui_Screen__Initial_Setup_screen_init(void);
lv_obj_t * ui_Screen__Initial_Setup;
lv_obj_t * ui_Header__Initial_Setup__Header9;
lv_obj_t * ui_Image__Initial_Setup__Image9;
lv_obj_t * ui_Container__Initial_Setup__Content1;
lv_obj_t * ui_Container__Initial_Setup__Container2;
lv_obj_t * ui_Container__Initial_Setup__Inputs;
lv_obj_t * ui_Input__Initial_Setup__Input;
void ui_event_Input__Initial_Setup__Input_Textarea__Initial_Setup__Input_Serial_Number(lv_event_t * e);
lv_obj_t * ui_Input__Initial_Setup__Input1;
void ui_event_Input__Initial_Setup__Input1_Textarea__Initial_Setup__Input1_Model_Number(lv_event_t * e);
lv_obj_t * ui_Container__Initial_Setup__tab_Initial;
lv_obj_t * ui_Container__Initial_Setup__Container4;
lv_obj_t * ui_TabButton__Initial_Setup__TabButton1;
lv_obj_t * ui_TabButton__Initial_Setup__TabButton2;
lv_obj_t * ui_TabButton__Initial_Setup__TabButton3;
lv_obj_t * ui_Container__Initial_Setup__Container5;
lv_obj_t * ui_TabContentInitial__Initial_Setup__TabContentInitial;
lv_obj_t * ui_Container__Initial_Setup__Buttons;
lv_obj_t * ui_Container__Initial_Setup__Top_Buttons;
lv_obj_t * ui_Secondarybtn__Initial_Setup__Disabled;
void ui_event_Secondarybtn__Initial_Setup__Remote_Password_Button____Secondarybtn(lv_event_t * e);
lv_obj_t * ui_Secondarybtn__Initial_Setup__Remote_Password;
void ui_event_Secondarybtn__Initial_Setup__Select_Options_Button____Secondarybtn(lv_event_t * e);
lv_obj_t * ui_Secondarybtn__Initial_Setup__Select_Options;
void ui_event_Primarybtn__Initial_Setup__Next_Button____Primarybtn(lv_event_t * e);
lv_obj_t * ui_Primarybtn__Initial_Setup__Next;
void ui_event_Numpad_M__Initial_Setup__Numpad_M_Keyboard____Numpad_M(lv_event_t * e);
lv_obj_t * ui_Numpad_M__Initial_Setup__Numpad_M;
// CUSTOM VARIABLES
lv_obj_t * ui_Image__Initial_Setup__USB_Status;
lv_obj_t * ui_Image__Initial_Setup__Ethernet_Status;
lv_obj_t * ui_Image__Initial_Setup__WiFi_Status;
lv_obj_t * ui_Textarea__Initial_Setup__Serial_Number;
lv_obj_t * ui_Textarea__Initial_Setup__Model_Number;
lv_obj_t * ui_Button__Initial_Setup__Pump1;
lv_obj_t * ui_Button__Initial_Setup__Pump2;
lv_obj_t * ui_Button__Initial_Setup__Pump3;
lv_obj_t * ui_Roller__Initial_Setup__PistonSize;
lv_obj_t * ui_Roller__Initial_Setup__StrokeLength;
lv_obj_t * ui_Roller__Initial_Setup__WettedParts;
lv_obj_t * ui_Button__Initial_Setup__FactoryTest;
lv_obj_t * ui_Button__Initial_Setup__ChangeRemotePassword;
lv_obj_t * ui_Button__Initial_Setup__SelectOptions;
lv_obj_t * ui_Button__Initial_Setup__Next;
lv_obj_t * ui_Keyboard__Initial_Setup__NumberEntry;


// SCREEN: ui_Screen__Select_Option
void ui_Screen__Select_Option_screen_init(void);
lv_obj_t * ui_Screen__Select_Option;
lv_obj_t * ui_Header__Select_Option__Header11;
lv_obj_t * ui_Image__Select_Option__Image11;
lv_obj_t * ui_Container__Select_Option__Content2;
lv_obj_t * ui_Panel__Select_Option__Group;
lv_obj_t * ui_Container__Select_Option__Left;
lv_obj_t * ui_Checkboxoption__Select_Option__Checkboxoption10;
lv_obj_t * ui_Checkboxoption__Select_Option__Checkboxoption5;
lv_obj_t * ui_Checkboxoption__Select_Option__Checkboxoption6;
lv_obj_t * ui_Container__Select_Option__Right;
lv_obj_t * ui_Checkboxoption__Select_Option__Checkboxoption7;
lv_obj_t * ui_Checkboxoption__Select_Option__Checkboxoption8;
void ui_event_Primarybtn__Select_Option__OK_3_Button____Primarybtn(lv_event_t * e);
lv_obj_t * ui_Primarybtn__Select_Option__OK_3;
// CUSTOM VARIABLES
lv_obj_t * ui_Image__Select_Option__USB_Status;
lv_obj_t * ui_Image__Select_Option__Ethernet_Status;
lv_obj_t * ui_Image__Select_Option__WiFi_Status;
lv_obj_t * ui_Checkbox__Select_Option__PressureTransducer;
lv_obj_t * ui_Checkbox__Select_Option__WashPort_Pump;
lv_obj_t * ui_Checkbox__Select_Option__LeakDetector_Sensor;
lv_obj_t * ui_Checkbox__Select_Option__FlowSensor;
lv_obj_t * ui_Checkbox__Select_Option__Encoder;
lv_obj_t * ui_Button__Select_Option__OK;


// SCREEN: ui_Screen__Generic_Password
void ui_Screen__Generic_Password_screen_init(void);
lv_obj_t * ui_Screen__Generic_Password;
lv_obj_t * ui_Header__Generic_Password__Header2;
lv_obj_t * ui_Image__Generic_Password__Image12;
lv_obj_t * ui_Container__Generic_Password__Content3;
lv_obj_t * ui_Panel__Generic_Password__Panel1;
lv_obj_t * ui_Input__Generic_Password__Remote_PIN4;
void ui_event_Secondarybtn__Generic_Password__Secondarybtn3_Button____Secondarybtn(lv_event_t * e);
lv_obj_t * ui_Secondarybtn__Generic_Password__Secondarybtn3;
void ui_event_Primarybtn__Generic_Password__OK_4_Button____Primarybtn(lv_event_t * e);
lv_obj_t * ui_Primarybtn__Generic_Password__OK_4;
lv_obj_t * ui_KeyboardL__Generic_Password__KeyboardL2;
// CUSTOM VARIABLES
lv_obj_t * ui_Label__Generic_Password__ScreenTitle;
lv_obj_t * ui_Image__Generic_Password__USB_Status;
lv_obj_t * ui_Image__Generic_Password__Ethernet_Status;
lv_obj_t * ui_Image__Generic_Password__WiFi_Status;
lv_obj_t * ui_Label__Generic_Password__PasswordField_Title;
lv_obj_t * ui_Textarea__Generic_Password__PasswordField;
lv_obj_t * ui_Button__Generic_Password__Cancel;
lv_obj_t * ui_Button__Generic_Password__OK;
lv_obj_t * ui_Keyboard__Generic_Password__PasswordEntry;


// SCREEN: ui_Screen__Home
void ui_Screen__Home_screen_init(void);
lv_obj_t * ui_Screen__Home;
lv_obj_t * ui_Container__Home__Container1;
lv_obj_t * ui_Image__Home__Logo1;
lv_obj_t * ui_Menu__Home__Menu;
void ui_event_Menu__Home__Menu_MenuButton____Menu_Button_Pump(lv_event_t * e);
void ui_event_Menu__Home__Menu_MenuButton____Menu_Button_Setup(lv_event_t * e);
lv_obj_t * ui_Container__Home__Container3;
lv_obj_t * ui_Header__Home__Header;
lv_obj_t * ui_Container__Home__Content4;
lv_obj_t * ui_Container__Home__tab_Initial2;
lv_obj_t * ui_Container__Home__Container9;
lv_obj_t * ui_TabButton__Home__TabButton7;
lv_obj_t * ui_TabButton__Home__TabButton4;
lv_obj_t * ui_TabButton__Home__TabButton5;
lv_obj_t * ui_Container__Home__Container7;
lv_obj_t * ui_Container__Home__Container6;
lv_obj_t * ui_Container__Home__Container10;
lv_obj_t * ui_Container__Home__Container12;
lv_obj_t * ui_Label__Home__Label3;
lv_obj_t * ui_Container__Home__Container14;
lv_obj_t * ui_Label__Home__Label4;
lv_obj_t * ui_Container__Home__Container15;
lv_obj_t * ui_Label__Home__Label5;
lv_obj_t * ui_Container__Home__Container13;
lv_obj_t * ui_Label__Home__Label6;
lv_obj_t * ui_Label__Home__Label7;
lv_obj_t * ui_Container__Home__Buttons_Group;
lv_obj_t * ui_ContorlButton__Home__ContorlButton;
lv_obj_t * ui_ContorlButton__Home__ContorlButton1;
lv_obj_t * ui_Container__Home__Dispense_Group;
lv_obj_t * ui_Container__Home__Container105;
lv_obj_t * ui_Input__Home__Input24;
void ui_event_Input__Home__Input24_Textarea____TextArea1(lv_event_t * e);
lv_obj_t * ui_Input__Home__Input20;
void ui_event_Input__Home__Input20_Textarea____TextArea1(lv_event_t * e);
lv_obj_t * ui_Container__Home__Container106;
lv_obj_t * ui_Input__Home__Input21;
void ui_event_Input__Home__Input21_Textarea____TextArea1(lv_event_t * e);
lv_obj_t * ui_Input__Home__Input22;
void ui_event_Input__Home__Input22_Textarea____TextArea1(lv_event_t * e);
lv_obj_t * ui_Container__Home__Container8;
lv_obj_t * ui_Container__Home__Container16;
lv_obj_t * ui_Secondarybtn__Home__Select_Options2;
lv_obj_t * ui_Image__Home__Image6;
lv_obj_t * ui_Container__Home__Container17;
lv_obj_t * ui_Container__Home__Container19;
lv_obj_t * ui_Label__Home__Label8;
lv_obj_t * ui_Label__Home__Label9;
lv_obj_t * ui_Container__Home__Container20;
lv_obj_t * ui_Label__Home__Label10;
lv_obj_t * ui_Label__Home__Label11;
lv_obj_t * ui_Primarybtn__Home__Start;
lv_obj_t * ui_Container__Home__Footer;
lv_obj_t * ui_Label__Home__Label12;
void ui_event_Numpad_M__Home__Numpad_M2_Keyboard____Numpad_M(lv_event_t * e);
lv_obj_t * ui_Numpad_M__Home__Numpad_M2;
// CUSTOM VARIABLES
lv_obj_t * ui_MenuButton__Home__Menu;
lv_obj_t * ui_MenuButton__Home__Pump;
lv_obj_t * ui_MenuButton__Home__Setup;
lv_obj_t * ui_Label__Home__ScreenTitle;
lv_obj_t * ui_Image__Home__USB_Status;
lv_obj_t * ui_Image__Home__Ethernet_Status;
lv_obj_t * ui_Image__Home__WiFi_Status;
lv_obj_t * ui_Button__Home__Pump1;
lv_obj_t * ui_Button__Home__Pump2;
lv_obj_t * ui_Button__Home__Pump3;
lv_obj_t * ui_Label__Home__MainValue_Title;
lv_obj_t * ui_Label__Home__MainValue;
lv_obj_t * ui_Label__Home__MainValue_Unit;
lv_obj_t * ui_Label__Home__CurrentPressure;
lv_obj_t * ui_Container__Home__ButtonGroup;
lv_obj_t * ui_Button__Home__FlowOrPressure_Up;
lv_obj_t * ui_Button__Home__FlowOrPressure_Down;
lv_obj_t * ui_Container__Home__DispenseGroup;
lv_obj_t * ui_Textarea__Home__Dispense_FluidAmount;
lv_obj_t * ui_Textarea__Home__Dispense_PumpRunDuration;
lv_obj_t * ui_Textarea__Home__Dispense_RepeatDelay;
lv_obj_t * ui_Textarea__Home__Dispense_RepeatAmount;
lv_obj_t * ui_Button__Home__Purge;
lv_obj_t * ui_Label__Home__RunTime;
lv_obj_t * ui_Label__Home__Total_PumpedFlowAmount;
lv_obj_t * ui_Button__Home__StartStop;
lv_obj_t * ui_Label__Home__StatusFooter;
lv_obj_t * ui_Keyboard__Home__DispenseDataEntry;


// SCREEN: ui_Screen__Pump_Settings
void ui_Screen__Pump_Settings_screen_init(void);
lv_obj_t * ui_Screen__Pump_Settings;
lv_obj_t * ui_Container__Pump_Settings__Container37;
lv_obj_t * ui_Image__Pump_Settings__Logo3;
lv_obj_t * ui_Menu__Pump_Settings__Menu2;
void ui_event_Menu__Pump_Settings__Menu2_MenuButton____Menu_Button_Home(lv_event_t * e);
void ui_event_Menu__Pump_Settings__Menu2_MenuButton____Menu_Button_Setup(lv_event_t * e);
lv_obj_t * ui_Container__Pump_Settings__Container39;
lv_obj_t * ui_Header__Pump_Settings__Header3;
lv_obj_t * ui_Container__Pump_Settings__Content6;
lv_obj_t * ui_Container__Pump_Settings__tab_Initial3;
lv_obj_t * ui_Container__Pump_Settings__Container40;
lv_obj_t * ui_TabButton__Pump_Settings__TabButton10;
lv_obj_t * ui_TabButton__Pump_Settings__TabButton11;
lv_obj_t * ui_TabButton__Pump_Settings__TabButton12;
lv_obj_t * ui_Container__Pump_Settings__Container41;
lv_obj_t * ui_Container__Pump_Settings__Container42;
lv_obj_t * ui_Container__Pump_Settings__Container43;
lv_obj_t * ui_Container__Pump_Settings__Container44;
lv_obj_t * ui_Switch__Pump_Settings__Switch;
lv_obj_t * ui_Switch__Pump_Settings__Switch1;
lv_obj_t * ui_Container__Pump_Settings__Container47;
lv_obj_t * ui_Dropdown__Pump_Settings__Dropdown1;
lv_obj_t * ui_Dropdown__Pump_Settings__Dropdown2;
lv_obj_t * ui_Container__Pump_Settings__Container49;
lv_obj_t * ui_Container__Pump_Settings__Container45;
lv_obj_t * ui_Label__Pump_Settings__Label25;
lv_obj_t * ui_Label__Pump_Settings__Label24;
lv_obj_t * ui_Slider__Pump_Settings__Slider1;
lv_obj_t * ui_Container__Pump_Settings__Footer2;
lv_obj_t * ui_Label__Pump_Settings__Label32;
// CUSTOM VARIABLES
lv_obj_t * ui_MenuButton__Pump_Settings__Menu;
lv_obj_t * ui_MenuButton__Pump_Settings__Pump;
lv_obj_t * ui_MenuButton__Pump_Settings__Setup;
lv_obj_t * ui_Image__Pump_Settings__USB_Status;
lv_obj_t * ui_Image__Pump_Settings__Ethernet_Status;
lv_obj_t * ui_Image__Pump_Settings__WiFi_Status;
lv_obj_t * ui_Button__Pump_Settings__Pump1;
lv_obj_t * ui_Button__Pump_Settings__Pump2;
lv_obj_t * ui_Button__Pump_Settings__Pump3;
lv_obj_t * ui_Switch__Pump_Settings__RestartOnPowerup;
lv_obj_t * ui_Switch__Pump_Settings__StopOnStall;
lv_obj_t * ui_Dropdown__Pump_Settings__Property;
lv_obj_t * ui_Dropdown__Pump_Settings__Value;
lv_obj_t * ui_Label__Pump_Settings__CompressibilityCompensation_Value;
lv_obj_t * ui_Slider__Pump_Settings__CompressibilityCompensation_Value;
lv_obj_t * ui_Label__Pump_Settings__StatusFooter;


// SCREEN: ui_Screen__Advanced_Settings
void ui_Screen__Advanced_Settings_screen_init(void);
lv_obj_t * ui_Screen__Advanced_Settings;
lv_obj_t * ui_Container__Advanced_Settings__Container46;
lv_obj_t * ui_Image__Advanced_Settings__Logo4;
lv_obj_t * ui_Menu__Advanced_Settings__Menu3;
void ui_event_Menu__Advanced_Settings__Menu3_MenuButton____Menu_Button_Home(lv_event_t * e);
void ui_event_Menu__Advanced_Settings__Menu3_MenuButton____Menu_Button_Pump(lv_event_t * e);
lv_obj_t * ui_Container__Advanced_Settings__Container48;
lv_obj_t * ui_Header__Advanced_Settings__Header4;
lv_obj_t * ui_Container__Advanced_Settings__Content7;
lv_obj_t * ui_Container__Advanced_Settings__Content;
lv_obj_t * ui_Container__Advanced_Settings__Container51;
lv_obj_t * ui_Container__Advanced_Settings__Container52;
lv_obj_t * ui_Container__Advanced_Settings__Container53;
lv_obj_t * ui_Container__Advanced_Settings__Container54;
lv_obj_t * ui_Label__Advanced_Settings__Label26;
lv_obj_t * ui_Container__Advanced_Settings__Container55;
lv_obj_t * ui_Container__Advanced_Settings__Container50;
lv_obj_t * ui_Input__Advanced_Settings__Input6;
void ui_event_Input__Advanced_Settings__Input6_Textarea__Advanced_Settings__Input6_TextAreaPAI1(lv_event_t * e);
lv_obj_t * ui_Image__Advanced_Settings__Image8;
lv_obj_t * ui_Input__Advanced_Settings__Input7;
void ui_event_Input__Advanced_Settings__Input7_Textarea__Advanced_Settings__Input7_TextAreaPAI2(lv_event_t * e);
lv_obj_t * ui_Container__Advanced_Settings__Container56;
lv_obj_t * ui_Label__Advanced_Settings__Label28;
lv_obj_t * ui_Switch__Advanced_Settings__Switch2;
lv_obj_t * ui_Container__Advanced_Settings__Container57;
lv_obj_t * ui_RollerSmall__Advanced_Settings__RollerSmall4;
lv_obj_t * ui_Container__Advanced_Settings__Container59;
lv_obj_t * ui_Container__Advanced_Settings__Container60;
void ui_event_Secondarybtn__Advanced_Settings__Select_Options3_Button____Secondarybtn(lv_event_t * e);
lv_obj_t * ui_Secondarybtn__Advanced_Settings__Select_Options3;
void ui_event_Secondarybtn__Advanced_Settings__Select_Options4_Button____Secondarybtn(lv_event_t * e);
lv_obj_t * ui_Secondarybtn__Advanced_Settings__Select_Options4;
void ui_event_Secondarybtn__Advanced_Settings__Select_Options5_Button____Secondarybtn(lv_event_t * e);
lv_obj_t * ui_Secondarybtn__Advanced_Settings__Select_Options5;
void ui_event_Secondarybtn__Advanced_Settings__Select_Options6_Button____Secondarybtn(lv_event_t * e);
lv_obj_t * ui_Secondarybtn__Advanced_Settings__Select_Options6;
void ui_event_Secondarybtn__Advanced_Settings__Select_Options7_Button____Secondarybtn(lv_event_t * e);
lv_obj_t * ui_Secondarybtn__Advanced_Settings__Select_Options7;
lv_obj_t * ui_Container__Advanced_Settings__Container61;
lv_obj_t * ui_Container__Advanced_Settings__Container62;
lv_obj_t * ui_Label__Advanced_Settings__Label31;
lv_obj_t * ui_Label__Advanced_Settings__Label35;
lv_obj_t * ui_Primarybtn__Advanced_Settings__Reset;
lv_obj_t * ui_Container__Advanced_Settings__Footer3;
lv_obj_t * ui_Label__Advanced_Settings__Label36;
void ui_event_KeyboardL__Advanced_Settings__KeyboardL4_Keyboard____KeyboardL(lv_event_t * e);
lv_obj_t * ui_KeyboardL__Advanced_Settings__KeyboardL4;
// CUSTOM VARIABLES
lv_obj_t * ui_MenuButton__Advanced_Settings__Menu;
lv_obj_t * ui_MenuButton__Advanced_Settings__Pump;
lv_obj_t * ui_MenuButton__Advanced_Settings__Setup;
lv_obj_t * ui_Image__Advanced_Settings__USB_Status;
lv_obj_t * ui_Image__Advanced_Settings__Ethernet_Status;
lv_obj_t * ui_Image__Advanced_Settings__WiFi_Status;
lv_obj_t * ui_Textarea__Advanced_Settings__PressureAlarm_Min;
lv_obj_t * ui_Textarea__Advanced_Settings__PressureAlarm_Max;
lv_obj_t * ui_Switch__Advanced_Settings__PressureLimit_Enable;
lv_obj_t * ui_Roller__Advanced_Settings__PressureUnit;
lv_obj_t * ui_Button__Advanced_Settings__FirmwareUpdate;
lv_obj_t * ui_Button__Advanced_Settings__Maintenance;
lv_obj_t * ui_Button__Advanced_Settings__Communications;
lv_obj_t * ui_Button__Advanced_Settings__FactoryMenu;
lv_obj_t * ui_Button__Advanced_Settings__SelfTest;
lv_obj_t * ui_Label__Advanced_Settings__DateAndTime;
lv_obj_t * ui_Button__Advanced_Settings__FactoryReset;
lv_obj_t * ui_Label__Advanced_Settings__StatusFooter;
lv_obj_t * ui_Keyboard__Advanced_Settings__PressureAlarmInterval_Entry;


// SCREEN: ui_Screen__Firmware_Update
void ui_Screen__Firmware_Update_screen_init(void);
lv_obj_t * ui_Screen__Firmware_Update;
lv_obj_t * ui_Container__Firmware_Update__Container63;
lv_obj_t * ui_Header__Firmware_Update__Header5;
void ui_event_Header__Firmware_Update__Header5_Button____Back_Button(lv_event_t * e);
lv_obj_t * ui_Container__Firmware_Update__Content8;
lv_obj_t * ui_Container__Firmware_Update__fw_contents;
lv_obj_t * ui_Container__Firmware_Update__Update_Buttons;
lv_obj_t * ui_Container__Firmware_Update__Container73;
lv_obj_t * ui_Container__Firmware_Update__Container74;
lv_obj_t * ui_Container__Firmware_Update__Container75;
lv_obj_t * ui_Label__Firmware_Update__Label39;
lv_obj_t * ui_Label__Firmware_Update__Label40;
lv_obj_t * ui_Container__Firmware_Update__Container64;
lv_obj_t * ui_Primarybtn__Firmware_Update__Next5;
lv_obj_t * ui_Primarybtn__Firmware_Update__Next3;
lv_obj_t * ui_Container__Firmware_Update__Update_Bar;
lv_obj_t * ui_Container__Firmware_Update__Container69;
lv_obj_t * ui_Label__Firmware_Update__Label29;
lv_obj_t * ui_Bar__Firmware_Update__Bar1;
lv_obj_t * ui_Container__Firmware_Update__Footer4;
lv_obj_t * ui_Label__Firmware_Update__Label41;
// CUSTOM VARIABLES
lv_obj_t * ui_Button__Firmware_Update__Back;
lv_obj_t * ui_Image__Firmware_Update__USB_Status;
lv_obj_t * ui_Image__Firmware_Update__Ethernet_Status;
lv_obj_t * ui_Image__Firmware_Update__WiFi_Status;
lv_obj_t * ui_Container__Firmware_Update__Start;
lv_obj_t * ui_Container__Firmware_Update__StartQuestion;
lv_obj_t * ui_Label__Firmware_Update__CurrentVersion;
lv_obj_t * ui_Container__Firmware_Update__UpdateButtons;
lv_obj_t * ui_Button__Firmware_Update__UpdateFromWeb;
lv_obj_t * ui_Button__Firmware_Update__UpdateFromFlashdrive;
lv_obj_t * ui_Container__Firmware_Update__UpdateProgress;
lv_obj_t * ui_Label__Firmware_Update__InstallationProgress;
lv_obj_t * ui_Bar__Firmware_Update__InstallationProgress;
lv_obj_t * ui_Label__Firmware_Update__StatusFooter;


// SCREEN: ui_Screen__Maintenance
void ui_Screen__Maintenance_screen_init(void);
lv_obj_t * ui_Screen__Maintenance;
lv_obj_t * ui_Container__Maintenance__Container66;
lv_obj_t * ui_Header__Maintenance__Header6;
void ui_event_Header__Maintenance__Header6_Button____Back_Button(lv_event_t * e);
lv_obj_t * ui_Container__Maintenance__Content9;
lv_obj_t * ui_Container__Maintenance__Container85;
lv_obj_t * ui_Input__Maintenance__Input9;
void ui_event_Input__Maintenance__Input9_Textarea__Maintenance__Input9_TextAreaSN(lv_event_t * e);
lv_obj_t * ui_Input__Maintenance__Input10;
void ui_event_Input__Maintenance__Input10_Textarea__Maintenance__Input10_TextAreaMN(lv_event_t * e);
lv_obj_t * ui_Container__Maintenance__Container76;
lv_obj_t * ui_Input__Maintenance__Input11;
void ui_event_Input__Maintenance__Input11_Textarea__Maintenance__Input11_TextAreaFW(lv_event_t * e);
lv_obj_t * ui_Input__Maintenance__Input12;
void ui_event_Input__Maintenance__Input12_Textarea__Maintenance__Input12_TextAreaGUI(lv_event_t * e);
lv_obj_t * ui_Input__Maintenance__Input13;
void ui_event_Input__Maintenance__Input13_Textarea__Maintenance__Input13_TextAreaTR(lv_event_t * e);
lv_obj_t * ui_Panel__Maintenance__Panel2;
lv_obj_t * ui_Container__Maintenance__Container79;
lv_obj_t * ui_Label__Maintenance__Label30;
lv_obj_t * ui_Secondarybtn__Maintenance__Select_Options9;
lv_obj_t * ui_Container__Maintenance__Container81;
lv_obj_t * ui_Label__Maintenance__Label27;
lv_obj_t * ui_Switch__Maintenance__Switch4;
lv_obj_t * ui_Container__Maintenance__Container82;
lv_obj_t * ui_Label__Maintenance__Label38;
lv_obj_t * ui_Container__Maintenance__tab_Initial4;
lv_obj_t * ui_Container__Maintenance__Container67;
lv_obj_t * ui_TabButton__Maintenance__TabButton13;
lv_obj_t * ui_TabButton__Maintenance__TabButton14;
lv_obj_t * ui_TabButton__Maintenance__TabButton15;
lv_obj_t * ui_Container__Maintenance__Container68;
lv_obj_t * ui_Container__Maintenance__Container70;
lv_obj_t * ui_Container__Maintenance__Container78;
lv_obj_t * ui_RollerSmall__Maintenance__RollerSmall5;
lv_obj_t * ui_Input__Maintenance__Input8;
void ui_event_Input__Maintenance__Input8_Textarea__Maintenance__Input8_TextArea_Reminder(lv_event_t * e);
lv_obj_t * ui_Container__Maintenance__Container77;
lv_obj_t * ui_Container__Maintenance__Container71;
lv_obj_t * ui_Container__Maintenance__Container87;
lv_obj_t * ui_Label__Maintenance__Label37;
lv_obj_t * ui_Label__Maintenance__Label33;
lv_obj_t * ui_Container__Maintenance__Container72;
lv_obj_t * ui_Secondarybtn__Maintenance__Select_Options10;
lv_obj_t * ui_Container__Maintenance__Container80;
lv_obj_t * ui_Primarybtn__Maintenance__Next6;
lv_obj_t * ui_Primarybtn__Maintenance__Next7;
lv_obj_t * ui_Container__Maintenance__Footer5;
lv_obj_t * ui_Label__Maintenance__Label45;
void ui_event_KeyboardL__Maintenance__KeyboardMainL1_Keyboard____KeyboardL(lv_event_t * e);
lv_obj_t * ui_KeyboardL__Maintenance__KeyboardMainL1;
void ui_event_KeyboardL__Maintenance__KeyboardMainL5_Keyboard____KeyboardL(lv_event_t * e);
lv_obj_t * ui_KeyboardL__Maintenance__KeyboardMainL5;
// CUSTOM VARIABLES
lv_obj_t * ui_Button__Maintenance__Back;
lv_obj_t * ui_Image__Maintenance__USB_Status;
lv_obj_t * ui_Image__Maintenance__Ethernet_Status;
lv_obj_t * ui_Image__Maintenance__WiFi_Status;
lv_obj_t * ui_Textarea__Maintenance__SerialNumber;
lv_obj_t * ui_Textarea__Maintenance__ModelNumber;
lv_obj_t * ui_Textarea__Maintenance__FirmwareVersion;
lv_obj_t * ui_Textarea__Maintenance__GUIversion;
lv_obj_t * ui_Textarea__Maintenance__Pump1_TotalRun;
lv_obj_t * ui_Button__Maintenance__Washport_Rinse;
lv_obj_t * ui_Switch__Maintenance__Washport_Auto;
lv_obj_t * ui_Button__Maintenance__Pump1;
lv_obj_t * ui_Button__Maintenance__Pump2;
lv_obj_t * ui_Button__Maintenance__Pump3;
lv_obj_t * ui_Roller__Maintenance__PumpPart;
lv_obj_t * ui_Textarea__Maintenance__PumpPart_RuntimeReminder_Period;
lv_obj_t * ui_Label__Maintenance__PumpPart_Runtime;
lv_obj_t * ui_Button__Maintenance__Reset_PumpPart_Runtime;
lv_obj_t * ui_Button__Maintenance__ZeroPressure_Transducer;
lv_obj_t * ui_Button__Maintenance__Sensor_MoveMotorsHome;
lv_obj_t * ui_Label__Maintenance__StatusFooter;
lv_obj_t * ui_Keyboard__Maintenance__PumpPart_RuntimeReminderPeriod_Entry;
lv_obj_t * ui_Keyboard__Maintenance__LeftSideFields_Entry;


// SCREEN: ui_Screen__Self_Test
void ui_Screen__Self_Test_screen_init(void);
lv_obj_t * ui_Screen__Self_Test;
lv_obj_t * ui_Container__Self_Test__Container58;
lv_obj_t * ui_Header__Self_Test__Header7;
void ui_event_Header__Self_Test__Header7_Button____Back_Button(lv_event_t * e);
lv_obj_t * ui_Container__Self_Test__Content10;
lv_obj_t * ui_Container__Self_Test__Container89;
lv_obj_t * ui_Container__Self_Test__Container91;
lv_obj_t * ui_Textarea__Self_Test__TextArea_Reminder1;
lv_obj_t * ui_Container__Self_Test__Container98;
lv_obj_t * ui_Secondarybtn__Self_Test__Select_Options11;
lv_obj_t * ui_Primarybtn__Self_Test__Next9;
lv_obj_t * ui_Container__Self_Test__Footer6;
lv_obj_t * ui_Label__Self_Test__Label47;
// CUSTOM VARIABLES
lv_obj_t * ui_Button__Self_Test__Back;
lv_obj_t * ui_Image__Self_Test__USB_Status;
lv_obj_t * ui_Image__Self_Test__Ethernet_Status;
lv_obj_t * ui_Image__Self_Test__WiFi_Status;
lv_obj_t * ui_Textarea__Self_Test__SelfTest_LogConsole;
lv_obj_t * ui_Button__Self_Test__SaveToFlashdrive;
lv_obj_t * ui_Button__Self_Test__Run_SelfTest;
lv_obj_t * ui_Label__Self_Test__StatusFooter;


// SCREEN: ui_Screen__Communications
void ui_Screen__Communications_screen_init(void);
void ui_event_Screen__Communications(lv_event_t * e);
lv_obj_t * ui_Screen__Communications;
lv_obj_t * ui_Header__Communications__Header8;
void ui_event_Header__Communications__Header8_Button____Back_Button(lv_event_t * e);
lv_obj_t * ui_Image__Communications__Image7;
lv_obj_t * ui_Container__Communications__Content;
lv_obj_t * ui_Container__Communications__Container65;
lv_obj_t * ui_Container__Communications__group;
lv_obj_t * ui_Container__Communications__Container83;
lv_obj_t * ui_TabButton__Communications__TabButton16;
lv_obj_t * ui_TabButton__Communications__TabButton17;
lv_obj_t * ui_TabButton__Communications__TabButton18;
lv_obj_t * ui_Container__Communications__Serial_Content;
lv_obj_t * ui_Container__Communications__Container88;
lv_obj_t * ui_Container__Communications__Container92;
lv_obj_t * ui_Panel__Communications__Panel3;
lv_obj_t * ui_Panel__Communications__Panel4;
lv_obj_t * ui_Panel__Communications__Panel5;
lv_obj_t * ui_RollerSmall__Communications__RollerSmall11;
lv_obj_t * ui_RollerSmall__Communications__RollerSmall12;
lv_obj_t * ui_Container__Communications__Container93;
lv_obj_t * ui_Container__Communications__Container94;
lv_obj_t * ui_RollerSmall__Communications__RollerSmall13;
lv_obj_t * ui_Container__Communications__Container95;
lv_obj_t * ui_Switch__Communications__Switch5;
lv_obj_t * ui_Container__Communications__Container90;
lv_obj_t * ui_RollerSmall__Communications__RollerSmall6;
lv_obj_t * ui_RollerSmall__Communications__RollerSmall7;
lv_obj_t * ui_RollerSmall__Communications__RollerSmall8;
lv_obj_t * ui_RollerSmall__Communications__RollerSmall9;
lv_obj_t * ui_RollerSmall__Communications__RollerSmall10;
lv_obj_t * ui_Container__Communications__Ethernet_Content;
lv_obj_t * ui_Container__Communications__Container86;
lv_obj_t * ui_Input__Communications__Input14;
void ui_event_Input__Communications__Input14_Textarea__Communications__Input14_TextAreaIP(lv_event_t * e);
lv_obj_t * ui_Input__Communications__Input15;
void ui_event_Input__Communications__Input15_Textarea__Communications__Input15_TextAreaSUB(lv_event_t * e);
lv_obj_t * ui_Input__Communications__Input16;
void ui_event_Input__Communications__Input16_Textarea__Communications__Input16_TextAreaGate(lv_event_t * e);
lv_obj_t * ui_Input__Communications__Input17;
void ui_event_Input__Communications__Input17_Textarea__Communications__Input17_TextAreaDNS(lv_event_t * e);
lv_obj_t * ui_Container__Communications__Container101;
lv_obj_t * ui_Container__Communications__Container96;
lv_obj_t * ui_Checkbox__Communications__Checkbox2;
lv_obj_t * ui_Switch__Communications__Switch6;
lv_obj_t * ui_Container__Communications__Container97;
lv_obj_t * ui_Numpad_M__Communications__Numpad_M1;
lv_obj_t * ui_Container__Communications__WiFi_Content;
lv_obj_t * ui_Container__Communications__Container99;
lv_obj_t * ui_Container__Communications__Container100;
lv_obj_t * ui_Input__Communications__Input19;
void ui_event_Input__Communications__Input19_Textarea__Communications__Input19_TextAreaSSID(lv_event_t * e);
lv_obj_t * ui_RollerSmall__Communications__RollerSmall14;
lv_obj_t * ui_Container__Communications__Container103;
lv_obj_t * ui_Input__Communications__Input18;
void ui_event_Input__Communications__Input18_Textarea__Communications__Input18_TextAreaPAss(lv_event_t * e);
lv_obj_t * ui_RollerSmall__Communications__RollerSmall15;
lv_obj_t * ui_Container__Communications__Container104;
lv_obj_t * ui_Switch__Communications__Switch8;
lv_obj_t * ui_Secondarybtn__Communications__Select_Options12;
lv_obj_t * ui_Primarybtn__Communications__Next10;
lv_obj_t * ui_Container__Communications__Container102;
lv_obj_t * ui_Switch__Communications__Switch7;
lv_obj_t * ui_Checkbox__Communications__Checkbox3;
lv_obj_t * ui_Container__Communications__Footer8;
lv_obj_t * ui_Label__Communications__Label42;
void ui_event_KeyboardL__Communications__KeyboardWifi_Keyboard____KeyboardL(lv_event_t * e);
lv_obj_t * ui_KeyboardL__Communications__KeyboardWifi;
// CUSTOM VARIABLES
lv_obj_t * ui_Button__Communications__Back;
lv_obj_t * ui_Image__Communications__USB_Status;
lv_obj_t * ui_Image__Communications__Ethernet_Status;
lv_obj_t * ui_Image__Communications__WiFi_Status;
lv_obj_t * ui_Button__Communications__Serial;
lv_obj_t * ui_Button__Communications__Ethernet;
lv_obj_t * ui_Button__Communications__WiFi;
lv_obj_t * ui_Label__Communications__Serial_PumpSelector_Title;
lv_obj_t * ui_Roller__Communications__Serial_SelectPump;
lv_obj_t * ui_Label__Communications__Serial_AnalogControlPortSelector_Title;
lv_obj_t * ui_Roller__Communications__Serial_PumpAnalogControlPort;
lv_obj_t * ui_Roller__Communications__Serial_ProtocolTypeStandard;
lv_obj_t * ui_Switch__Communications__Serial_RemoteControl;
lv_obj_t * ui_Roller__Communications__Serial_DeviceID;
lv_obj_t * ui_Roller__Communications__Serial_BaudRate;
lv_obj_t * ui_Roller__Communications__Serial_DatabitsPerBaud;
lv_obj_t * ui_Roller__Communications__Serial_StopBitAmount;
lv_obj_t * ui_Roller__Communications__Serial_ParityBitType;
lv_obj_t * ui_Textarea__Communications__Ethernet_IPaddress;
lv_obj_t * ui_Textarea__Communications__Ethernet_SubnetMask;
lv_obj_t * ui_Textarea__Communications__Ethernet_GatewayIP;
lv_obj_t * ui_Textarea__Communications__Ethernet_DNSaddress;
lv_obj_t * ui_Checkbox__Communications__Ethernet_DHCP;
lv_obj_t * ui_Switch__Communications__Ethernet_RemoteControl;
lv_obj_t * ui_Keyboard__Communications__Ethernet_IPAddressEntry;
lv_obj_t * ui_Container__Communications__WiFi__LeftSide;
lv_obj_t * ui_Container__Communications__WiFi__SSID;
lv_obj_t * ui_Textarea__Communications__WiFi_SSID;
lv_obj_t * ui_Container__Communications__WiFi__SecurityType;
lv_obj_t * ui_Roller__Communications__WiFi_SecurityType;
lv_obj_t * ui_Container__Communications__WiFi__RightSide;
lv_obj_t * ui_Container__Communications__WiFi__Password;
lv_obj_t * ui_Textarea__Communications__WiFi_Password;
lv_obj_t * ui_Container__Communications__WiFi__SSIDlist;
lv_obj_t * ui_Roller__Communications__WiFi_SSIDlist;
lv_obj_t * ui_Switch__Communications__WiFi_RemoteControl;
lv_obj_t * ui_Button__Communications__WiFi_ForgetConnection;
lv_obj_t * ui_Button__Communications__WiFi_Connect;
lv_obj_t * ui_Switch__Communications__WiFi_ConnectToHiddenNetwork;
lv_obj_t * ui_Checkbox__Communications__WiFi_AutomaticConnection;
lv_obj_t * ui_Label__Communications__StatusFooter;
lv_obj_t * ui_Keyboard__Communications__WiFi_AuthenticationDataEntry;


// SCREEN: ui_Screen__Popup_Modal
void ui_Screen__Popup_Modal_screen_init(void);
lv_obj_t * ui_Screen__Popup_Modal;
lv_obj_t * ui_Popup__Popup_Modal__Popup;
// CUSTOM VARIABLES
lv_obj_t * ui_Panel__Popup_Modal__Full;
lv_obj_t * ui_Label__Popup_Modal__Title;
lv_obj_t * ui_Label__Popup_Modal__Text;
lv_obj_t * ui_Button__Popup_Modal__Left;
lv_obj_t * ui_ButtonLabel__Popup_Modal__Left;
lv_obj_t * ui_Button__Popup_Modal__Right;
lv_obj_t * ui_ButtonLabel__Popup_Modal__Right;

// EVENTS
lv_obj_t * ui_Startevents_______initial_actions0;

// IMAGES AND IMAGE SETS
const char * ui_imgset_910091477[15] = {"S:assets/SplashFrames/Eldex-Splash-01.png", "S:assets/SplashFrames/Eldex-Splash-02.png", "S:assets/SplashFrames/Eldex-Splash-03.png", "S:assets/SplashFrames/Eldex-Splash-04.png", "S:assets/SplashFrames/Eldex-Splash-05.png", "S:assets/SplashFrames/Eldex-Splash-06.png", "S:assets/SplashFrames/Eldex-Splash-07.png", "S:assets/SplashFrames/Eldex-Splash-08.png", "S:assets/SplashFrames/Eldex-Splash-09.png", "S:assets/SplashFrames/Eldex-Splash-10.png", "S:assets/SplashFrames/Eldex-Splash-11.png", "S:assets/SplashFrames/Eldex-Splash-12.png", "S:assets/SplashFrames/Eldex-Splash-13.png", "S:assets/SplashFrames/Eldex-Splash-14.png", "S:assets/SplashFrames/Eldex-Splash-15.png"};

const char * ui_imgset_option[1] = {"S:assets/Option1.png"};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void SplashVideo_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->imgset = (lv_img_dsc_t **)ui_imgset_910091477;
    PropertyAnimation_0_user_data->imgset_size = sizeof(ui_imgset_910091477) / (sizeof(lv_image_dsc_t *));
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1800);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_frame);
    lv_anim_set_values(&PropertyAnimation_0, 1, 15);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen__StartupSplash(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        SplashVideo_Animation(ui_Image__StartupSplash__LogoVideo, 0);
    }
}

void ui_event_Input__Initial_Setup__Input_Textarea__Initial_Setup__Input_Serial_Number(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Numpad_M__Initial_Setup__Numpad_M,  ui_comp_get_child(ui_Input__Initial_Setup__Input,
                                                                                         UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1));
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Numpad_M__Initial_Setup__Numpad_M, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Input__Initial_Setup__Input1_Textarea__Initial_Setup__Input1_Model_Number(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Numpad_M__Initial_Setup__Numpad_M,  ui_comp_get_child(ui_Input__Initial_Setup__Input1,
                                                                                         UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1));
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Numpad_M__Initial_Setup__Numpad_M, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Secondarybtn__Initial_Setup__Remote_Password_Button____Secondarybtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen__Generic_Password, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                          &ui_Screen__Generic_Password_screen_init);
    }
}

void ui_event_Secondarybtn__Initial_Setup__Select_Options_Button____Secondarybtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen__Select_Option, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen__Select_Option_screen_init);
    }
}

void ui_event_Primarybtn__Initial_Setup__Next_Button____Primarybtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen__Home, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen__Home_screen_init);
    }
}

void ui_event_Numpad_M__Initial_Setup__Numpad_M_Keyboard____Numpad_M(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Numpad_M__Initial_Setup__Numpad_M, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Primarybtn__Select_Option__OK_3_Button____Primarybtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen__Home, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen__Home_screen_init);
    }
}

void ui_event_Secondarybtn__Generic_Password__Secondarybtn3_Button____Secondarybtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen__Initial_Setup, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen__Initial_Setup_screen_init);
    }
}

void ui_event_Primarybtn__Generic_Password__OK_4_Button____Primarybtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen__Initial_Setup, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen__Initial_Setup_screen_init);
    }
}

void ui_event_Menu__Home__Menu_MenuButton____Menu_Button_Pump(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen__Pump_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen__Pump_Settings_screen_init);
    }
}

void ui_event_Menu__Home__Menu_MenuButton____Menu_Button_Setup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen__Advanced_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                          &ui_Screen__Advanced_Settings_screen_init);
    }
}

void ui_event_Input__Home__Input24_Textarea____TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Numpad_M__Home__Numpad_M2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Numpad_M__Home__Numpad_M2,  ui_comp_get_child(ui_Input__Home__Input24,
                                                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1));
    }
}

void ui_event_Input__Home__Input20_Textarea____TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Numpad_M__Home__Numpad_M2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Numpad_M__Home__Numpad_M2,  ui_comp_get_child(ui_Input__Home__Input20,
                                                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1));
    }
}

void ui_event_Input__Home__Input21_Textarea____TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Numpad_M__Home__Numpad_M2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Numpad_M__Home__Numpad_M2,  ui_comp_get_child(ui_Input__Home__Input21,
                                                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1));
    }
}

void ui_event_Input__Home__Input22_Textarea____TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Numpad_M__Home__Numpad_M2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Numpad_M__Home__Numpad_M2,  ui_comp_get_child(ui_Input__Home__Input22,
                                                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1));
    }
}

void ui_event_Numpad_M__Home__Numpad_M2_Keyboard____Numpad_M(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Numpad_M__Home__Numpad_M2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Menu__Pump_Settings__Menu2_MenuButton____Menu_Button_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen__Home, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen__Home_screen_init);
    }
}

void ui_event_Menu__Pump_Settings__Menu2_MenuButton____Menu_Button_Setup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen__Advanced_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                          &ui_Screen__Advanced_Settings_screen_init);
    }
}

void ui_event_Menu__Advanced_Settings__Menu3_MenuButton____Menu_Button_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen__Home, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen__Home_screen_init);
    }
}

void ui_event_Menu__Advanced_Settings__Menu3_MenuButton____Menu_Button_Pump(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen__Pump_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen__Pump_Settings_screen_init);
    }
}

void ui_event_Input__Advanced_Settings__Input6_Textarea__Advanced_Settings__Input6_TextAreaPAI1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_KeyboardL__Advanced_Settings__KeyboardL4,
                                ui_comp_get_child(ui_Input__Advanced_Settings__Input6, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1));
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_KeyboardL__Advanced_Settings__KeyboardL4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Input__Advanced_Settings__Input7_Textarea__Advanced_Settings__Input7_TextAreaPAI2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_KeyboardL__Advanced_Settings__KeyboardL4,
                                ui_comp_get_child(ui_Input__Advanced_Settings__Input7, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1));
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_KeyboardL__Advanced_Settings__KeyboardL4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Secondarybtn__Advanced_Settings__Select_Options3_Button____Secondarybtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen__Firmware_Update, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen__Firmware_Update_screen_init);
    }
}

void ui_event_Secondarybtn__Advanced_Settings__Select_Options4_Button____Secondarybtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen__Maintenance, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen__Maintenance_screen_init);
    }
}

void ui_event_Secondarybtn__Advanced_Settings__Select_Options5_Button____Secondarybtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen__Communications, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen__Communications_screen_init);
    }
}

void ui_event_Secondarybtn__Advanced_Settings__Select_Options6_Button____Secondarybtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen__Initial_Setup, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen__Initial_Setup_screen_init);
    }
}

void ui_event_Secondarybtn__Advanced_Settings__Select_Options7_Button____Secondarybtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen__Self_Test, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen__Self_Test_screen_init);
    }
}

void ui_event_KeyboardL__Advanced_Settings__KeyboardL4_Keyboard____KeyboardL(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_KeyboardL__Advanced_Settings__KeyboardL4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Header__Firmware_Update__Header5_Button____Back_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen__Advanced_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                          &ui_Screen__Advanced_Settings_screen_init);
    }
}

void ui_event_Header__Maintenance__Header6_Button____Back_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen__Advanced_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                          &ui_Screen__Advanced_Settings_screen_init);
    }
}

void ui_event_Input__Maintenance__Input9_Textarea__Maintenance__Input9_TextAreaSN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardL__Maintenance__KeyboardMainL5,  ui_comp_get_child(ui_Input__Maintenance__Input9,
                                                                                              UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1));
        _ui_flag_modify(ui_KeyboardL__Maintenance__KeyboardMainL5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Input__Maintenance__Input10_Textarea__Maintenance__Input10_TextAreaMN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardL__Maintenance__KeyboardMainL5,  ui_comp_get_child(ui_Input__Maintenance__Input10,
                                                                                              UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1));
        _ui_flag_modify(ui_KeyboardL__Maintenance__KeyboardMainL5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Input__Maintenance__Input11_Textarea__Maintenance__Input11_TextAreaFW(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardL__Maintenance__KeyboardMainL5,  ui_comp_get_child(ui_Input__Maintenance__Input11,
                                                                                              UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1));
        _ui_flag_modify(ui_KeyboardL__Maintenance__KeyboardMainL5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Input__Maintenance__Input12_Textarea__Maintenance__Input12_TextAreaGUI(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardL__Maintenance__KeyboardMainL5,  ui_comp_get_child(ui_Input__Maintenance__Input12,
                                                                                              UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1));
        _ui_flag_modify(ui_KeyboardL__Maintenance__KeyboardMainL5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Input__Maintenance__Input13_Textarea__Maintenance__Input13_TextAreaTR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardL__Maintenance__KeyboardMainL5,  ui_comp_get_child(ui_Input__Maintenance__Input13,
                                                                                              UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1));
        _ui_flag_modify(ui_KeyboardL__Maintenance__KeyboardMainL5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Input__Maintenance__Input8_Textarea__Maintenance__Input8_TextArea_Reminder(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardL__Maintenance__KeyboardMainL5,  ui_comp_get_child(ui_Input__Maintenance__Input8,
                                                                                              UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1));
        _ui_flag_modify(ui_KeyboardL__Maintenance__KeyboardMainL1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_KeyboardL__Maintenance__KeyboardMainL1_Keyboard____KeyboardL(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_KeyboardL__Maintenance__KeyboardMainL1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_KeyboardL__Maintenance__KeyboardMainL5_Keyboard____KeyboardL(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_KeyboardL__Maintenance__KeyboardMainL5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Header__Self_Test__Header7_Button____Back_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen__Advanced_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                          &ui_Screen__Advanced_Settings_screen_init);
    }
}

void ui_event_Screen__Communications(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        tablogic(e);
    }
}

void ui_event_Header__Communications__Header8_Button____Back_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen__Advanced_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                          &ui_Screen__Advanced_Settings_screen_init);
    }
}

void ui_event_Input__Communications__Input14_Textarea__Communications__Input14_TextAreaIP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Numpad_M__Communications__Numpad_M1,  ui_comp_get_child(ui_Input__Communications__Input14,
                                                                                           UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1));
    }
}

void ui_event_Input__Communications__Input15_Textarea__Communications__Input15_TextAreaSUB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Numpad_M__Communications__Numpad_M1,  ui_comp_get_child(ui_Input__Communications__Input15,
                                                                                           UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1));
    }
}

void ui_event_Input__Communications__Input16_Textarea__Communications__Input16_TextAreaGate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Numpad_M__Communications__Numpad_M1,  ui_comp_get_child(ui_Input__Communications__Input16,
                                                                                           UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1));
    }
}

void ui_event_Input__Communications__Input17_Textarea__Communications__Input17_TextAreaDNS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Numpad_M__Communications__Numpad_M1,  ui_comp_get_child(ui_Input__Communications__Input17,
                                                                                           UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1));
    }
}

void ui_event_Input__Communications__Input19_Textarea__Communications__Input19_TextAreaSSID(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardL__Communications__KeyboardWifi,
                                ui_comp_get_child(ui_Input__Communications__Input19, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1));
        _ui_flag_modify(ui_KeyboardL__Communications__KeyboardWifi, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Input__Communications__Input18_Textarea__Communications__Input18_TextAreaPAss(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardL__Communications__KeyboardWifi,
                                ui_comp_get_child(ui_Input__Communications__Input18, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1));
        _ui_flag_modify(ui_KeyboardL__Communications__KeyboardWifi, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_KeyboardL__Communications__KeyboardWifi_Keyboard____KeyboardL(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_KeyboardL__Communications__KeyboardWifi, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_simple_init(dispp);
    lv_disp_set_theme(dispp, theme);
    ui_Screen__StartupSplash_screen_init();
    ui_Screen__Initial_Setup_screen_init();
    ui_Screen__Select_Option_screen_init();
    ui_Screen__Generic_Password_screen_init();
    ui_Screen__Home_screen_init();
    ui_Screen__Pump_Settings_screen_init();
    ui_Screen__Advanced_Settings_screen_init();
    ui_Screen__Firmware_Update_screen_init();
    ui_Screen__Maintenance_screen_init();
    ui_Screen__Self_Test_screen_init();
    ui_Screen__Communications_screen_init();
    ui_Screen__Popup_Modal_screen_init();
    LV_LOG_WARN("End Load Screens");
    ui_Startevents_______initial_actions0 = lv_obj_create(NULL);
    LV_LOG_WARN("Started Events");   
    lv_disp_load_scr(ui_Screen__StartupSplash);
    LV_LOG_WARN("Splash Screen Loaded");
}
