// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_Dark_blue[1] = {0x0A245C};
const ui_theme_variable_t _ui_theme_alpha_Dark_blue[1] = {255};

const ui_theme_variable_t _ui_theme_color_Blue[1] = {0x285CCC};
const ui_theme_variable_t _ui_theme_alpha_Blue[1] = {255};

const ui_theme_variable_t _ui_theme_color_Purple[1] = {0x6C2264};
const ui_theme_variable_t _ui_theme_alpha_Purple[1] = {255};

const ui_theme_variable_t _ui_theme_color_Orange[1] = {0xFF9902};
const ui_theme_variable_t _ui_theme_alpha_Orange[1] = {255};

const ui_theme_variable_t _ui_theme_color_Green[1] = {0x8FC93A};
const ui_theme_variable_t _ui_theme_alpha_Green[1] = {255};

const ui_theme_variable_t _ui_theme_color_Interface[1] = {0xF3F5F5};
const ui_theme_variable_t _ui_theme_alpha_Interface[1] = {255};

const ui_theme_variable_t _ui_theme_color_White[1] = {0xFFFFFF};
const ui_theme_variable_t _ui_theme_alpha_White[1] = {255};

const ui_theme_variable_t _ui_theme_color_Bg_[1] = {0xF5F5F5};
const ui_theme_variable_t _ui_theme_alpha_Bg_[1] = {255};

const ui_theme_variable_t _ui_theme_color_Disabled[1] = {0xDFE2E2};
const ui_theme_variable_t _ui_theme_alpha_Disabled[1] = {255};

const ui_theme_variable_t _ui_theme_color_Disabled_font[1] = {0x999C9E};
const ui_theme_variable_t _ui_theme_alpha_Disabled_font[1] = {170};

const ui_theme_variable_t _ui_theme_color_Secondary_font[1] = {0x999C9E};
const ui_theme_variable_t _ui_theme_alpha_Secondary_font[1] = {255};

const ui_theme_variable_t _ui_theme_color_Border[1] = {0xDFE2E2};
const ui_theme_variable_t _ui_theme_alpha_Border[1] = {255};

const ui_theme_variable_t _ui_theme_color_Placeholder[1] = {0x0A245C};
const ui_theme_variable_t _ui_theme_alpha_Placeholder[1] = {55};

const ui_theme_variable_t _ui_theme_color_Shadow[1] = {0x000000};
const ui_theme_variable_t _ui_theme_alpha_Shadow[1] = {60};

const ui_theme_variable_t _ui_theme_color_BG_Purple[1] = {0x6C2264};
const ui_theme_variable_t _ui_theme_alpha_BG_Purple[1] = {10};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

