// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_DARK_BLUE 0
#define UI_THEME_COLOR_BLUE 1
#define UI_THEME_COLOR_PURPLE 2
#define UI_THEME_COLOR_ORANGE 3
#define UI_THEME_COLOR_GREEN 4
#define UI_THEME_COLOR_INTERFACE 5
#define UI_THEME_COLOR_WHITE 6
#define UI_THEME_COLOR_BG_ 7
#define UI_THEME_COLOR_DISABLED 8
#define UI_THEME_COLOR_DISABLED_FONT 9
#define UI_THEME_COLOR_SECONDARY_FONT 10
#define UI_THEME_COLOR_BORDER 11
#define UI_THEME_COLOR_PLACEHOLDER 12
#define UI_THEME_COLOR_SHADOW 13
#define UI_THEME_COLOR_BG_PURPLE 14

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_Dark_blue[1];
extern const ui_theme_variable_t _ui_theme_alpha_Dark_blue[1];

extern const ui_theme_variable_t _ui_theme_color_Blue[1];
extern const ui_theme_variable_t _ui_theme_alpha_Blue[1];

extern const ui_theme_variable_t _ui_theme_color_Purple[1];
extern const ui_theme_variable_t _ui_theme_alpha_Purple[1];

extern const ui_theme_variable_t _ui_theme_color_Orange[1];
extern const ui_theme_variable_t _ui_theme_alpha_Orange[1];

extern const ui_theme_variable_t _ui_theme_color_Green[1];
extern const ui_theme_variable_t _ui_theme_alpha_Green[1];

extern const ui_theme_variable_t _ui_theme_color_Interface[1];
extern const ui_theme_variable_t _ui_theme_alpha_Interface[1];

extern const ui_theme_variable_t _ui_theme_color_White[1];
extern const ui_theme_variable_t _ui_theme_alpha_White[1];

extern const ui_theme_variable_t _ui_theme_color_Bg_[1];
extern const ui_theme_variable_t _ui_theme_alpha_Bg_[1];

extern const ui_theme_variable_t _ui_theme_color_Disabled[1];
extern const ui_theme_variable_t _ui_theme_alpha_Disabled[1];

extern const ui_theme_variable_t _ui_theme_color_Disabled_font[1];
extern const ui_theme_variable_t _ui_theme_alpha_Disabled_font[1];

extern const ui_theme_variable_t _ui_theme_color_Secondary_font[1];
extern const ui_theme_variable_t _ui_theme_alpha_Secondary_font[1];

extern const ui_theme_variable_t _ui_theme_color_Border[1];
extern const ui_theme_variable_t _ui_theme_alpha_Border[1];

extern const ui_theme_variable_t _ui_theme_color_Placeholder[1];
extern const ui_theme_variable_t _ui_theme_alpha_Placeholder[1];

extern const ui_theme_variable_t _ui_theme_color_Shadow[1];
extern const ui_theme_variable_t _ui_theme_alpha_Shadow[1];

extern const ui_theme_variable_t _ui_theme_color_BG_Purple[1];
extern const ui_theme_variable_t _ui_theme_alpha_BG_Purple[1];

extern const uint32_t * ui_theme_colors[1];
extern const uint8_t * ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
