// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "../ui.h"

void ui_Screen__Firmware_Update_screen_init(void)
{
    ui_Screen__Firmware_Update = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen__Firmware_Update, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Screen__Firmware_Update, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screen__Firmware_Update, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    ui_object_set_themeable_style_property(ui_Screen__Firmware_Update, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Bg_);
    ui_object_set_themeable_style_property(ui_Screen__Firmware_Update, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Bg_);
    lv_obj_set_style_pad_left(ui_Screen__Firmware_Update, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Screen__Firmware_Update, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Screen__Firmware_Update, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Screen__Firmware_Update, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Screen__Firmware_Update, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Screen__Firmware_Update, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Firmware_Update__Container63 = lv_obj_create(ui_Screen__Firmware_Update);
    lv_obj_remove_style_all(ui_Container__Firmware_Update__Container63);
    lv_obj_set_height(ui_Container__Firmware_Update__Container63, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Firmware_Update__Container63, 1);
    lv_obj_set_align(ui_Container__Firmware_Update__Container63, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Firmware_Update__Container63, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Firmware_Update__Container63, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Firmware_Update__Container63,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container__Firmware_Update__Container63, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Container__Firmware_Update__Container63, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Firmware_Update__Container63, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Firmware_Update__Container63, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Header__Firmware_Update__Header5 = ui_Container____Header_create(ui_Container__Firmware_Update__Container63);
    lv_obj_set_x(ui_Header__Firmware_Update__Header5, 0);
    lv_obj_set_y(ui_Header__Firmware_Update__Header5, 0);

    lv_obj_remove_flag(ui_comp_get_child(ui_Header__Firmware_Update__Header5,
                                         UI_COMP_CONTAINER____HEADER_BUTTON____BACK_BUTTON), LV_OBJ_FLAG_HIDDEN);     /// Flags


    lv_label_set_text(ui_comp_get_child(ui_Header__Firmware_Update__Header5, UI_COMP_CONTAINER____HEADER_LABEL____TITLE),
                      "Firmware Update");



    lv_obj_add_flag(ui_comp_get_child(ui_Header__Firmware_Update__Header5,
                                      UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____USB), LV_OBJ_FLAG_HIDDEN);    /// Flags

    lv_obj_add_flag(ui_comp_get_child(ui_Header__Firmware_Update__Header5,
                                      UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____ETHERNET), LV_OBJ_FLAG_HIDDEN);    /// Flags

    lv_obj_add_flag(ui_comp_get_child(ui_Header__Firmware_Update__Header5,
                                      UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____WIFI), LV_OBJ_FLAG_HIDDEN);    /// Flags

    ui_Container__Firmware_Update__Content8 = lv_obj_create(ui_Container__Firmware_Update__Container63);
    lv_obj_remove_style_all(ui_Container__Firmware_Update__Content8);
    lv_obj_set_width(ui_Container__Firmware_Update__Content8, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Firmware_Update__Content8, 1);
    lv_obj_set_align(ui_Container__Firmware_Update__Content8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Firmware_Update__Content8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Firmware_Update__Content8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Firmware_Update__Content8,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container__Firmware_Update__Content8, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Container__Firmware_Update__Content8, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_Container__Firmware_Update__Content8, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_Container__Firmware_Update__Content8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Container__Firmware_Update__Content8, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Firmware_Update__Content8, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Firmware_Update__Content8, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Firmware_Update__Content8, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Firmware_Update__Content8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Firmware_Update__Content8, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Firmware_Update__fw_contents = lv_obj_create(ui_Container__Firmware_Update__Content8);
    lv_obj_remove_style_all(ui_Container__Firmware_Update__fw_contents);
    lv_obj_set_width(ui_Container__Firmware_Update__fw_contents, lv_pct(100));
    lv_obj_set_height(ui_Container__Firmware_Update__fw_contents, lv_pct(100));
    lv_obj_set_align(ui_Container__Firmware_Update__fw_contents, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Firmware_Update__fw_contents,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container__Firmware_Update__fw_contents, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Firmware_Update__fw_contents, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Firmware_Update__Update_Buttons = lv_obj_create(ui_Container__Firmware_Update__fw_contents);
    lv_obj_remove_style_all(ui_Container__Firmware_Update__Update_Buttons);
    lv_obj_set_width(ui_Container__Firmware_Update__Update_Buttons, lv_pct(100));
    lv_obj_set_height(ui_Container__Firmware_Update__Update_Buttons, lv_pct(100));
    lv_obj_set_align(ui_Container__Firmware_Update__Update_Buttons, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Firmware_Update__Update_Buttons, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Firmware_Update__Update_Buttons, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Firmware_Update__Update_Buttons,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container__Firmware_Update__Update_Buttons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Firmware_Update__Update_Buttons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Firmware_Update__Update_Buttons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Firmware_Update__Update_Buttons, 28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Firmware_Update__Container73 = lv_obj_create(ui_Container__Firmware_Update__Update_Buttons);
    lv_obj_remove_style_all(ui_Container__Firmware_Update__Container73);
    lv_obj_set_height(ui_Container__Firmware_Update__Container73, 120);
    lv_obj_set_width(ui_Container__Firmware_Update__Container73, lv_pct(100));
    lv_obj_set_x(ui_Container__Firmware_Update__Container73, -1);
    lv_obj_set_y(ui_Container__Firmware_Update__Container73, -12);
    lv_obj_set_align(ui_Container__Firmware_Update__Container73, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Firmware_Update__Container73, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Firmware_Update__Container73, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Firmware_Update__Container73,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container__Firmware_Update__Container73, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Firmware_Update__Container73, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Firmware_Update__Container73, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Firmware_Update__Container73, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Firmware_Update__Container74 = lv_obj_create(ui_Container__Firmware_Update__Container73);
    lv_obj_remove_style_all(ui_Container__Firmware_Update__Container74);
    lv_obj_set_width(ui_Container__Firmware_Update__Container74, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Container__Firmware_Update__Container74, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Container__Firmware_Update__Container74, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Firmware_Update__Container74,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container__Firmware_Update__Container75 = lv_obj_create(ui_Container__Firmware_Update__Container73);
    lv_obj_remove_style_all(ui_Container__Firmware_Update__Container75);
    lv_obj_set_height(ui_Container__Firmware_Update__Container75, lv_pct(81));
    lv_obj_set_flex_grow(ui_Container__Firmware_Update__Container75, 1);
    lv_obj_set_align(ui_Container__Firmware_Update__Container75, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Firmware_Update__Container75, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Firmware_Update__Container75, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Firmware_Update__Container75,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container__Firmware_Update__Container75, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Firmware_Update__Container75, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Firmware_Update__Container75, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Firmware_Update__Container75, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Firmware_Update__Container75, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Firmware_Update__Container75, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label__Firmware_Update__Label39 = lv_label_create(ui_Container__Firmware_Update__Container75);
    lv_obj_set_width(ui_Label__Firmware_Update__Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Firmware_Update__Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label__Firmware_Update__Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label__Firmware_Update__Label39, "Current Version: XXXXX");
    ui_object_set_themeable_style_property(ui_Label__Firmware_Update__Label39, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Label__Firmware_Update__Label39, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(ui_Label__Firmware_Update__Label39, &ui_font_P1_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label__Firmware_Update__Label40 = lv_label_create(ui_Container__Firmware_Update__Container75);
    lv_obj_set_width(ui_Label__Firmware_Update__Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Firmware_Update__Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label__Firmware_Update__Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label__Firmware_Update__Label40, "Where would you like to update from?");
    ui_object_set_themeable_style_property(ui_Label__Firmware_Update__Label40, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Label__Firmware_Update__Label40, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(ui_Label__Firmware_Update__Label40, &ui_font_P2_SBold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Firmware_Update__Container64 = lv_obj_create(ui_Container__Firmware_Update__Update_Buttons);
    lv_obj_remove_style_all(ui_Container__Firmware_Update__Container64);
    lv_obj_set_height(ui_Container__Firmware_Update__Container64, 120);
    lv_obj_set_width(ui_Container__Firmware_Update__Container64, lv_pct(100));
    lv_obj_set_x(ui_Container__Firmware_Update__Container64, -1);
    lv_obj_set_y(ui_Container__Firmware_Update__Container64, -12);
    lv_obj_set_align(ui_Container__Firmware_Update__Container64, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Firmware_Update__Container64, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Firmware_Update__Container64, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Firmware_Update__Container64,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container__Firmware_Update__Container64, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Firmware_Update__Container64, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Firmware_Update__Container64, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Firmware_Update__Container64, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Firmware_Update__Container64, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Firmware_Update__Container64, 28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Primarybtn__Firmware_Update__Next5 = ui_Button____Primarybtn_create(ui_Container__Firmware_Update__Container64);
    lv_obj_set_height(ui_Primarybtn__Firmware_Update__Next5, 74);
    lv_obj_set_flex_grow(ui_Primarybtn__Firmware_Update__Next5, 1);
    lv_obj_set_x(ui_Primarybtn__Firmware_Update__Next5, 0);
    lv_obj_set_y(ui_Primarybtn__Firmware_Update__Next5, 0);
    lv_obj_set_align(ui_Primarybtn__Firmware_Update__Next5, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_pad_left(ui_Primarybtn__Firmware_Update__Next5, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Primarybtn__Firmware_Update__Next5, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Primarybtn__Firmware_Update__Next5, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Primarybtn__Firmware_Update__Next5, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_label_set_text(ui_comp_get_child(ui_Primarybtn__Firmware_Update__Next5, UI_COMP_BUTTON____PRIMARYBTN_LABEL____LABEL),
                      "Web");

    ui_Primarybtn__Firmware_Update__Next3 = ui_Button____Primarybtn_create(ui_Container__Firmware_Update__Container64);
    lv_obj_set_height(ui_Primarybtn__Firmware_Update__Next3, 74);
    lv_obj_set_flex_grow(ui_Primarybtn__Firmware_Update__Next3, 1);
    lv_obj_set_x(ui_Primarybtn__Firmware_Update__Next3, 0);
    lv_obj_set_y(ui_Primarybtn__Firmware_Update__Next3, 0);
    lv_obj_set_align(ui_Primarybtn__Firmware_Update__Next3, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_pad_left(ui_Primarybtn__Firmware_Update__Next3, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Primarybtn__Firmware_Update__Next3, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Primarybtn__Firmware_Update__Next3, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Primarybtn__Firmware_Update__Next3, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_label_set_text(ui_comp_get_child(ui_Primarybtn__Firmware_Update__Next3, UI_COMP_BUTTON____PRIMARYBTN_LABEL____LABEL),
                      "Flash Drive");

    ui_Container__Firmware_Update__Update_Bar = lv_obj_create(ui_Container__Firmware_Update__fw_contents);
    lv_obj_remove_style_all(ui_Container__Firmware_Update__Update_Bar);
    lv_obj_set_width(ui_Container__Firmware_Update__Update_Bar, lv_pct(100));
    lv_obj_set_height(ui_Container__Firmware_Update__Update_Bar, lv_pct(100));
    lv_obj_set_align(ui_Container__Firmware_Update__Update_Bar, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Firmware_Update__Update_Bar, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Firmware_Update__Update_Bar, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Container__Firmware_Update__Update_Bar, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Container__Firmware_Update__Update_Bar,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container__Firmware_Update__Update_Bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Firmware_Update__Update_Bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Firmware_Update__Update_Bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Firmware_Update__Update_Bar, 28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Firmware_Update__Container69 = lv_obj_create(ui_Container__Firmware_Update__Update_Bar);
    lv_obj_remove_style_all(ui_Container__Firmware_Update__Container69);
    lv_obj_set_width(ui_Container__Firmware_Update__Container69, lv_pct(100));
    lv_obj_set_height(ui_Container__Firmware_Update__Container69, lv_pct(100));
    lv_obj_set_align(ui_Container__Firmware_Update__Container69, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Firmware_Update__Container69, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Firmware_Update__Container69, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Firmware_Update__Container69,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container__Firmware_Update__Container69, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Firmware_Update__Container69, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Firmware_Update__Container69, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Firmware_Update__Container69, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Firmware_Update__Container69, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Firmware_Update__Container69, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label__Firmware_Update__Label29 = lv_label_create(ui_Container__Firmware_Update__Container69);
    lv_obj_set_width(ui_Label__Firmware_Update__Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Firmware_Update__Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label__Firmware_Update__Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label__Firmware_Update__Label29, "Installing new version from web...");
    ui_object_set_themeable_style_property(ui_Label__Firmware_Update__Label29, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Label__Firmware_Update__Label29, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(ui_Label__Firmware_Update__Label29, &ui_font_P2_SBold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar__Firmware_Update__Bar1 = lv_bar_create(ui_Container__Firmware_Update__Container69);
    lv_bar_set_value(ui_Bar__Firmware_Update__Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar__Firmware_Update__Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_Bar__Firmware_Update__Bar1, 28);
    lv_obj_set_width(ui_Bar__Firmware_Update__Bar1, lv_pct(100));
    lv_obj_set_align(ui_Bar__Firmware_Update__Bar1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Bar__Firmware_Update__Bar1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar__Firmware_Update__Bar1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar__Firmware_Update__Bar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Bar__Firmware_Update__Bar1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Bar__Firmware_Update__Bar1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Bar__Firmware_Update__Bar1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Bar__Firmware_Update__Bar1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar__Firmware_Update__Bar1, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Bar__Firmware_Update__Bar1, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Bar__Firmware_Update__Bar1, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Dark_blue);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar__Firmware_Update__Bar1,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar__Firmware_Update__Bar1,
                                                                                  lv_obj_get_style_pad_right(ui_Bar__Firmware_Update__Bar1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Container__Firmware_Update__Footer4 = lv_obj_create(ui_Container__Firmware_Update__Container63);
    lv_obj_remove_style_all(ui_Container__Firmware_Update__Footer4);
    lv_obj_set_height(ui_Container__Firmware_Update__Footer4, 34);
    lv_obj_set_width(ui_Container__Firmware_Update__Footer4, lv_pct(100));
    lv_obj_set_align(ui_Container__Firmware_Update__Footer4, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Container__Firmware_Update__Footer4, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_remove_flag(ui_Container__Firmware_Update__Footer4,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Container__Firmware_Update__Footer4, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Container__Firmware_Update__Footer4, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Dark_blue);

    ui_Label__Firmware_Update__Label41 = lv_label_create(ui_Container__Firmware_Update__Footer4);
    lv_obj_set_width(ui_Label__Firmware_Update__Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Firmware_Update__Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label__Firmware_Update__Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label__Firmware_Update__Label41, "Visit eldex.com/support for manuals and help");
    ui_object_set_themeable_style_property(ui_Label__Firmware_Update__Label41, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Interface);
    ui_object_set_themeable_style_property(ui_Label__Firmware_Update__Label41, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Interface);
    lv_obj_set_style_text_font(ui_Label__Firmware_Update__Label41, &ui_font_P3_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_comp_get_child(ui_Header__Firmware_Update__Header5,
                                          UI_COMP_CONTAINER____HEADER_BUTTON____BACK_BUTTON), ui_event_Header__Firmware_Update__Header5_Button____Back_Button,
                        LV_EVENT_ALL, NULL);
    ui_Button__Firmware_Update__Back = ui_comp_get_child(ui_Header__Firmware_Update__Header5,
                                                         UI_COMP_CONTAINER____HEADER_BUTTON____BACK_BUTTON);
    ui_Image__Firmware_Update__USB_Status = ui_comp_get_child(ui_Header__Firmware_Update__Header5,
                                                              UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____USB);
    ui_Image__Firmware_Update__Ethernet_Status = ui_comp_get_child(ui_Header__Firmware_Update__Header5,
                                                                   UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____ETHERNET);
    ui_Image__Firmware_Update__WiFi_Status = ui_comp_get_child(ui_Header__Firmware_Update__Header5,
                                                               UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____WIFI);
    ui_Container__Firmware_Update__Start = ui_Container__Firmware_Update__Update_Buttons;
    ui_Container__Firmware_Update__StartQuestion = ui_Container__Firmware_Update__Container73;
    ui_Label__Firmware_Update__CurrentVersion = ui_Label__Firmware_Update__Label39;
    ui_Container__Firmware_Update__UpdateButtons = ui_Container__Firmware_Update__Container64;
    ui_Button__Firmware_Update__UpdateFromWeb = ui_Primarybtn__Firmware_Update__Next5;
    ui_Button__Firmware_Update__UpdateFromFlashdrive = ui_Primarybtn__Firmware_Update__Next3;
    ui_Container__Firmware_Update__UpdateProgress = ui_Container__Firmware_Update__Update_Bar;
    ui_Label__Firmware_Update__InstallationProgress = ui_Label__Firmware_Update__Label29;
    ui_Bar__Firmware_Update__InstallationProgress = ui_Bar__Firmware_Update__Bar1;
    ui_Label__Firmware_Update__StatusFooter = ui_Label__Firmware_Update__Label41;

}
