// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "../ui.h"

void ui_Screen__Generic_Password_screen_init(void)
{
    ui_Screen__Generic_Password = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen__Generic_Password, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Screen__Generic_Password, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Screen__Generic_Password, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    ui_object_set_themeable_style_property(ui_Screen__Generic_Password, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Bg_);
    ui_object_set_themeable_style_property(ui_Screen__Generic_Password, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Bg_);
    lv_obj_set_style_pad_left(ui_Screen__Generic_Password, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Screen__Generic_Password, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Screen__Generic_Password, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Screen__Generic_Password, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Screen__Generic_Password, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Screen__Generic_Password, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Header__Generic_Password__Header2 = ui_Container____Header_create(ui_Screen__Generic_Password);
    lv_obj_set_x(ui_Header__Generic_Password__Header2, 0);
    lv_obj_set_y(ui_Header__Generic_Password__Header2, 0);



    lv_label_set_text(ui_comp_get_child(ui_Header__Generic_Password__Header2, UI_COMP_CONTAINER____HEADER_LABEL____TITLE),
                      "Change Remote Password");



    lv_obj_add_flag(ui_comp_get_child(ui_Header__Generic_Password__Header2,
                                      UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____USB), LV_OBJ_FLAG_HIDDEN);    /// Flags

    lv_obj_add_flag(ui_comp_get_child(ui_Header__Generic_Password__Header2,
                                      UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____ETHERNET), LV_OBJ_FLAG_HIDDEN);    /// Flags

    lv_obj_add_flag(ui_comp_get_child(ui_Header__Generic_Password__Header2,
                                      UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____WIFI), LV_OBJ_FLAG_HIDDEN);    /// Flags

    ui_Image__Generic_Password__Image12 = lv_image_create(ui_comp_get_child(ui_Header__Generic_Password__Header2,
                                                                            UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS));
    lv_image_set_src(ui_Image__Generic_Password__Image12, ui_img_logo_png);
    lv_obj_set_width(ui_Image__Generic_Password__Image12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image__Generic_Password__Image12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image__Generic_Password__Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image__Generic_Password__Image12, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image__Generic_Password__Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container__Generic_Password__Content3 = lv_obj_create(ui_Screen__Generic_Password);
    lv_obj_remove_style_all(ui_Container__Generic_Password__Content3);
    lv_obj_set_width(ui_Container__Generic_Password__Content3, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Generic_Password__Content3, 1);
    lv_obj_set_align(ui_Container__Generic_Password__Content3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Generic_Password__Content3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Generic_Password__Content3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Generic_Password__Content3,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container__Generic_Password__Content3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Container__Generic_Password__Content3, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_Container__Generic_Password__Content3, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_Container__Generic_Password__Content3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Container__Generic_Password__Content3, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Generic_Password__Content3, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Generic_Password__Content3, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Generic_Password__Content3, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Generic_Password__Content3, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Generic_Password__Content3, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel__Generic_Password__Panel1 = lv_obj_create(ui_Container__Generic_Password__Content3);
    lv_obj_set_width(ui_Panel__Generic_Password__Panel1, lv_pct(100));
    lv_obj_set_height(ui_Panel__Generic_Password__Panel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Panel__Generic_Password__Panel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel__Generic_Password__Panel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel__Generic_Password__Panel1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_END,
                          LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_Panel__Generic_Password__Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel__Generic_Password__Panel1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Panel__Generic_Password__Panel1, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_White);
    ui_object_set_themeable_style_property(ui_Panel__Generic_Password__Panel1, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_White);
    lv_obj_set_style_pad_left(ui_Panel__Generic_Password__Panel1, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel__Generic_Password__Panel1, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel__Generic_Password__Panel1, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel__Generic_Password__Panel1, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel__Generic_Password__Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel__Generic_Password__Panel1, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Input__Generic_Password__Remote_PIN4 = ui_Container____Input_create(ui_Panel__Generic_Password__Panel1);
    lv_obj_set_height(ui_Input__Generic_Password__Remote_PIN4, 86);
    lv_obj_set_flex_grow(ui_Input__Generic_Password__Remote_PIN4, 1);
    lv_obj_set_x(ui_Input__Generic_Password__Remote_PIN4, 0);
    lv_obj_set_y(ui_Input__Generic_Password__Remote_PIN4, 0);



    lv_label_set_text(ui_comp_get_child(ui_Input__Generic_Password__Remote_PIN4,
                                        UI_COMP_CONTAINER____INPUT_CONTAINER____LABEL_PADDING_LABEL____LABEL), "Enter New Remote PIN");

    lv_textarea_set_placeholder_text(ui_comp_get_child(ui_Input__Generic_Password__Remote_PIN4,
                                                       UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), "****");
    lv_textarea_set_password_mode(ui_comp_get_child(ui_Input__Generic_Password__Remote_PIN4,
                                                    UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), true);



    ui_Secondarybtn__Generic_Password__Secondarybtn3 = ui_Button____Secondarybtn_create(ui_Panel__Generic_Password__Panel1);
    lv_obj_set_width(ui_Secondarybtn__Generic_Password__Secondarybtn3, 134);
    lv_obj_set_height(ui_Secondarybtn__Generic_Password__Secondarybtn3, 68);
    lv_obj_set_x(ui_Secondarybtn__Generic_Password__Secondarybtn3, 271);
    lv_obj_set_y(ui_Secondarybtn__Generic_Password__Secondarybtn3, -16);
    lv_obj_set_style_min_height(ui_Secondarybtn__Generic_Password__Secondarybtn3, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_height(ui_Secondarybtn__Generic_Password__Secondarybtn3, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_label_set_text(ui_comp_get_child(ui_Secondarybtn__Generic_Password__Secondarybtn3,
                                        UI_COMP_BUTTON____SECONDARYBTN_LABEL____LABEL), "Cancel");

    ui_Primarybtn__Generic_Password__OK_4 = ui_Button____Primarybtn_create(ui_Panel__Generic_Password__Panel1);
    lv_obj_set_width(ui_Primarybtn__Generic_Password__OK_4, 199);
    lv_obj_set_height(ui_Primarybtn__Generic_Password__OK_4, 70);
    lv_obj_set_x(ui_Primarybtn__Generic_Password__OK_4, 0);
    lv_obj_set_y(ui_Primarybtn__Generic_Password__OK_4, 0);

    lv_label_set_text(ui_comp_get_child(ui_Primarybtn__Generic_Password__OK_4, UI_COMP_BUTTON____PRIMARYBTN_LABEL____LABEL),
                      "OK");

    ui_KeyboardL__Generic_Password__KeyboardL2 = ui_Keyboard____KeyboardL_create(ui_Container__Generic_Password__Content3);
    lv_obj_set_width(ui_KeyboardL__Generic_Password__KeyboardL2, lv_pct(100));
    lv_obj_set_flex_grow(ui_KeyboardL__Generic_Password__KeyboardL2, 1);
    lv_obj_set_x(ui_KeyboardL__Generic_Password__KeyboardL2, 0);
    lv_obj_set_y(ui_KeyboardL__Generic_Password__KeyboardL2, 0);

    lv_obj_add_event_cb(ui_Secondarybtn__Generic_Password__Secondarybtn3,
                        ui_event_Secondarybtn__Generic_Password__Secondarybtn3_Button____Secondarybtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Primarybtn__Generic_Password__OK_4,
                        ui_event_Primarybtn__Generic_Password__OK_4_Button____Primarybtn, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardL__Generic_Password__KeyboardL2,
                             ui_comp_get_child(ui_Input__Generic_Password__Remote_PIN4, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1));
    ui_Label__Generic_Password__ScreenTitle = ui_comp_get_child(ui_Header__Generic_Password__Header2,
                                                                UI_COMP_CONTAINER____HEADER_LABEL____TITLE);
    ui_Image__Generic_Password__USB_Status = ui_comp_get_child(ui_Header__Generic_Password__Header2,
                                                               UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____USB);
    ui_Image__Generic_Password__Ethernet_Status = ui_comp_get_child(ui_Header__Generic_Password__Header2,
                                                                    UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____ETHERNET);
    ui_Image__Generic_Password__WiFi_Status = ui_comp_get_child(ui_Header__Generic_Password__Header2,
                                                                UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____WIFI);
    ui_Label__Generic_Password__PasswordField_Title = ui_comp_get_child(ui_Input__Generic_Password__Remote_PIN4,
                                                                        UI_COMP_CONTAINER____INPUT_CONTAINER____LABEL_PADDING_LABEL____LABEL);
    ui_Textarea__Generic_Password__PasswordField = ui_comp_get_child(ui_Input__Generic_Password__Remote_PIN4,
                                                                     UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1);
    ui_Button__Generic_Password__Cancel = ui_Secondarybtn__Generic_Password__Secondarybtn3;
    ui_Button__Generic_Password__OK = ui_Primarybtn__Generic_Password__OK_4;
    ui_Keyboard__Generic_Password__PasswordEntry = ui_KeyboardL__Generic_Password__KeyboardL2;

}
