// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "../ui.h"

void ui_Screen__Popup_Modal_screen_init(void)
{
    ui_Screen__Popup_Modal = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen__Popup_Modal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen__Popup_Modal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen__Popup_Modal, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Popup__Popup_Modal__Popup = ui_Panel____Popup_create(ui_Screen__Popup_Modal);
    lv_obj_set_x(ui_Popup__Popup_Modal__Popup, 0);
    lv_obj_set_y(ui_Popup__Popup_Modal__Popup, 0);









    ui_Panel__Popup_Modal__Full = ui_Popup__Popup_Modal__Popup;
    ui_Label__Popup_Modal__Title = ui_comp_get_child(ui_Popup__Popup_Modal__Popup,
                                                     UI_COMP_PANEL____POPUP_PANEL____CARD_LABEL____TITLE);
    ui_Label__Popup_Modal__Text = ui_comp_get_child(ui_Popup__Popup_Modal__Popup,
                                                    UI_COMP_PANEL____POPUP_PANEL____CARD_CONTAINER____CONTAINER11_LABEL____TEXT);
    ui_Button__Popup_Modal__Left = ui_comp_get_child(ui_Popup__Popup_Modal__Popup,
                                                     UI_COMP_PANEL____POPUP_SECONDARYBTN____CANCEL);
    ui_ButtonLabel__Popup_Modal__Left = ui_comp_get_child(ui_Popup__Popup_Modal__Popup,
                                                          UI_COMP_PANEL____POPUP_SECONDARYBTN____CANCEL_LABEL____CANCEL_LABEL);
    ui_Button__Popup_Modal__Right = ui_comp_get_child(ui_Popup__Popup_Modal__Popup,
                                                      UI_COMP_PANEL____POPUP_PRIMARYBTN____NEXT);
    ui_ButtonLabel__Popup_Modal__Right = ui_comp_get_child(ui_Popup__Popup_Modal__Popup,
                                                           UI_COMP_PANEL____POPUP_PRIMARYBTN____NEXT_LABEL____NEXT_LABEL);

}
