// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "../ui.h"

void ui_Screen__Home_screen_init(void)
{
    ui_Screen__Home = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen__Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Screen__Home, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screen__Home, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    ui_object_set_themeable_style_property(ui_Screen__Home, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Bg_);
    ui_object_set_themeable_style_property(ui_Screen__Home, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Bg_);
    lv_obj_set_style_pad_left(ui_Screen__Home, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Screen__Home, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Screen__Home, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Screen__Home, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Screen__Home, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Screen__Home, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Home__Container1 = lv_obj_create(ui_Screen__Home);
    lv_obj_remove_style_all(ui_Container__Home__Container1);
    lv_obj_set_width(ui_Container__Home__Container1, 100);
    lv_obj_set_height(ui_Container__Home__Container1, lv_pct(100));
    lv_obj_set_align(ui_Container__Home__Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Home__Container1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Home__Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Home__Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container__Home__Container1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Home__Container1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Home__Container1, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Home__Container1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Home__Container1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Home__Container1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image__Home__Logo1 = lv_image_create(ui_Container__Home__Container1);
    lv_image_set_src(ui_Image__Home__Logo1, ui_img_logo_png);
    lv_obj_set_width(ui_Image__Home__Logo1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image__Home__Logo1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image__Home__Logo1, 0);
    lv_obj_set_y(ui_Image__Home__Logo1, 6);
    lv_obj_set_align(ui_Image__Home__Logo1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image__Home__Logo1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image__Home__Logo1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Menu__Home__Menu = ui_Container____Menu_create(ui_Container__Home__Container1);
    lv_obj_set_x(ui_Menu__Home__Menu, 0);
    lv_obj_set_y(ui_Menu__Home__Menu, 0);

    lv_obj_add_state(ui_comp_get_child(ui_Menu__Home__Menu, UI_COMP_CONTAINER____MENU_MENUBUTTON____MENU_BUTTON_HOME),
                     LV_STATE_CHECKED);      /// States

    lv_obj_add_state(ui_comp_get_child(ui_Menu__Home__Menu,
                                       UI_COMP_CONTAINER____MENU_MENUBUTTON____MENU_BUTTON_HOME_IMAGE____MENU_BUTTON_HOME_ICON),
                     LV_STATE_CHECKED);      /// States





    ui_Container__Home__Container3 = lv_obj_create(ui_Screen__Home);
    lv_obj_remove_style_all(ui_Container__Home__Container3);
    lv_obj_set_height(ui_Container__Home__Container3, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Home__Container3, 1);
    lv_obj_set_align(ui_Container__Home__Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Home__Container3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Home__Container3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Home__Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container__Home__Container3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Container__Home__Container3, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Home__Container3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Home__Container3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Header__Home__Header = ui_Container____Header_create(ui_Container__Home__Container3);
    lv_obj_set_x(ui_Header__Home__Header, 0);
    lv_obj_set_y(ui_Header__Home__Header, 0);



    lv_label_set_text(ui_comp_get_child(ui_Header__Home__Header, UI_COMP_CONTAINER____HEADER_LABEL____TITLE),
                      "Pump Control");



    lv_obj_add_flag(ui_comp_get_child(ui_Header__Home__Header, UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____USB),
                    LV_OBJ_FLAG_HIDDEN);    /// Flags

    lv_obj_add_flag(ui_comp_get_child(ui_Header__Home__Header,
                                      UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____ETHERNET), LV_OBJ_FLAG_HIDDEN);    /// Flags

    lv_obj_add_flag(ui_comp_get_child(ui_Header__Home__Header,
                                      UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____WIFI), LV_OBJ_FLAG_HIDDEN);    /// Flags

    ui_Container__Home__Content4 = lv_obj_create(ui_Container__Home__Container3);
    lv_obj_remove_style_all(ui_Container__Home__Content4);
    lv_obj_set_width(ui_Container__Home__Content4, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Home__Content4, 1);
    lv_obj_set_align(ui_Container__Home__Content4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Home__Content4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Home__Content4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Home__Content4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container__Home__Content4, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Container__Home__Content4, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_Container__Home__Content4, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_Container__Home__Content4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Container__Home__Content4, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Home__Content4, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Home__Content4, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Home__Content4, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Home__Content4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Home__Content4, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Home__tab_Initial2 = lv_obj_create(ui_Container__Home__Content4);
    lv_obj_remove_style_all(ui_Container__Home__tab_Initial2);
    lv_obj_set_width(ui_Container__Home__tab_Initial2, lv_pct(100));
    lv_obj_set_height(ui_Container__Home__tab_Initial2, lv_pct(100));
    lv_obj_set_align(ui_Container__Home__tab_Initial2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Home__tab_Initial2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Home__tab_Initial2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Home__tab_Initial2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container__Home__tab_Initial2, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Home__tab_Initial2, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Home__Container9 = lv_obj_create(ui_Container__Home__tab_Initial2);
    lv_obj_remove_style_all(ui_Container__Home__Container9);
    lv_obj_set_width(ui_Container__Home__Container9, lv_pct(100));
    lv_obj_set_height(ui_Container__Home__Container9, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Container__Home__Container9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Home__Container9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Home__Container9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Home__Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container__Home__Container9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Home__Container9, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabButton__Home__TabButton7 = ui_Button____TabButton_create(ui_Container__Home__Container9);
    lv_obj_set_height(ui_TabButton__Home__TabButton7, 36);
    lv_obj_set_flex_grow(ui_TabButton__Home__TabButton7, 1);
    lv_obj_set_x(ui_TabButton__Home__TabButton7, 0);
    lv_obj_set_y(ui_TabButton__Home__TabButton7, 0);
    lv_obj_add_state(ui_TabButton__Home__TabButton7, LV_STATE_CHECKED);       /// States

    lv_label_set_text(ui_comp_get_child(ui_TabButton__Home__TabButton7, UI_COMP_BUTTON____TABBUTTON_LABEL____LABEL),
                      "Pump 1");

    ui_TabButton__Home__TabButton4 = ui_Button____TabButton_create(ui_Container__Home__Container9);
    lv_obj_set_height(ui_TabButton__Home__TabButton4, 36);
    lv_obj_set_flex_grow(ui_TabButton__Home__TabButton4, 1);
    lv_obj_set_x(ui_TabButton__Home__TabButton4, 0);
    lv_obj_set_y(ui_TabButton__Home__TabButton4, 0);
    lv_obj_remove_state(ui_TabButton__Home__TabButton4, LV_STATE_CHECKED);     /// States

    lv_label_set_text(ui_comp_get_child(ui_TabButton__Home__TabButton4, UI_COMP_BUTTON____TABBUTTON_LABEL____LABEL),
                      "Pump 2");

    ui_TabButton__Home__TabButton5 = ui_Button____TabButton_create(ui_Container__Home__Container9);
    lv_obj_set_height(ui_TabButton__Home__TabButton5, 36);
    lv_obj_set_flex_grow(ui_TabButton__Home__TabButton5, 1);
    lv_obj_set_x(ui_TabButton__Home__TabButton5, 0);
    lv_obj_set_y(ui_TabButton__Home__TabButton5, 0);
    lv_obj_remove_state(ui_TabButton__Home__TabButton5, LV_STATE_CHECKED);     /// States

    lv_label_set_text(ui_comp_get_child(ui_TabButton__Home__TabButton5, UI_COMP_BUTTON____TABBUTTON_LABEL____LABEL),
                      "Pump 3");

    ui_Container__Home__Container7 = lv_obj_create(ui_Container__Home__tab_Initial2);
    lv_obj_remove_style_all(ui_Container__Home__Container7);
    lv_obj_set_width(ui_Container__Home__Container7, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Home__Container7, 1);
    lv_obj_set_align(ui_Container__Home__Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Home__Container7, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Home__Container7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Home__Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container__Home__Container6 = lv_obj_create(ui_Container__Home__Container7);
    lv_obj_remove_style_all(ui_Container__Home__Container6);
    lv_obj_set_width(ui_Container__Home__Container6, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Home__Container6, 2);
    lv_obj_set_align(ui_Container__Home__Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Home__Container6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Home__Container6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Home__Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container__Home__Container6, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Container__Home__Container6, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_White);
    ui_object_set_themeable_style_property(ui_Container__Home__Container6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_White);

    ui_Container__Home__Container10 = lv_obj_create(ui_Container__Home__Container6);
    lv_obj_remove_style_all(ui_Container__Home__Container10);
    lv_obj_set_height(ui_Container__Home__Container10, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Home__Container10, 1);
    lv_obj_set_align(ui_Container__Home__Container10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Home__Container10, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Home__Container10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Home__Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container__Home__Container10, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Home__Container10, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Home__Container10, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Home__Container10, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Home__Container12 = lv_obj_create(ui_Container__Home__Container10);
    lv_obj_remove_style_all(ui_Container__Home__Container12);
    lv_obj_set_width(ui_Container__Home__Container12, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Home__Container12, 2);
    lv_obj_set_align(ui_Container__Home__Container12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Home__Container12, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Home__Container12, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Home__Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Container__Home__Container12, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_Container__Home__Container12, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_Container__Home__Container12, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container__Home__Container12, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label__Home__Label3 = lv_label_create(ui_Container__Home__Container12);
    lv_obj_set_width(ui_Label__Home__Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Home__Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label__Home__Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label__Home__Label3, "Pressure Target");
    ui_object_set_themeable_style_property(ui_Label__Home__Label3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Label__Home__Label3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(ui_Label__Home__Label3, &ui_font_P2_Med, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Home__Container14 = lv_obj_create(ui_Container__Home__Container12);
    lv_obj_remove_style_all(ui_Container__Home__Container14);
    lv_obj_set_width(ui_Container__Home__Container14, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Home__Container14, 1);
    lv_obj_set_align(ui_Container__Home__Container14, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Home__Container14, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Home__Container14, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Home__Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container__Home__Container14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Home__Container14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Home__Container14, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Home__Container14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Home__Container14, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Home__Container14, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label__Home__Label4 = lv_label_create(ui_Container__Home__Container14);
    lv_obj_set_width(ui_Label__Home__Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Home__Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label__Home__Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label__Home__Label4, "750");
    ui_object_set_themeable_style_property(ui_Label__Home__Label4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Label__Home__Label4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(ui_Label__Home__Label4, &ui_font_H1_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Home__Container15 = lv_obj_create(ui_Container__Home__Container14);
    lv_obj_remove_style_all(ui_Container__Home__Container15);
    lv_obj_set_height(ui_Container__Home__Container15, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Home__Container15, 1);
    lv_obj_set_align(ui_Container__Home__Container15, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Home__Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label__Home__Label5 = lv_label_create(ui_Container__Home__Container15);
    lv_obj_set_width(ui_Label__Home__Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Home__Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label__Home__Label5, 0);
    lv_obj_set_y(ui_Label__Home__Label5, -6);
    lv_obj_set_align(ui_Label__Home__Label5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label__Home__Label5, "psi");
    ui_object_set_themeable_style_property(ui_Label__Home__Label5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Label__Home__Label5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(ui_Label__Home__Label5, &ui_font_P1_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Home__Container13 = lv_obj_create(ui_Container__Home__Container10);
    lv_obj_remove_style_all(ui_Container__Home__Container13);
    lv_obj_set_width(ui_Container__Home__Container13, lv_pct(100));
    lv_obj_set_height(ui_Container__Home__Container13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container__Home__Container13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Home__Container13, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Home__Container13, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Home__Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container__Home__Container13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Home__Container13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Home__Container13, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Home__Container13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label__Home__Label6 = lv_label_create(ui_Container__Home__Container13);
    lv_obj_set_width(ui_Label__Home__Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Home__Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label__Home__Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label__Home__Label6, "Pressure:  ");
    ui_object_set_themeable_style_property(ui_Label__Home__Label6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Label__Home__Label6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(ui_Label__Home__Label6, &ui_font_P2_Med, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label__Home__Label7 = lv_label_create(ui_Container__Home__Container13);
    lv_obj_set_width(ui_Label__Home__Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Home__Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label__Home__Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label__Home__Label7, "750 psi");
    ui_object_set_themeable_style_property(ui_Label__Home__Label7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Label__Home__Label7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(ui_Label__Home__Label7, &ui_font_P2_SBold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Home__Buttons_Group = lv_obj_create(ui_Container__Home__Container6);
    lv_obj_remove_style_all(ui_Container__Home__Buttons_Group);
    lv_obj_set_height(ui_Container__Home__Buttons_Group, lv_pct(100));
    lv_obj_set_width(ui_Container__Home__Buttons_Group, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_x(ui_Container__Home__Buttons_Group, 166);
    lv_obj_set_y(ui_Container__Home__Buttons_Group, -32);
    lv_obj_set_align(ui_Container__Home__Buttons_Group, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Home__Buttons_Group, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Home__Buttons_Group, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Home__Buttons_Group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container__Home__Buttons_Group, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Home__Buttons_Group, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Home__Buttons_Group, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Home__Buttons_Group, 16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContorlButton__Home__ContorlButton = ui_Button____ContorlButton_create(ui_Container__Home__Buttons_Group);
    lv_obj_set_width(ui_ContorlButton__Home__ContorlButton, 180);
    lv_obj_set_height(ui_ContorlButton__Home__ContorlButton, 80);
    lv_obj_set_x(ui_ContorlButton__Home__ContorlButton, 0);
    lv_obj_set_y(ui_ContorlButton__Home__ContorlButton, 0);

    ui_ContorlButton__Home__ContorlButton1 = ui_Button____ContorlButton_create(ui_Container__Home__Buttons_Group);
    lv_obj_set_width(ui_ContorlButton__Home__ContorlButton1, 180);
    lv_obj_set_height(ui_ContorlButton__Home__ContorlButton1, 80);
    lv_obj_set_x(ui_ContorlButton__Home__ContorlButton1, 0);
    lv_obj_set_y(ui_ContorlButton__Home__ContorlButton1, 0);
    lv_obj_add_state(ui_ContorlButton__Home__ContorlButton1, LV_STATE_USER_1);       /// States

    ui_Container__Home__Dispense_Group = lv_obj_create(ui_Container__Home__Container6);
    lv_obj_remove_style_all(ui_Container__Home__Dispense_Group);
    lv_obj_set_height(ui_Container__Home__Dispense_Group, lv_pct(100));
    lv_obj_set_width(ui_Container__Home__Dispense_Group, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_x(ui_Container__Home__Dispense_Group, 0);
    lv_obj_set_y(ui_Container__Home__Dispense_Group, 1);
    lv_obj_set_align(ui_Container__Home__Dispense_Group, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Home__Dispense_Group, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Home__Dispense_Group, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Container__Home__Dispense_Group, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Container__Home__Dispense_Group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container__Home__Dispense_Group, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Home__Dispense_Group, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Home__Dispense_Group, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Home__Dispense_Group, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Home__Dispense_Group, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Home__Dispense_Group, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Home__Container105 = lv_obj_create(ui_Container__Home__Dispense_Group);
    lv_obj_remove_style_all(ui_Container__Home__Container105);
    lv_obj_set_width(ui_Container__Home__Container105, LV_SIZE_CONTENT);   /// 132
    lv_obj_set_flex_grow(ui_Container__Home__Container105, 1);
    lv_obj_set_align(ui_Container__Home__Container105, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Home__Container105, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Home__Container105, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Home__Container105, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container__Home__Container105, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Home__Container105, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Input__Home__Input24 = ui_Container____Input_create(ui_Container__Home__Container105);
    lv_obj_set_width(ui_Input__Home__Input24, 120);
    lv_obj_set_height(ui_Input__Home__Input24, LV_SIZE_CONTENT);    /// 86
    lv_obj_set_x(ui_Input__Home__Input24, 0);
    lv_obj_set_y(ui_Input__Home__Input24, 0);



    lv_label_set_text(ui_comp_get_child(ui_Input__Home__Input24,
                                        UI_COMP_CONTAINER____INPUT_CONTAINER____LABEL_PADDING_LABEL____LABEL), "Amount");



    ui_Input__Home__Input20 = ui_Container____Input_create(ui_Container__Home__Container105);
    lv_obj_set_width(ui_Input__Home__Input20, 120);
    lv_obj_set_height(ui_Input__Home__Input20, LV_SIZE_CONTENT);    /// 86
    lv_obj_set_x(ui_Input__Home__Input20, 0);
    lv_obj_set_y(ui_Input__Home__Input20, 0);



    lv_label_set_text(ui_comp_get_child(ui_Input__Home__Input20,
                                        UI_COMP_CONTAINER____INPUT_CONTAINER____LABEL_PADDING_LABEL____LABEL), "Duration");



    ui_Container__Home__Container106 = lv_obj_create(ui_Container__Home__Dispense_Group);
    lv_obj_remove_style_all(ui_Container__Home__Container106);
    lv_obj_set_width(ui_Container__Home__Container106, LV_SIZE_CONTENT);   /// 132
    lv_obj_set_flex_grow(ui_Container__Home__Container106, 1);
    lv_obj_set_align(ui_Container__Home__Container106, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Home__Container106, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Home__Container106, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Home__Container106, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container__Home__Container106, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Home__Container106, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Input__Home__Input21 = ui_Container____Input_create(ui_Container__Home__Container106);
    lv_obj_set_width(ui_Input__Home__Input21, 120);
    lv_obj_set_height(ui_Input__Home__Input21, LV_SIZE_CONTENT);    /// 86
    lv_obj_set_x(ui_Input__Home__Input21, 0);
    lv_obj_set_y(ui_Input__Home__Input21, 0);



    lv_label_set_text(ui_comp_get_child(ui_Input__Home__Input21,
                                        UI_COMP_CONTAINER____INPUT_CONTAINER____LABEL_PADDING_LABEL____LABEL), "Delay");



    ui_Input__Home__Input22 = ui_Container____Input_create(ui_Container__Home__Container106);
    lv_obj_set_width(ui_Input__Home__Input22, 120);
    lv_obj_set_height(ui_Input__Home__Input22, LV_SIZE_CONTENT);    /// 86
    lv_obj_set_x(ui_Input__Home__Input22, 0);
    lv_obj_set_y(ui_Input__Home__Input22, 0);



    lv_label_set_text(ui_comp_get_child(ui_Input__Home__Input22,
                                        UI_COMP_CONTAINER____INPUT_CONTAINER____LABEL_PADDING_LABEL____LABEL), "Occurrences");



    ui_Container__Home__Container8 = lv_obj_create(ui_Container__Home__Container7);
    lv_obj_remove_style_all(ui_Container__Home__Container8);
    lv_obj_set_height(ui_Container__Home__Container8, 120);
    lv_obj_set_width(ui_Container__Home__Container8, lv_pct(100));
    lv_obj_set_x(ui_Container__Home__Container8, -1);
    lv_obj_set_y(ui_Container__Home__Container8, -12);
    lv_obj_set_align(ui_Container__Home__Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Home__Container8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Home__Container8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Home__Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container__Home__Container8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Home__Container8, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Home__Container8, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Home__Container8, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Home__Container16 = lv_obj_create(ui_Container__Home__Container8);
    lv_obj_remove_style_all(ui_Container__Home__Container16);
    lv_obj_set_width(ui_Container__Home__Container16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Container__Home__Container16, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Container__Home__Container16, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Home__Container16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Secondarybtn__Home__Select_Options2 = ui_Button____Secondarybtn_create(ui_Container__Home__Container16);
    lv_obj_set_width(ui_Secondarybtn__Home__Select_Options2, LV_SIZE_CONTENT);   /// 199
    lv_obj_set_height(ui_Secondarybtn__Home__Select_Options2, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Secondarybtn__Home__Select_Options2, 0);
    lv_obj_set_y(ui_Secondarybtn__Home__Select_Options2, 0);
    lv_obj_set_flex_flow(ui_Secondarybtn__Home__Select_Options2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Secondarybtn__Home__Select_Options2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);

    lv_obj_set_width(ui_comp_get_child(ui_Secondarybtn__Home__Select_Options2,
                                       UI_COMP_BUTTON____SECONDARYBTN_LABEL____LABEL), LV_SIZE_CONTENT);  /// 100
    lv_obj_set_height(ui_comp_get_child(ui_Secondarybtn__Home__Select_Options2,
                                        UI_COMP_BUTTON____SECONDARYBTN_LABEL____LABEL), LV_SIZE_CONTENT);   /// 100
    lv_label_set_text(ui_comp_get_child(ui_Secondarybtn__Home__Select_Options2,
                                        UI_COMP_BUTTON____SECONDARYBTN_LABEL____LABEL), "Purge");

    ui_Image__Home__Image6 = lv_image_create(ui_Secondarybtn__Home__Select_Options2);
    lv_image_set_src(ui_Image__Home__Image6, ui_img_home_buttons_purge_png);
    lv_obj_set_width(ui_Image__Home__Image6, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_Image__Home__Image6, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_align(ui_Image__Home__Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image__Home__Image6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image__Home__Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container__Home__Container17 = lv_obj_create(ui_Container__Home__Container8);
    lv_obj_remove_style_all(ui_Container__Home__Container17);
    lv_obj_set_height(ui_Container__Home__Container17, lv_pct(81));
    lv_obj_set_flex_grow(ui_Container__Home__Container17, 1);
    lv_obj_set_align(ui_Container__Home__Container17, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Home__Container17, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Home__Container17, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Home__Container17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container__Home__Container17, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Home__Container17, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Home__Container17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Home__Container17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Home__Container17, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Home__Container17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Home__Container19 = lv_obj_create(ui_Container__Home__Container17);
    lv_obj_remove_style_all(ui_Container__Home__Container19);
    lv_obj_set_width(ui_Container__Home__Container19, lv_pct(100));
    lv_obj_set_height(ui_Container__Home__Container19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container__Home__Container19, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Home__Container19, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Home__Container19, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Home__Container19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container__Home__Container19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Home__Container19, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label__Home__Label8 = lv_label_create(ui_Container__Home__Container19);
    lv_obj_set_width(ui_Label__Home__Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Home__Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label__Home__Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label__Home__Label8, "Run Time:");
    ui_object_set_themeable_style_property(ui_Label__Home__Label8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Label__Home__Label8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(ui_Label__Home__Label8, &ui_font_P2_Med, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label__Home__Label9 = lv_label_create(ui_Container__Home__Container19);
    lv_obj_set_width(ui_Label__Home__Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Home__Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label__Home__Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label__Home__Label9, "10 min");
    ui_object_set_themeable_style_property(ui_Label__Home__Label9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Label__Home__Label9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(ui_Label__Home__Label9, &ui_font_P2_SBold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Home__Container20 = lv_obj_create(ui_Container__Home__Container17);
    lv_obj_remove_style_all(ui_Container__Home__Container20);
    lv_obj_set_width(ui_Container__Home__Container20, lv_pct(100));
    lv_obj_set_height(ui_Container__Home__Container20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container__Home__Container20, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Home__Container20, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Home__Container20, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Home__Container20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container__Home__Container20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Home__Container20, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label__Home__Label10 = lv_label_create(ui_Container__Home__Container20);
    lv_obj_set_width(ui_Label__Home__Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Home__Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label__Home__Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label__Home__Label10, "Flow Total:");
    ui_object_set_themeable_style_property(ui_Label__Home__Label10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Label__Home__Label10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(ui_Label__Home__Label10, &ui_font_P2_Med, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label__Home__Label11 = lv_label_create(ui_Container__Home__Container20);
    lv_obj_set_width(ui_Label__Home__Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Home__Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label__Home__Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label__Home__Label11, "800 mL");
    ui_object_set_themeable_style_property(ui_Label__Home__Label11, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Label__Home__Label11, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(ui_Label__Home__Label11, &ui_font_P2_SBold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Primarybtn__Home__Start = ui_Button____Primarybtn_create(ui_Container__Home__Container8);
    lv_obj_set_width(ui_Primarybtn__Home__Start, 180);
    lv_obj_set_height(ui_Primarybtn__Home__Start, 74);
    lv_obj_set_x(ui_Primarybtn__Home__Start, 0);
    lv_obj_set_y(ui_Primarybtn__Home__Start, 0);
    lv_obj_set_align(ui_Primarybtn__Home__Start, LV_ALIGN_RIGHT_MID);
    ui_object_set_themeable_style_property(ui_Primarybtn__Home__Start, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Green);
    ui_object_set_themeable_style_property(ui_Primarybtn__Home__Start, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Green);
    lv_obj_set_style_pad_left(ui_Primarybtn__Home__Start, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Primarybtn__Home__Start, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Primarybtn__Home__Start, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Primarybtn__Home__Start, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Primarybtn__Home__Start, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_Primarybtn__Home__Start, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Blue);

    lv_label_set_text(ui_comp_get_child(ui_Primarybtn__Home__Start, UI_COMP_BUTTON____PRIMARYBTN_LABEL____LABEL), "Start");
    lv_obj_set_style_text_font(ui_comp_get_child(ui_Primarybtn__Home__Start, UI_COMP_BUTTON____PRIMARYBTN_LABEL____LABEL),
                               &ui_font_P1_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Home__Footer = lv_obj_create(ui_Container__Home__Container3);
    lv_obj_remove_style_all(ui_Container__Home__Footer);
    lv_obj_set_height(ui_Container__Home__Footer, 34);
    lv_obj_set_width(ui_Container__Home__Footer, lv_pct(100));
    lv_obj_set_align(ui_Container__Home__Footer, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Container__Home__Footer, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_remove_flag(ui_Container__Home__Footer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Container__Home__Footer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Container__Home__Footer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Dark_blue);

    ui_Label__Home__Label12 = lv_label_create(ui_Container__Home__Footer);
    lv_obj_set_width(ui_Label__Home__Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Home__Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label__Home__Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label__Home__Label12, "Visit eldex.com/support for manuals and help");
    ui_object_set_themeable_style_property(ui_Label__Home__Label12, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Interface);
    ui_object_set_themeable_style_property(ui_Label__Home__Label12, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Interface);
    lv_obj_set_style_text_font(ui_Label__Home__Label12, &ui_font_P3_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Numpad_M__Home__Numpad_M2 = ui_Keyboard____Numpad_M_create(ui_Screen__Home);
    lv_obj_set_width(ui_Numpad_M__Home__Numpad_M2, 474);
    lv_obj_set_height(ui_Numpad_M__Home__Numpad_M2, 410);
    lv_obj_set_x(ui_Numpad_M__Home__Numpad_M2, -3);
    lv_obj_set_y(ui_Numpad_M__Home__Numpad_M2, -47);
    lv_obj_add_flag(ui_Numpad_M__Home__Numpad_M2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags

    lv_obj_add_event_cb(ui_comp_get_child(ui_Menu__Home__Menu, UI_COMP_CONTAINER____MENU_MENUBUTTON____MENU_BUTTON_PUMP),
                        ui_event_Menu__Home__Menu_MenuButton____Menu_Button_Pump, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Menu__Home__Menu, UI_COMP_CONTAINER____MENU_MENUBUTTON____MENU_BUTTON_SETUP),
                        ui_event_Menu__Home__Menu_MenuButton____Menu_Button_Setup, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input__Home__Input24, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                        ui_event_Input__Home__Input24_Textarea____TextArea1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input__Home__Input20, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                        ui_event_Input__Home__Input20_Textarea____TextArea1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input__Home__Input21, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                        ui_event_Input__Home__Input21_Textarea____TextArea1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input__Home__Input22, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                        ui_event_Input__Home__Input22_Textarea____TextArea1, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Numpad_M__Home__Numpad_M2, ui_comp_get_child(ui_Input__Home__Input24,
                                                                             UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1));
    lv_obj_add_event_cb(ui_Numpad_M__Home__Numpad_M2, ui_event_Numpad_M__Home__Numpad_M2_Keyboard____Numpad_M, LV_EVENT_ALL,
                        NULL);
    ui_MenuButton__Home__Menu = ui_comp_get_child(ui_Menu__Home__Menu,
                                                  UI_COMP_CONTAINER____MENU_MENUBUTTON____MENU_BUTTON_HOME);
    ui_MenuButton__Home__Pump = ui_comp_get_child(ui_Menu__Home__Menu,
                                                  UI_COMP_CONTAINER____MENU_MENUBUTTON____MENU_BUTTON_PUMP);
    ui_MenuButton__Home__Setup = ui_comp_get_child(ui_Menu__Home__Menu,
                                                   UI_COMP_CONTAINER____MENU_MENUBUTTON____MENU_BUTTON_SETUP);
    ui_Label__Home__ScreenTitle = ui_comp_get_child(ui_Header__Home__Header, UI_COMP_CONTAINER____HEADER_LABEL____TITLE);
    ui_Image__Home__USB_Status = ui_comp_get_child(ui_Header__Home__Header,
                                                   UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____USB);
    ui_Image__Home__Ethernet_Status = ui_comp_get_child(ui_Header__Home__Header,
                                                        UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____ETHERNET);
    ui_Image__Home__WiFi_Status = ui_comp_get_child(ui_Header__Home__Header,
                                                    UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____WIFI);
    ui_Button__Home__Pump1 = ui_TabButton__Home__TabButton7;
    ui_Button__Home__Pump2 = ui_TabButton__Home__TabButton4;
    ui_Button__Home__Pump3 = ui_TabButton__Home__TabButton5;
    ui_Label__Home__MainValue_Title = ui_Label__Home__Label3;
    ui_Label__Home__MainValue = ui_Label__Home__Label4;
    ui_Label__Home__MainValue_Unit = ui_Label__Home__Label5;
    ui_Label__Home__CurrentPressure = ui_Label__Home__Label7;
    ui_Container__Home__ButtonGroup = ui_Container__Home__Buttons_Group;
    ui_Button__Home__FlowOrPressure_Up = ui_ContorlButton__Home__ContorlButton;
    ui_Button__Home__FlowOrPressure_Down = ui_ContorlButton__Home__ContorlButton1;
    ui_Container__Home__DispenseGroup = ui_Container__Home__Dispense_Group;
    ui_Textarea__Home__Dispense_FluidAmount = ui_comp_get_child(ui_Input__Home__Input24,
                                                                UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1);
    ui_Textarea__Home__Dispense_PumpRunDuration = ui_comp_get_child(ui_Input__Home__Input20,
                                                                    UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1);
    ui_Textarea__Home__Dispense_RepeatDelay = ui_comp_get_child(ui_Input__Home__Input21,
                                                                UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1);
    ui_Textarea__Home__Dispense_RepeatAmount = ui_comp_get_child(ui_Input__Home__Input22,
                                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1);
    ui_Button__Home__Purge = ui_Secondarybtn__Home__Select_Options2;
    ui_Label__Home__RunTime = ui_Label__Home__Label9;
    ui_Label__Home__Total_PumpedFlowAmount = ui_Label__Home__Label11;
    ui_Button__Home__StartStop = ui_Primarybtn__Home__Start;
    ui_Label__Home__StatusFooter = ui_Label__Home__Label12;
    ui_Keyboard__Home__DispenseDataEntry = ui_Numpad_M__Home__Numpad_M2;

}
