// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "../ui.h"

void ui_Screen__Maintenance_screen_init(void)
{
    ui_Screen__Maintenance = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen__Maintenance, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Screen__Maintenance, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screen__Maintenance, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    ui_object_set_themeable_style_property(ui_Screen__Maintenance, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Bg_);
    ui_object_set_themeable_style_property(ui_Screen__Maintenance, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Bg_);
    lv_obj_set_style_pad_left(ui_Screen__Maintenance, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Screen__Maintenance, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Screen__Maintenance, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Screen__Maintenance, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Screen__Maintenance, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Screen__Maintenance, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Maintenance__Container66 = lv_obj_create(ui_Screen__Maintenance);
    lv_obj_remove_style_all(ui_Container__Maintenance__Container66);
    lv_obj_set_height(ui_Container__Maintenance__Container66, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Maintenance__Container66, 1);
    lv_obj_set_align(ui_Container__Maintenance__Container66, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Maintenance__Container66, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Maintenance__Container66, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Maintenance__Container66,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container__Maintenance__Container66, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Container__Maintenance__Container66, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Maintenance__Container66, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Maintenance__Container66, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Header__Maintenance__Header6 = ui_Container____Header_create(ui_Container__Maintenance__Container66);
    lv_obj_set_x(ui_Header__Maintenance__Header6, 0);
    lv_obj_set_y(ui_Header__Maintenance__Header6, 0);

    lv_obj_remove_flag(ui_comp_get_child(ui_Header__Maintenance__Header6,
                                         UI_COMP_CONTAINER____HEADER_BUTTON____BACK_BUTTON), LV_OBJ_FLAG_HIDDEN);     /// Flags


    lv_label_set_text(ui_comp_get_child(ui_Header__Maintenance__Header6, UI_COMP_CONTAINER____HEADER_LABEL____TITLE),
                      "Maintenance");



    lv_obj_add_flag(ui_comp_get_child(ui_Header__Maintenance__Header6,
                                      UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____USB), LV_OBJ_FLAG_HIDDEN);    /// Flags

    lv_obj_add_flag(ui_comp_get_child(ui_Header__Maintenance__Header6,
                                      UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____ETHERNET), LV_OBJ_FLAG_HIDDEN);    /// Flags

    lv_obj_add_flag(ui_comp_get_child(ui_Header__Maintenance__Header6,
                                      UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____WIFI), LV_OBJ_FLAG_HIDDEN);    /// Flags

    ui_Container__Maintenance__Content9 = lv_obj_create(ui_Container__Maintenance__Container66);
    lv_obj_remove_style_all(ui_Container__Maintenance__Content9);
    lv_obj_set_width(ui_Container__Maintenance__Content9, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Maintenance__Content9, 1);
    lv_obj_set_align(ui_Container__Maintenance__Content9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Maintenance__Content9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Maintenance__Content9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Maintenance__Content9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container__Maintenance__Content9, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Container__Maintenance__Content9, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_Container__Maintenance__Content9, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_Container__Maintenance__Content9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Container__Maintenance__Content9, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Maintenance__Content9, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Maintenance__Content9, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Maintenance__Content9, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Maintenance__Content9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Maintenance__Content9, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Maintenance__Container85 = lv_obj_create(ui_Container__Maintenance__Content9);
    lv_obj_remove_style_all(ui_Container__Maintenance__Container85);
    lv_obj_set_width(ui_Container__Maintenance__Container85, 260);
    lv_obj_set_height(ui_Container__Maintenance__Container85, lv_pct(100));
    lv_obj_set_align(ui_Container__Maintenance__Container85, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Maintenance__Container85, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Maintenance__Container85, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Maintenance__Container85,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container__Maintenance__Container85, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Maintenance__Container85, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Maintenance__Container85, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Maintenance__Container85, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Maintenance__Container85, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Maintenance__Container85, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Input__Maintenance__Input9 = ui_Container____Input_create(ui_Container__Maintenance__Container85);
    lv_obj_set_width(ui_Input__Maintenance__Input9, lv_pct(100));
    lv_obj_set_height(ui_Input__Maintenance__Input9, LV_SIZE_CONTENT);    /// 86
    lv_obj_set_x(ui_Input__Maintenance__Input9, 0);
    lv_obj_set_y(ui_Input__Maintenance__Input9, 0);



    lv_obj_set_width(ui_comp_get_child(ui_Input__Maintenance__Input9, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                     lv_pct(100));
    lv_obj_set_height(ui_comp_get_child(ui_Input__Maintenance__Input9, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                      LV_SIZE_CONTENT);   /// 40
    lv_obj_set_style_pad_left(ui_comp_get_child(ui_Input__Maintenance__Input9,
                                                UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_comp_get_child(ui_Input__Maintenance__Input9,
                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_comp_get_child(ui_Input__Maintenance__Input9,
                                               UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_comp_get_child(ui_Input__Maintenance__Input9,
                                                  UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_comp_get_child(ui_Input__Maintenance__Input9,
                                                UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 14, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_right(ui_comp_get_child(ui_Input__Maintenance__Input9,
                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_top(ui_comp_get_child(ui_Input__Maintenance__Input9,
                                               UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 6, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_bottom(ui_comp_get_child(ui_Input__Maintenance__Input9,
                                                  UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_FOCUSED);



    ui_Input__Maintenance__Input10 = ui_Container____Input_create(ui_Container__Maintenance__Container85);
    lv_obj_set_width(ui_Input__Maintenance__Input10, lv_pct(100));
    lv_obj_set_height(ui_Input__Maintenance__Input10, LV_SIZE_CONTENT);    /// 86
    lv_obj_set_x(ui_Input__Maintenance__Input10, 0);
    lv_obj_set_y(ui_Input__Maintenance__Input10, 0);



    lv_label_set_text(ui_comp_get_child(ui_Input__Maintenance__Input10,
                                        UI_COMP_CONTAINER____INPUT_CONTAINER____LABEL_PADDING_LABEL____LABEL), "Model Number");

    lv_obj_set_width(ui_comp_get_child(ui_Input__Maintenance__Input10, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                     lv_pct(100));
    lv_obj_set_height(ui_comp_get_child(ui_Input__Maintenance__Input10, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                      LV_SIZE_CONTENT);   /// 40
    lv_obj_set_style_pad_left(ui_comp_get_child(ui_Input__Maintenance__Input10,
                                                UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_comp_get_child(ui_Input__Maintenance__Input10,
                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_comp_get_child(ui_Input__Maintenance__Input10,
                                               UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_comp_get_child(ui_Input__Maintenance__Input10,
                                                  UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_comp_get_child(ui_Input__Maintenance__Input10,
                                                UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 14, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_right(ui_comp_get_child(ui_Input__Maintenance__Input10,
                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_top(ui_comp_get_child(ui_Input__Maintenance__Input10,
                                               UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 6, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_bottom(ui_comp_get_child(ui_Input__Maintenance__Input10,
                                                  UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_FOCUSED);



    ui_Container__Maintenance__Container76 = lv_obj_create(ui_Container__Maintenance__Container85);
    lv_obj_remove_style_all(ui_Container__Maintenance__Container76);
    lv_obj_set_width(ui_Container__Maintenance__Container76, lv_pct(100));
    lv_obj_set_height(ui_Container__Maintenance__Container76, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Container__Maintenance__Container76, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Maintenance__Container76, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Maintenance__Container76, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Maintenance__Container76,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container__Maintenance__Container76, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Maintenance__Container76, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Input__Maintenance__Input11 = ui_Container____Input_create(ui_Container__Maintenance__Container76);
    lv_obj_set_height(ui_Input__Maintenance__Input11, LV_SIZE_CONTENT);    /// 86
    lv_obj_set_flex_grow(ui_Input__Maintenance__Input11, 1);
    lv_obj_set_x(ui_Input__Maintenance__Input11, 0);
    lv_obj_set_y(ui_Input__Maintenance__Input11, 0);



    lv_label_set_text(ui_comp_get_child(ui_Input__Maintenance__Input11,
                                        UI_COMP_CONTAINER____INPUT_CONTAINER____LABEL_PADDING_LABEL____LABEL), "Firmware");

    lv_obj_set_height(ui_comp_get_child(ui_Input__Maintenance__Input11, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                      40);
    lv_obj_set_width(ui_comp_get_child(ui_Input__Maintenance__Input11, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                     lv_pct(100));
    lv_textarea_set_placeholder_text(ui_comp_get_child(ui_Input__Maintenance__Input11,
                                                       UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), "1.01");
    lv_obj_set_style_pad_left(ui_comp_get_child(ui_Input__Maintenance__Input11,
                                                UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_comp_get_child(ui_Input__Maintenance__Input11,
                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_comp_get_child(ui_Input__Maintenance__Input11,
                                               UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_comp_get_child(ui_Input__Maintenance__Input11,
                                                  UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_comp_get_child(ui_Input__Maintenance__Input11,
                                                UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 14, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_right(ui_comp_get_child(ui_Input__Maintenance__Input11,
                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_top(ui_comp_get_child(ui_Input__Maintenance__Input11,
                                               UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 6, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_bottom(ui_comp_get_child(ui_Input__Maintenance__Input11,
                                                  UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_FOCUSED);



    ui_Input__Maintenance__Input12 = ui_Container____Input_create(ui_Container__Maintenance__Container76);
    lv_obj_set_height(ui_Input__Maintenance__Input12, LV_SIZE_CONTENT);    /// 86
    lv_obj_set_flex_grow(ui_Input__Maintenance__Input12, 1);
    lv_obj_set_x(ui_Input__Maintenance__Input12, 0);
    lv_obj_set_y(ui_Input__Maintenance__Input12, 0);



    lv_label_set_text(ui_comp_get_child(ui_Input__Maintenance__Input12,
                                        UI_COMP_CONTAINER____INPUT_CONTAINER____LABEL_PADDING_LABEL____LABEL), "GUI");

    lv_obj_set_height(ui_comp_get_child(ui_Input__Maintenance__Input12, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                      40);
    lv_obj_set_width(ui_comp_get_child(ui_Input__Maintenance__Input12, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                     lv_pct(100));
    lv_textarea_set_placeholder_text(ui_comp_get_child(ui_Input__Maintenance__Input12,
                                                       UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), "1.01");
    lv_obj_set_style_pad_left(ui_comp_get_child(ui_Input__Maintenance__Input12,
                                                UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_comp_get_child(ui_Input__Maintenance__Input12,
                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_comp_get_child(ui_Input__Maintenance__Input12,
                                               UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_comp_get_child(ui_Input__Maintenance__Input12,
                                                  UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_comp_get_child(ui_Input__Maintenance__Input12,
                                                UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 14, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_right(ui_comp_get_child(ui_Input__Maintenance__Input12,
                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_top(ui_comp_get_child(ui_Input__Maintenance__Input12,
                                               UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 6, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_bottom(ui_comp_get_child(ui_Input__Maintenance__Input12,
                                                  UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_FOCUSED);



    ui_Input__Maintenance__Input13 = ui_Container____Input_create(ui_Container__Maintenance__Container85);
    lv_obj_set_width(ui_Input__Maintenance__Input13, lv_pct(100));
    lv_obj_set_height(ui_Input__Maintenance__Input13, LV_SIZE_CONTENT);    /// 86
    lv_obj_set_x(ui_Input__Maintenance__Input13, 0);
    lv_obj_set_y(ui_Input__Maintenance__Input13, 0);



    lv_label_set_text(ui_comp_get_child(ui_Input__Maintenance__Input13,
                                        UI_COMP_CONTAINER____INPUT_CONTAINER____LABEL_PADDING_LABEL____LABEL), "Pump1 Total Run");

    lv_obj_set_height(ui_comp_get_child(ui_Input__Maintenance__Input13, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                      40);
    lv_obj_set_width(ui_comp_get_child(ui_Input__Maintenance__Input13, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                     lv_pct(100));
    lv_textarea_set_placeholder_text(ui_comp_get_child(ui_Input__Maintenance__Input13,
                                                       UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), "35 hours");
    lv_obj_set_style_pad_left(ui_comp_get_child(ui_Input__Maintenance__Input13,
                                                UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_comp_get_child(ui_Input__Maintenance__Input13,
                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_comp_get_child(ui_Input__Maintenance__Input13,
                                               UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_comp_get_child(ui_Input__Maintenance__Input13,
                                                  UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_comp_get_child(ui_Input__Maintenance__Input13,
                                                UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 14, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_right(ui_comp_get_child(ui_Input__Maintenance__Input13,
                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_top(ui_comp_get_child(ui_Input__Maintenance__Input13,
                                               UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 6, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_bottom(ui_comp_get_child(ui_Input__Maintenance__Input13,
                                                  UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_FOCUSED);



    ui_Panel__Maintenance__Panel2 = lv_obj_create(ui_Container__Maintenance__Container85);
    lv_obj_set_width(ui_Panel__Maintenance__Panel2, lv_pct(100));
    lv_obj_set_flex_grow(ui_Panel__Maintenance__Panel2, 1);
    lv_obj_set_align(ui_Panel__Maintenance__Panel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel__Maintenance__Panel2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel__Maintenance__Panel2, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_Panel__Maintenance__Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel__Maintenance__Panel2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Panel__Maintenance__Panel2, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_White);
    ui_object_set_themeable_style_property(ui_Panel__Maintenance__Panel2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_White);

    ui_Container__Maintenance__Container79 = lv_obj_create(ui_Panel__Maintenance__Panel2);
    lv_obj_remove_style_all(ui_Container__Maintenance__Container79);
    lv_obj_set_height(ui_Container__Maintenance__Container79, lv_pct(100));
    lv_obj_set_width(ui_Container__Maintenance__Container79, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(ui_Container__Maintenance__Container79, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Maintenance__Container79, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Maintenance__Container79, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Maintenance__Container79,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container__Maintenance__Container79, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Maintenance__Container79, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label__Maintenance__Label30 = lv_label_create(ui_Container__Maintenance__Container79);
    lv_obj_set_width(ui_Label__Maintenance__Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Maintenance__Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label__Maintenance__Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label__Maintenance__Label30, "Washport");
    ui_object_set_themeable_style_property(ui_Label__Maintenance__Label30, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Label__Maintenance__Label30, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(ui_Label__Maintenance__Label30, &ui_font_P3_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Secondarybtn__Maintenance__Select_Options9 = ui_Button____Secondarybtn_create(
                                                        ui_Container__Maintenance__Container79);
    lv_obj_set_height(ui_Secondarybtn__Maintenance__Select_Options9, 54);
    lv_obj_set_width(ui_Secondarybtn__Maintenance__Select_Options9, LV_SIZE_CONTENT);   /// 199
    lv_obj_set_x(ui_Secondarybtn__Maintenance__Select_Options9, 0);
    lv_obj_set_y(ui_Secondarybtn__Maintenance__Select_Options9, 0);
    lv_obj_set_style_min_height(ui_Secondarybtn__Maintenance__Select_Options9, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_height(ui_Secondarybtn__Maintenance__Select_Options9, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_width(ui_comp_get_child(ui_Secondarybtn__Maintenance__Select_Options9,
                                       UI_COMP_BUTTON____SECONDARYBTN_LABEL____LABEL), LV_SIZE_CONTENT);  /// 100
    lv_obj_set_height(ui_comp_get_child(ui_Secondarybtn__Maintenance__Select_Options9,
                                        UI_COMP_BUTTON____SECONDARYBTN_LABEL____LABEL), LV_SIZE_CONTENT);   /// 100
    lv_label_set_text(ui_comp_get_child(ui_Secondarybtn__Maintenance__Select_Options9,
                                        UI_COMP_BUTTON____SECONDARYBTN_LABEL____LABEL), "Rinse");

    ui_Container__Maintenance__Container81 = lv_obj_create(ui_Panel__Maintenance__Panel2);
    lv_obj_remove_style_all(ui_Container__Maintenance__Container81);
    lv_obj_set_height(ui_Container__Maintenance__Container81, lv_pct(100));
    lv_obj_set_width(ui_Container__Maintenance__Container81, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(ui_Container__Maintenance__Container81, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Maintenance__Container81, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Maintenance__Container81, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Maintenance__Container81,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container__Maintenance__Container81, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Maintenance__Container81, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label__Maintenance__Label27 = lv_label_create(ui_Container__Maintenance__Container81);
    lv_obj_set_width(ui_Label__Maintenance__Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Maintenance__Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label__Maintenance__Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label__Maintenance__Label27, "Auto");
    ui_object_set_themeable_style_property(ui_Label__Maintenance__Label27, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Label__Maintenance__Label27, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(ui_Label__Maintenance__Label27, &ui_font_P3_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch__Maintenance__Switch4 = ui_Container____Switch_create(ui_Container__Maintenance__Container81);
    lv_obj_set_x(ui_Switch__Maintenance__Switch4, 0);
    lv_obj_set_y(ui_Switch__Maintenance__Switch4, 0);

    lv_obj_add_flag(ui_comp_get_child(ui_Switch__Maintenance__Switch4, UI_COMP_CONTAINER____SWITCH_LABEL____LABEL23),
                    LV_OBJ_FLAG_HIDDEN);    /// Flags



    ui_Container__Maintenance__Container82 = lv_obj_create(ui_Container__Maintenance__Content9);
    lv_obj_remove_style_all(ui_Container__Maintenance__Container82);
    lv_obj_set_height(ui_Container__Maintenance__Container82, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Maintenance__Container82, 1);
    lv_obj_set_align(ui_Container__Maintenance__Container82, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Maintenance__Container82, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Maintenance__Container82, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Maintenance__Container82,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container__Maintenance__Container82, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Maintenance__Container82, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label__Maintenance__Label38 = lv_label_create(ui_Container__Maintenance__Container82);
    lv_obj_set_width(ui_Label__Maintenance__Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Maintenance__Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label__Maintenance__Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label__Maintenance__Label38, "Alarm Reminder");
    ui_object_set_themeable_style_property(ui_Label__Maintenance__Label38, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Label__Maintenance__Label38, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(ui_Label__Maintenance__Label38, &ui_font_P3_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Maintenance__tab_Initial4 = lv_obj_create(ui_Container__Maintenance__Container82);
    lv_obj_remove_style_all(ui_Container__Maintenance__tab_Initial4);
    lv_obj_set_width(ui_Container__Maintenance__tab_Initial4, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Maintenance__tab_Initial4, 1);
    lv_obj_set_align(ui_Container__Maintenance__tab_Initial4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Maintenance__tab_Initial4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Maintenance__tab_Initial4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Maintenance__tab_Initial4,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container__Maintenance__tab_Initial4, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Maintenance__tab_Initial4, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Maintenance__Container67 = lv_obj_create(ui_Container__Maintenance__tab_Initial4);
    lv_obj_remove_style_all(ui_Container__Maintenance__Container67);
    lv_obj_set_width(ui_Container__Maintenance__Container67, lv_pct(100));
    lv_obj_set_height(ui_Container__Maintenance__Container67, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Container__Maintenance__Container67, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Maintenance__Container67, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Maintenance__Container67, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Maintenance__Container67,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container__Maintenance__Container67, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Maintenance__Container67, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabButton__Maintenance__TabButton13 = ui_Button____TabButton_create(ui_Container__Maintenance__Container67);
    lv_obj_set_height(ui_TabButton__Maintenance__TabButton13, 36);
    lv_obj_set_flex_grow(ui_TabButton__Maintenance__TabButton13, 1);
    lv_obj_set_x(ui_TabButton__Maintenance__TabButton13, 0);
    lv_obj_set_y(ui_TabButton__Maintenance__TabButton13, 0);
    lv_obj_add_state(ui_TabButton__Maintenance__TabButton13, LV_STATE_CHECKED);       /// States

    lv_label_set_text(ui_comp_get_child(ui_TabButton__Maintenance__TabButton13, UI_COMP_BUTTON____TABBUTTON_LABEL____LABEL),
                      "Pump 1");

    ui_TabButton__Maintenance__TabButton14 = ui_Button____TabButton_create(ui_Container__Maintenance__Container67);
    lv_obj_set_height(ui_TabButton__Maintenance__TabButton14, 36);
    lv_obj_set_flex_grow(ui_TabButton__Maintenance__TabButton14, 1);
    lv_obj_set_x(ui_TabButton__Maintenance__TabButton14, 0);
    lv_obj_set_y(ui_TabButton__Maintenance__TabButton14, 0);
    lv_obj_remove_state(ui_TabButton__Maintenance__TabButton14, LV_STATE_CHECKED);     /// States

    lv_label_set_text(ui_comp_get_child(ui_TabButton__Maintenance__TabButton14, UI_COMP_BUTTON____TABBUTTON_LABEL____LABEL),
                      "Pump 2");

    ui_TabButton__Maintenance__TabButton15 = ui_Button____TabButton_create(ui_Container__Maintenance__Container67);
    lv_obj_set_height(ui_TabButton__Maintenance__TabButton15, 36);
    lv_obj_set_flex_grow(ui_TabButton__Maintenance__TabButton15, 1);
    lv_obj_set_x(ui_TabButton__Maintenance__TabButton15, 0);
    lv_obj_set_y(ui_TabButton__Maintenance__TabButton15, 0);
    lv_obj_remove_state(ui_TabButton__Maintenance__TabButton15, LV_STATE_CHECKED);     /// States

    lv_label_set_text(ui_comp_get_child(ui_TabButton__Maintenance__TabButton15, UI_COMP_BUTTON____TABBUTTON_LABEL____LABEL),
                      "Pump 3");

    ui_Container__Maintenance__Container68 = lv_obj_create(ui_Container__Maintenance__tab_Initial4);
    lv_obj_remove_style_all(ui_Container__Maintenance__Container68);
    lv_obj_set_width(ui_Container__Maintenance__Container68, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Maintenance__Container68, 1);
    lv_obj_set_align(ui_Container__Maintenance__Container68, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Maintenance__Container68, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Maintenance__Container68, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Maintenance__Container68,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container__Maintenance__Container70 = lv_obj_create(ui_Container__Maintenance__Container68);
    lv_obj_remove_style_all(ui_Container__Maintenance__Container70);
    lv_obj_set_width(ui_Container__Maintenance__Container70, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Maintenance__Container70, 2);
    lv_obj_set_align(ui_Container__Maintenance__Container70, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Maintenance__Container70, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Maintenance__Container70, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Maintenance__Container70,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container__Maintenance__Container70, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Container__Maintenance__Container70, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_White);
    ui_object_set_themeable_style_property(ui_Container__Maintenance__Container70, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_White);
    lv_obj_set_style_pad_left(ui_Container__Maintenance__Container70, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Maintenance__Container70, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Maintenance__Container70, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Maintenance__Container70, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Maintenance__Container78 = lv_obj_create(ui_Container__Maintenance__Container70);
    lv_obj_remove_style_all(ui_Container__Maintenance__Container78);
    lv_obj_set_height(ui_Container__Maintenance__Container78, 110);
    lv_obj_set_width(ui_Container__Maintenance__Container78, lv_pct(100));
    lv_obj_set_align(ui_Container__Maintenance__Container78, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Maintenance__Container78, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Maintenance__Container78, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Maintenance__Container78,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Container__Maintenance__Container78, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_Container__Maintenance__Container78, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_Container__Maintenance__Container78, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container__Maintenance__Container78, LV_BORDER_SIDE_BOTTOM,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Container__Maintenance__Container78, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Maintenance__Container78, -4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Maintenance__Container78, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Maintenance__Container78, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerSmall__Maintenance__RollerSmall5 = ui_Container____RollerSmall_create(ui_Container__Maintenance__Container78);
    lv_obj_set_x(ui_RollerSmall__Maintenance__RollerSmall5, 0);
    lv_obj_set_y(ui_RollerSmall__Maintenance__RollerSmall5, 0);

    lv_obj_add_flag(ui_comp_get_child(ui_RollerSmall__Maintenance__RollerSmall5,
                                      UI_COMP_CONTAINER____ROLLERSMALL_LABEL____TITLE), LV_OBJ_FLAG_HIDDEN);    /// Flags

    lv_roller_set_options(ui_comp_get_child(ui_RollerSmall__Maintenance__RollerSmall5,
                                            UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER), "Piston Seal\nCheck valve", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_comp_get_child(ui_RollerSmall__Maintenance__RollerSmall5,
                                       UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER), 181);
    lv_obj_set_height(ui_comp_get_child(ui_RollerSmall__Maintenance__RollerSmall5,
                                        UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER), lv_pct(100));

    ui_Input__Maintenance__Input8 = ui_Container____Input_create(ui_Container__Maintenance__Container78);
    lv_obj_set_width(ui_Input__Maintenance__Input8, 171);
    lv_obj_set_height(ui_Input__Maintenance__Input8, LV_SIZE_CONTENT);    /// 86
    lv_obj_set_x(ui_Input__Maintenance__Input8, 0);
    lv_obj_set_y(ui_Input__Maintenance__Input8, 0);



    lv_label_set_text(ui_comp_get_child(ui_Input__Maintenance__Input8,
                                        UI_COMP_CONTAINER____INPUT_CONTAINER____LABEL_PADDING_LABEL____LABEL), "Reminder");

    lv_textarea_set_placeholder_text(ui_comp_get_child(ui_Input__Maintenance__Input8,
                                                       UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), "500 Hrs");



    ui_Container__Maintenance__Container77 = lv_obj_create(ui_Container__Maintenance__Container70);
    lv_obj_remove_style_all(ui_Container__Maintenance__Container77);
    lv_obj_set_width(ui_Container__Maintenance__Container77, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Maintenance__Container77, 1);
    lv_obj_set_align(ui_Container__Maintenance__Container77, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Maintenance__Container77, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Maintenance__Container77, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Maintenance__Container77,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container__Maintenance__Container71 = lv_obj_create(ui_Container__Maintenance__Container77);
    lv_obj_remove_style_all(ui_Container__Maintenance__Container71);
    lv_obj_set_height(ui_Container__Maintenance__Container71, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Maintenance__Container71, 1);
    lv_obj_set_align(ui_Container__Maintenance__Container71, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Maintenance__Container71,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container__Maintenance__Container87 = lv_obj_create(ui_Container__Maintenance__Container71);
    lv_obj_remove_style_all(ui_Container__Maintenance__Container87);
    lv_obj_set_width(ui_Container__Maintenance__Container87, lv_pct(100));
    lv_obj_set_height(ui_Container__Maintenance__Container87, lv_pct(100));
    lv_obj_set_align(ui_Container__Maintenance__Container87, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Maintenance__Container87, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Maintenance__Container87, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Maintenance__Container87,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container__Maintenance__Container87, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Maintenance__Container87, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Maintenance__Container87, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Maintenance__Container87, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Maintenance__Container87, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Maintenance__Container87, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label__Maintenance__Label37 = lv_label_create(ui_Container__Maintenance__Container87);
    lv_obj_set_width(ui_Label__Maintenance__Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Maintenance__Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label__Maintenance__Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label__Maintenance__Label37, "Run Time");
    ui_object_set_themeable_style_property(ui_Label__Maintenance__Label37, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Label__Maintenance__Label37, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(ui_Label__Maintenance__Label37, &ui_font_P3_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label__Maintenance__Label33 = lv_label_create(ui_Container__Maintenance__Container87);
    lv_obj_set_width(ui_Label__Maintenance__Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Maintenance__Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label__Maintenance__Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label__Maintenance__Label33, "40 Hrs");
    ui_object_set_themeable_style_property(ui_Label__Maintenance__Label33, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Label__Maintenance__Label33, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(ui_Label__Maintenance__Label33, &ui_font_P2_SBold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Maintenance__Container72 = lv_obj_create(ui_Container__Maintenance__Container77);
    lv_obj_remove_style_all(ui_Container__Maintenance__Container72);
    lv_obj_set_height(ui_Container__Maintenance__Container72, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Maintenance__Container72, 1);
    lv_obj_set_align(ui_Container__Maintenance__Container72, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Maintenance__Container72,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container__Maintenance__Container72, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Maintenance__Container72, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Maintenance__Container72, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Maintenance__Container72, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Secondarybtn__Maintenance__Select_Options10 = ui_Button____Secondarybtn_create(
                                                         ui_Container__Maintenance__Container72);
    lv_obj_set_width(ui_Secondarybtn__Maintenance__Select_Options10, 177);
    lv_obj_set_height(ui_Secondarybtn__Maintenance__Select_Options10, 54);
    lv_obj_set_x(ui_Secondarybtn__Maintenance__Select_Options10, 0);
    lv_obj_set_y(ui_Secondarybtn__Maintenance__Select_Options10, 0);
    lv_obj_set_style_min_height(ui_Secondarybtn__Maintenance__Select_Options10, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_height(ui_Secondarybtn__Maintenance__Select_Options10, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_width(ui_comp_get_child(ui_Secondarybtn__Maintenance__Select_Options10,
                                       UI_COMP_BUTTON____SECONDARYBTN_LABEL____LABEL), LV_SIZE_CONTENT);  /// 100
    lv_obj_set_height(ui_comp_get_child(ui_Secondarybtn__Maintenance__Select_Options10,
                                        UI_COMP_BUTTON____SECONDARYBTN_LABEL____LABEL), LV_SIZE_CONTENT);   /// 100
    lv_label_set_text(ui_comp_get_child(ui_Secondarybtn__Maintenance__Select_Options10,
                                        UI_COMP_BUTTON____SECONDARYBTN_LABEL____LABEL), "Reset");

    ui_Container__Maintenance__Container80 = lv_obj_create(ui_Container__Maintenance__Container68);
    lv_obj_remove_style_all(ui_Container__Maintenance__Container80);
    lv_obj_set_height(ui_Container__Maintenance__Container80, 120);
    lv_obj_set_width(ui_Container__Maintenance__Container80, lv_pct(100));
    lv_obj_set_x(ui_Container__Maintenance__Container80, -1);
    lv_obj_set_y(ui_Container__Maintenance__Container80, -12);
    lv_obj_set_align(ui_Container__Maintenance__Container80, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Maintenance__Container80, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Maintenance__Container80, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Maintenance__Container80,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container__Maintenance__Container80, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Maintenance__Container80, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Maintenance__Container80, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Maintenance__Container80, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Primarybtn__Maintenance__Next6 = ui_Button____Primarybtn_create(ui_Container__Maintenance__Container80);
    lv_obj_set_width(ui_Primarybtn__Maintenance__Next6, 180);
    lv_obj_set_height(ui_Primarybtn__Maintenance__Next6, 74);
    lv_obj_set_x(ui_Primarybtn__Maintenance__Next6, 0);
    lv_obj_set_y(ui_Primarybtn__Maintenance__Next6, 0);
    lv_obj_set_align(ui_Primarybtn__Maintenance__Next6, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_pad_left(ui_Primarybtn__Maintenance__Next6, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Primarybtn__Maintenance__Next6, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Primarybtn__Maintenance__Next6, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Primarybtn__Maintenance__Next6, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_label_set_text(ui_comp_get_child(ui_Primarybtn__Maintenance__Next6, UI_COMP_BUTTON____PRIMARYBTN_LABEL____LABEL),
                      "Zero Press\nTransducer");
    lv_obj_set_style_text_align(ui_comp_get_child(ui_Primarybtn__Maintenance__Next6,
                                                  UI_COMP_BUTTON____PRIMARYBTN_LABEL____LABEL), LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Primarybtn__Maintenance__Next7 = ui_Button____Primarybtn_create(ui_Container__Maintenance__Container80);
    lv_obj_set_width(ui_Primarybtn__Maintenance__Next7, 180);
    lv_obj_set_height(ui_Primarybtn__Maintenance__Next7, 74);
    lv_obj_set_x(ui_Primarybtn__Maintenance__Next7, 0);
    lv_obj_set_y(ui_Primarybtn__Maintenance__Next7, 0);
    lv_obj_set_align(ui_Primarybtn__Maintenance__Next7, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_pad_left(ui_Primarybtn__Maintenance__Next7, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Primarybtn__Maintenance__Next7, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Primarybtn__Maintenance__Next7, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Primarybtn__Maintenance__Next7, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_label_set_text(ui_comp_get_child(ui_Primarybtn__Maintenance__Next7, UI_COMP_BUTTON____PRIMARYBTN_LABEL____LABEL),
                      "Home\nPosition");
    lv_obj_set_style_text_align(ui_comp_get_child(ui_Primarybtn__Maintenance__Next7,
                                                  UI_COMP_BUTTON____PRIMARYBTN_LABEL____LABEL), LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Maintenance__Footer5 = lv_obj_create(ui_Container__Maintenance__Container66);
    lv_obj_remove_style_all(ui_Container__Maintenance__Footer5);
    lv_obj_set_height(ui_Container__Maintenance__Footer5, 34);
    lv_obj_set_width(ui_Container__Maintenance__Footer5, lv_pct(100));
    lv_obj_set_align(ui_Container__Maintenance__Footer5, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Container__Maintenance__Footer5, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_remove_flag(ui_Container__Maintenance__Footer5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Container__Maintenance__Footer5, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Container__Maintenance__Footer5, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Dark_blue);

    ui_Label__Maintenance__Label45 = lv_label_create(ui_Container__Maintenance__Footer5);
    lv_obj_set_width(ui_Label__Maintenance__Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Maintenance__Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label__Maintenance__Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label__Maintenance__Label45, "Visit eldex.com/support for manuals and help");
    ui_object_set_themeable_style_property(ui_Label__Maintenance__Label45, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Interface);
    ui_object_set_themeable_style_property(ui_Label__Maintenance__Label45, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Interface);
    lv_obj_set_style_text_font(ui_Label__Maintenance__Label45, &ui_font_P3_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardL__Maintenance__KeyboardMainL1 = ui_Keyboard____KeyboardL_create(ui_Screen__Maintenance);
    lv_keyboard_set_mode(ui_KeyboardL__Maintenance__KeyboardMainL1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KeyboardL__Maintenance__KeyboardMainL1, 529);
    lv_obj_set_height(ui_KeyboardL__Maintenance__KeyboardMainL1, lv_pct(89));
    lv_obj_set_x(ui_KeyboardL__Maintenance__KeyboardMainL1, 0);
    lv_obj_set_y(ui_KeyboardL__Maintenance__KeyboardMainL1, 0);
    lv_obj_add_flag(ui_KeyboardL__Maintenance__KeyboardMainL1,
                    LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags

    ui_KeyboardL__Maintenance__KeyboardMainL5 = ui_Keyboard____KeyboardL_create(ui_Screen__Maintenance);
    lv_keyboard_set_mode(ui_KeyboardL__Maintenance__KeyboardMainL5, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KeyboardL__Maintenance__KeyboardMainL5, 486);
    lv_obj_set_height(ui_KeyboardL__Maintenance__KeyboardMainL5, lv_pct(89));
    lv_obj_set_x(ui_KeyboardL__Maintenance__KeyboardMainL5, 0);
    lv_obj_set_y(ui_KeyboardL__Maintenance__KeyboardMainL5, 0);
    lv_obj_set_align(ui_KeyboardL__Maintenance__KeyboardMainL5, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_KeyboardL__Maintenance__KeyboardMainL5,
                    LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags

    lv_obj_add_event_cb(ui_comp_get_child(ui_Header__Maintenance__Header6,
                                          UI_COMP_CONTAINER____HEADER_BUTTON____BACK_BUTTON), ui_event_Header__Maintenance__Header6_Button____Back_Button,
                        LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input__Maintenance__Input9, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                        ui_event_Input__Maintenance__Input9_Textarea__Maintenance__Input9_TextAreaSN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input__Maintenance__Input10, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                        ui_event_Input__Maintenance__Input10_Textarea__Maintenance__Input10_TextAreaMN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input__Maintenance__Input11, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                        ui_event_Input__Maintenance__Input11_Textarea__Maintenance__Input11_TextAreaFW, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input__Maintenance__Input12, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                        ui_event_Input__Maintenance__Input12_Textarea__Maintenance__Input12_TextAreaGUI, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input__Maintenance__Input13, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                        ui_event_Input__Maintenance__Input13_Textarea__Maintenance__Input13_TextAreaTR, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input__Maintenance__Input8, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                        ui_event_Input__Maintenance__Input8_Textarea__Maintenance__Input8_TextArea_Reminder, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardL__Maintenance__KeyboardMainL1, ui_comp_get_child(ui_Input__Maintenance__Input8,
                                                                                          UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1));
    lv_obj_add_event_cb(ui_KeyboardL__Maintenance__KeyboardMainL1,
                        ui_event_KeyboardL__Maintenance__KeyboardMainL1_Keyboard____KeyboardL, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KeyboardL__Maintenance__KeyboardMainL5,
                        ui_event_KeyboardL__Maintenance__KeyboardMainL5_Keyboard____KeyboardL, LV_EVENT_ALL, NULL);
    ui_Button__Maintenance__Back = ui_comp_get_child(ui_Header__Maintenance__Header6,
                                                     UI_COMP_CONTAINER____HEADER_BUTTON____BACK_BUTTON);
    ui_Image__Maintenance__USB_Status = ui_comp_get_child(ui_Header__Maintenance__Header6,
                                                          UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____USB);
    ui_Image__Maintenance__Ethernet_Status = ui_comp_get_child(ui_Header__Maintenance__Header6,
                                                               UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____ETHERNET);
    ui_Image__Maintenance__WiFi_Status = ui_comp_get_child(ui_Header__Maintenance__Header6,
                                                           UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____WIFI);
    ui_Textarea__Maintenance__SerialNumber = ui_comp_get_child(ui_Input__Maintenance__Input9,
                                                               UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1);
    ui_Textarea__Maintenance__ModelNumber = ui_comp_get_child(ui_Input__Maintenance__Input10,
                                                              UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1);
    ui_Textarea__Maintenance__FirmwareVersion = ui_comp_get_child(ui_Input__Maintenance__Input11,
                                                                  UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1);
    ui_Textarea__Maintenance__GUIversion = ui_comp_get_child(ui_Input__Maintenance__Input12,
                                                             UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1);
    ui_Textarea__Maintenance__Pump1_TotalRun = ui_comp_get_child(ui_Input__Maintenance__Input13,
                                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1);
    ui_Button__Maintenance__Washport_Rinse = ui_Secondarybtn__Maintenance__Select_Options9;
    ui_Switch__Maintenance__Washport_Auto = ui_comp_get_child(ui_Switch__Maintenance__Switch4,
                                                              UI_COMP_CONTAINER____SWITCH_SWITCH____SWITCH3);
    ui_Button__Maintenance__Pump1 = ui_TabButton__Maintenance__TabButton13;
    ui_Button__Maintenance__Pump2 = ui_TabButton__Maintenance__TabButton14;
    ui_Button__Maintenance__Pump3 = ui_TabButton__Maintenance__TabButton15;
    ui_Roller__Maintenance__PumpPart = ui_comp_get_child(ui_RollerSmall__Maintenance__RollerSmall5,
                                                         UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER);
    ui_Textarea__Maintenance__PumpPart_RuntimeReminder_Period = ui_comp_get_child(ui_Input__Maintenance__Input8,
                                                                                  UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1);
    ui_Label__Maintenance__PumpPart_Runtime = ui_Label__Maintenance__Label33;
    ui_Button__Maintenance__Reset_PumpPart_Runtime = ui_Secondarybtn__Maintenance__Select_Options10;
    ui_Button__Maintenance__ZeroPressure_Transducer = ui_Primarybtn__Maintenance__Next6;
    ui_Button__Maintenance__Sensor_MoveMotorsHome = ui_Primarybtn__Maintenance__Next7;
    ui_Label__Maintenance__StatusFooter = ui_Label__Maintenance__Label45;
    ui_Keyboard__Maintenance__PumpPart_RuntimeReminderPeriod_Entry = ui_KeyboardL__Maintenance__KeyboardMainL1;
    ui_Keyboard__Maintenance__LeftSideFields_Entry = ui_KeyboardL__Maintenance__KeyboardMainL5;

}
