// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "../ui.h"

void ui_Screen__StartupSplash_screen_init(void)
{
    ui_Screen__StartupSplash = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen__StartupSplash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Screen__StartupSplash, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Screen__StartupSplash, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Dark_blue);

    ui_Image__StartupSplash__LogoVideo = lv_image_create(ui_Screen__StartupSplash);
    lv_image_set_src(ui_Image__StartupSplash__LogoVideo, ui_img_1103707581);
    lv_obj_set_width(ui_Image__StartupSplash__LogoVideo, lv_pct(100));
    lv_obj_set_height(ui_Image__StartupSplash__LogoVideo, lv_pct(100));
    lv_obj_set_align(ui_Image__StartupSplash__LogoVideo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image__StartupSplash__LogoVideo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image__StartupSplash__LogoVideo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label__StartupSplash__FirwareVersion = lv_label_create(ui_Screen__StartupSplash);
    lv_obj_set_width(ui_Label__StartupSplash__FirwareVersion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__StartupSplash__FirwareVersion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label__StartupSplash__FirwareVersion, 0);
    lv_obj_set_y(ui_Label__StartupSplash__FirwareVersion, 116);
    lv_obj_set_align(ui_Label__StartupSplash__FirwareVersion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label__StartupSplash__FirwareVersion, "Firmware vXX.XX");
    ui_object_set_themeable_style_property(ui_Label__StartupSplash__FirwareVersion, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_White);
    ui_object_set_themeable_style_property(ui_Label__StartupSplash__FirwareVersion, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_White);
    lv_obj_set_style_text_font(ui_Label__StartupSplash__FirwareVersion, &ui_font_P3_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label__StartupSplash__GUIversion = lv_label_create(ui_Screen__StartupSplash);
    lv_obj_set_width(ui_Label__StartupSplash__GUIversion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__StartupSplash__GUIversion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label__StartupSplash__GUIversion, 0);
    lv_obj_set_y(ui_Label__StartupSplash__GUIversion, 151);
    lv_obj_set_align(ui_Label__StartupSplash__GUIversion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label__StartupSplash__GUIversion, "GUI vXX.XX");
    ui_object_set_themeable_style_property(ui_Label__StartupSplash__GUIversion, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_White);
    ui_object_set_themeable_style_property(ui_Label__StartupSplash__GUIversion, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_White);
    lv_obj_set_style_text_font(ui_Label__StartupSplash__GUIversion, &ui_font_P3_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen__StartupSplash, ui_event_Screen__StartupSplash, LV_EVENT_ALL, NULL);

}
