// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "../ui.h"

void ui_Screen__Pump_Settings_screen_init(void)
{
    ui_Screen__Pump_Settings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen__Pump_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Screen__Pump_Settings, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screen__Pump_Settings, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    ui_object_set_themeable_style_property(ui_Screen__Pump_Settings, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Bg_);
    ui_object_set_themeable_style_property(ui_Screen__Pump_Settings, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Bg_);
    lv_obj_set_style_pad_left(ui_Screen__Pump_Settings, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Screen__Pump_Settings, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Screen__Pump_Settings, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Screen__Pump_Settings, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Screen__Pump_Settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Screen__Pump_Settings, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Pump_Settings__Container37 = lv_obj_create(ui_Screen__Pump_Settings);
    lv_obj_remove_style_all(ui_Container__Pump_Settings__Container37);
    lv_obj_set_width(ui_Container__Pump_Settings__Container37, 100);
    lv_obj_set_height(ui_Container__Pump_Settings__Container37, lv_pct(100));
    lv_obj_set_align(ui_Container__Pump_Settings__Container37, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Pump_Settings__Container37, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Pump_Settings__Container37, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Pump_Settings__Container37,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container__Pump_Settings__Container37, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Pump_Settings__Container37, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Pump_Settings__Container37, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Pump_Settings__Container37, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Pump_Settings__Container37, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Pump_Settings__Container37, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image__Pump_Settings__Logo3 = lv_image_create(ui_Container__Pump_Settings__Container37);
    lv_image_set_src(ui_Image__Pump_Settings__Logo3, ui_img_logo_png);
    lv_obj_set_width(ui_Image__Pump_Settings__Logo3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image__Pump_Settings__Logo3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image__Pump_Settings__Logo3, 0);
    lv_obj_set_y(ui_Image__Pump_Settings__Logo3, 6);
    lv_obj_set_align(ui_Image__Pump_Settings__Logo3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image__Pump_Settings__Logo3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image__Pump_Settings__Logo3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Menu__Pump_Settings__Menu2 = ui_Container____Menu_create(ui_Container__Pump_Settings__Container37);
    lv_obj_set_x(ui_Menu__Pump_Settings__Menu2, 0);
    lv_obj_set_y(ui_Menu__Pump_Settings__Menu2, 0);



    lv_obj_add_state(ui_comp_get_child(ui_Menu__Pump_Settings__Menu2,
                                       UI_COMP_CONTAINER____MENU_MENUBUTTON____MENU_BUTTON_PUMP), LV_STATE_CHECKED);      /// States

    lv_obj_add_state(ui_comp_get_child(ui_Menu__Pump_Settings__Menu2,
                                       UI_COMP_CONTAINER____MENU_MENUBUTTON____MENU_BUTTON_PUMP_IMAGE____MENU_BUTTON_PUMP_ICON),
                     LV_STATE_CHECKED);      /// States



    ui_Container__Pump_Settings__Container39 = lv_obj_create(ui_Screen__Pump_Settings);
    lv_obj_remove_style_all(ui_Container__Pump_Settings__Container39);
    lv_obj_set_height(ui_Container__Pump_Settings__Container39, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Pump_Settings__Container39, 1);
    lv_obj_set_align(ui_Container__Pump_Settings__Container39, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Pump_Settings__Container39, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Pump_Settings__Container39, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Pump_Settings__Container39,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container__Pump_Settings__Container39, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Container__Pump_Settings__Container39, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Pump_Settings__Container39, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Pump_Settings__Container39, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Header__Pump_Settings__Header3 = ui_Container____Header_create(ui_Container__Pump_Settings__Container39);
    lv_obj_set_x(ui_Header__Pump_Settings__Header3, 0);
    lv_obj_set_y(ui_Header__Pump_Settings__Header3, 0);



    lv_label_set_text(ui_comp_get_child(ui_Header__Pump_Settings__Header3, UI_COMP_CONTAINER____HEADER_LABEL____TITLE),
                      "Pump Settings");



    lv_obj_add_flag(ui_comp_get_child(ui_Header__Pump_Settings__Header3,
                                      UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____USB), LV_OBJ_FLAG_HIDDEN);    /// Flags

    lv_obj_add_flag(ui_comp_get_child(ui_Header__Pump_Settings__Header3,
                                      UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____ETHERNET), LV_OBJ_FLAG_HIDDEN);    /// Flags

    lv_obj_add_flag(ui_comp_get_child(ui_Header__Pump_Settings__Header3,
                                      UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____WIFI), LV_OBJ_FLAG_HIDDEN);    /// Flags

    ui_Container__Pump_Settings__Content6 = lv_obj_create(ui_Container__Pump_Settings__Container39);
    lv_obj_remove_style_all(ui_Container__Pump_Settings__Content6);
    lv_obj_set_width(ui_Container__Pump_Settings__Content6, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Pump_Settings__Content6, 1);
    lv_obj_set_align(ui_Container__Pump_Settings__Content6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Pump_Settings__Content6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Pump_Settings__Content6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Pump_Settings__Content6,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container__Pump_Settings__Content6, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Container__Pump_Settings__Content6, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_Container__Pump_Settings__Content6, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_Container__Pump_Settings__Content6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Container__Pump_Settings__Content6, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Pump_Settings__Content6, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Pump_Settings__Content6, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Pump_Settings__Content6, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Pump_Settings__Content6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Pump_Settings__Content6, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Pump_Settings__tab_Initial3 = lv_obj_create(ui_Container__Pump_Settings__Content6);
    lv_obj_remove_style_all(ui_Container__Pump_Settings__tab_Initial3);
    lv_obj_set_width(ui_Container__Pump_Settings__tab_Initial3, lv_pct(100));
    lv_obj_set_height(ui_Container__Pump_Settings__tab_Initial3, lv_pct(100));
    lv_obj_set_align(ui_Container__Pump_Settings__tab_Initial3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Pump_Settings__tab_Initial3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Pump_Settings__tab_Initial3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Pump_Settings__tab_Initial3,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container__Pump_Settings__tab_Initial3, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Pump_Settings__tab_Initial3, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Pump_Settings__Container40 = lv_obj_create(ui_Container__Pump_Settings__tab_Initial3);
    lv_obj_remove_style_all(ui_Container__Pump_Settings__Container40);
    lv_obj_set_width(ui_Container__Pump_Settings__Container40, lv_pct(100));
    lv_obj_set_height(ui_Container__Pump_Settings__Container40, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Container__Pump_Settings__Container40, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Pump_Settings__Container40, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Pump_Settings__Container40, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Pump_Settings__Container40,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container__Pump_Settings__Container40, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Pump_Settings__Container40, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabButton__Pump_Settings__TabButton10 = ui_Button____TabButton_create(ui_Container__Pump_Settings__Container40);
    lv_obj_set_height(ui_TabButton__Pump_Settings__TabButton10, 36);
    lv_obj_set_flex_grow(ui_TabButton__Pump_Settings__TabButton10, 1);
    lv_obj_set_x(ui_TabButton__Pump_Settings__TabButton10, 0);
    lv_obj_set_y(ui_TabButton__Pump_Settings__TabButton10, 0);
    lv_obj_add_state(ui_TabButton__Pump_Settings__TabButton10, LV_STATE_CHECKED);       /// States

    lv_label_set_text(ui_comp_get_child(ui_TabButton__Pump_Settings__TabButton10,
                                        UI_COMP_BUTTON____TABBUTTON_LABEL____LABEL), "Pump 1");

    ui_TabButton__Pump_Settings__TabButton11 = ui_Button____TabButton_create(ui_Container__Pump_Settings__Container40);
    lv_obj_set_height(ui_TabButton__Pump_Settings__TabButton11, 36);
    lv_obj_set_flex_grow(ui_TabButton__Pump_Settings__TabButton11, 1);
    lv_obj_set_x(ui_TabButton__Pump_Settings__TabButton11, 0);
    lv_obj_set_y(ui_TabButton__Pump_Settings__TabButton11, 0);
    lv_obj_remove_state(ui_TabButton__Pump_Settings__TabButton11, LV_STATE_CHECKED);     /// States

    lv_label_set_text(ui_comp_get_child(ui_TabButton__Pump_Settings__TabButton11,
                                        UI_COMP_BUTTON____TABBUTTON_LABEL____LABEL), "Pump 2");

    ui_TabButton__Pump_Settings__TabButton12 = ui_Button____TabButton_create(ui_Container__Pump_Settings__Container40);
    lv_obj_set_height(ui_TabButton__Pump_Settings__TabButton12, 36);
    lv_obj_set_flex_grow(ui_TabButton__Pump_Settings__TabButton12, 1);
    lv_obj_set_x(ui_TabButton__Pump_Settings__TabButton12, 0);
    lv_obj_set_y(ui_TabButton__Pump_Settings__TabButton12, 0);
    lv_obj_remove_state(ui_TabButton__Pump_Settings__TabButton12, LV_STATE_CHECKED);     /// States

    lv_label_set_text(ui_comp_get_child(ui_TabButton__Pump_Settings__TabButton12,
                                        UI_COMP_BUTTON____TABBUTTON_LABEL____LABEL), "Pump 3");

    ui_Container__Pump_Settings__Container41 = lv_obj_create(ui_Container__Pump_Settings__tab_Initial3);
    lv_obj_remove_style_all(ui_Container__Pump_Settings__Container41);
    lv_obj_set_width(ui_Container__Pump_Settings__Container41, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Pump_Settings__Container41, 1);
    lv_obj_set_align(ui_Container__Pump_Settings__Container41, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Pump_Settings__Container41, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Pump_Settings__Container41, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Pump_Settings__Container41,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container__Pump_Settings__Container42 = lv_obj_create(ui_Container__Pump_Settings__Container41);
    lv_obj_remove_style_all(ui_Container__Pump_Settings__Container42);
    lv_obj_set_width(ui_Container__Pump_Settings__Container42, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Pump_Settings__Container42, 2);
    lv_obj_set_align(ui_Container__Pump_Settings__Container42, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Pump_Settings__Container42, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Pump_Settings__Container42, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Pump_Settings__Container42,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container__Pump_Settings__Container42, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Container__Pump_Settings__Container42, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_White);
    ui_object_set_themeable_style_property(ui_Container__Pump_Settings__Container42, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_White);

    ui_Container__Pump_Settings__Container43 = lv_obj_create(ui_Container__Pump_Settings__Container42);
    lv_obj_remove_style_all(ui_Container__Pump_Settings__Container43);
    lv_obj_set_height(ui_Container__Pump_Settings__Container43, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Pump_Settings__Container43, 1);
    lv_obj_set_align(ui_Container__Pump_Settings__Container43, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Pump_Settings__Container43, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Pump_Settings__Container43, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Pump_Settings__Container43,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container__Pump_Settings__Container43, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Pump_Settings__Container43, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Pump_Settings__Container43, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Pump_Settings__Container43, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Pump_Settings__Container44 = lv_obj_create(ui_Container__Pump_Settings__Container43);
    lv_obj_remove_style_all(ui_Container__Pump_Settings__Container44);
    lv_obj_set_height(ui_Container__Pump_Settings__Container44, lv_pct(100));
    lv_obj_set_width(ui_Container__Pump_Settings__Container44, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_align(ui_Container__Pump_Settings__Container44, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Pump_Settings__Container44, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Pump_Settings__Container44, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Pump_Settings__Container44,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Container__Pump_Settings__Container44, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_Container__Pump_Settings__Container44, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_Container__Pump_Settings__Container44, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container__Pump_Settings__Container44, LV_BORDER_SIDE_RIGHT,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Container__Pump_Settings__Container44, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Pump_Settings__Container44, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Pump_Settings__Container44, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Pump_Settings__Container44, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Pump_Settings__Container44, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Pump_Settings__Container44, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch__Pump_Settings__Switch = ui_Container____Switch_create(ui_Container__Pump_Settings__Container44);
    lv_obj_set_width(ui_Switch__Pump_Settings__Switch, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_flex_grow(ui_Switch__Pump_Settings__Switch, 1);
    lv_obj_set_x(ui_Switch__Pump_Settings__Switch, 0);
    lv_obj_set_y(ui_Switch__Pump_Settings__Switch, 0);




    ui_Switch__Pump_Settings__Switch1 = ui_Container____Switch_create(ui_Container__Pump_Settings__Container44);
    lv_obj_set_width(ui_Switch__Pump_Settings__Switch1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_flex_grow(ui_Switch__Pump_Settings__Switch1, 1);
    lv_obj_set_x(ui_Switch__Pump_Settings__Switch1, 0);
    lv_obj_set_y(ui_Switch__Pump_Settings__Switch1, 0);

    lv_label_set_text(ui_comp_get_child(ui_Switch__Pump_Settings__Switch1, UI_COMP_CONTAINER____SWITCH_LABEL____LABEL23),
                      "Stop on Stall");



    ui_Container__Pump_Settings__Container47 = lv_obj_create(ui_Container__Pump_Settings__Container43);
    lv_obj_remove_style_all(ui_Container__Pump_Settings__Container47);
    lv_obj_set_height(ui_Container__Pump_Settings__Container47, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Pump_Settings__Container47, 1);
    lv_obj_set_align(ui_Container__Pump_Settings__Container47, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Pump_Settings__Container47, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Pump_Settings__Container47, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Pump_Settings__Container47,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container__Pump_Settings__Container47, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Pump_Settings__Container47, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Pump_Settings__Container47, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Pump_Settings__Container47, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Pump_Settings__Container47, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Pump_Settings__Container47, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown__Pump_Settings__Dropdown1 = ui_Container____Dropdown_create(ui_Container__Pump_Settings__Container47);
    lv_obj_set_width(ui_Dropdown__Pump_Settings__Dropdown1, lv_pct(100));
    lv_obj_set_height(ui_Dropdown__Pump_Settings__Dropdown1, LV_SIZE_CONTENT);    /// 86
    lv_obj_set_x(ui_Dropdown__Pump_Settings__Dropdown1, 0);
    lv_obj_set_y(ui_Dropdown__Pump_Settings__Dropdown1, 0);



    lv_label_set_text(ui_comp_get_child(ui_Dropdown__Pump_Settings__Dropdown1,
                                        UI_COMP_CONTAINER____DROPDOWN_CONTAINER____LABEL_GROUP_LABEL____TITLE), "Select Mode");

    lv_dropdown_set_options(ui_comp_get_child(ui_Dropdown__Pump_Settings__Dropdown1,
                                              UI_COMP_CONTAINER____DROPDOWN_DROPDOWN____DROP),
                            "Synchronization Mode\nPump Dispense Mode\nSet Refill OutPut Ratio\nError Delay\nSet Voltage Out");



    ui_Dropdown__Pump_Settings__Dropdown2 = ui_Container____Dropdown_create(ui_Container__Pump_Settings__Container47);
    lv_obj_set_width(ui_Dropdown__Pump_Settings__Dropdown2, lv_pct(100));
    lv_obj_set_height(ui_Dropdown__Pump_Settings__Dropdown2, LV_SIZE_CONTENT);    /// 86
    lv_obj_set_x(ui_Dropdown__Pump_Settings__Dropdown2, 0);
    lv_obj_set_y(ui_Dropdown__Pump_Settings__Dropdown2, 0);



    lv_label_set_text(ui_comp_get_child(ui_Dropdown__Pump_Settings__Dropdown2,
                                        UI_COMP_CONTAINER____DROPDOWN_CONTAINER____LABEL_GROUP_LABEL____TITLE), "Select Parameter");

    lv_dropdown_set_options(ui_comp_get_child(ui_Dropdown__Pump_Settings__Dropdown2,
                                              UI_COMP_CONTAINER____DROPDOWN_DROPDOWN____DROP),
                            "Flow\nPressure\nDispense\nNo synchronization\n1 and 2 synchronized\n1 and 3 synchronized\nAll synchronized\nNo synchronization\nsynchronized\nFull Out\n15/ 85\n30/ 70\n50/ 50\n70/ 30\n0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\nFlow\nPressure\n");



    ui_Container__Pump_Settings__Container49 = lv_obj_create(ui_Container__Pump_Settings__Container41);
    lv_obj_remove_style_all(ui_Container__Pump_Settings__Container49);
    lv_obj_set_height(ui_Container__Pump_Settings__Container49, 92);
    lv_obj_set_width(ui_Container__Pump_Settings__Container49, lv_pct(100));
    lv_obj_set_x(ui_Container__Pump_Settings__Container49, -1);
    lv_obj_set_y(ui_Container__Pump_Settings__Container49, -12);
    lv_obj_set_align(ui_Container__Pump_Settings__Container49, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Pump_Settings__Container49, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Pump_Settings__Container49, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Pump_Settings__Container49,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container__Pump_Settings__Container49, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Pump_Settings__Container49, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Pump_Settings__Container49, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Pump_Settings__Container49, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Pump_Settings__Container49, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Pump_Settings__Container49, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Pump_Settings__Container45 = lv_obj_create(ui_Container__Pump_Settings__Container49);
    lv_obj_remove_style_all(ui_Container__Pump_Settings__Container45);
    lv_obj_set_width(ui_Container__Pump_Settings__Container45, lv_pct(100));
    lv_obj_set_height(ui_Container__Pump_Settings__Container45, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_align(ui_Container__Pump_Settings__Container45, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Pump_Settings__Container45,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label__Pump_Settings__Label25 = lv_label_create(ui_Container__Pump_Settings__Container45);
    lv_obj_set_width(ui_Label__Pump_Settings__Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Pump_Settings__Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label__Pump_Settings__Label25, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label__Pump_Settings__Label25, "Adjust Compressibility Compensation");
    ui_object_set_themeable_style_property(ui_Label__Pump_Settings__Label25, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Label__Pump_Settings__Label25, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(ui_Label__Pump_Settings__Label25, &ui_font_P3_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label__Pump_Settings__Label24 = lv_label_create(ui_Container__Pump_Settings__Container45);
    lv_obj_set_width(ui_Label__Pump_Settings__Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Pump_Settings__Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label__Pump_Settings__Label24, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label__Pump_Settings__Label24, "52%");
    ui_object_set_themeable_style_property(ui_Label__Pump_Settings__Label24, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Label__Pump_Settings__Label24, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(ui_Label__Pump_Settings__Label24, &ui_font_P2_SBold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider__Pump_Settings__Slider1 = lv_slider_create(ui_Container__Pump_Settings__Container49);
    lv_slider_set_value(ui_Slider__Pump_Settings__Slider1, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider__Pump_Settings__Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_Slider__Pump_Settings__Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_Slider__Pump_Settings__Slider1, 14);
    lv_obj_set_width(ui_Slider__Pump_Settings__Slider1, lv_pct(100));
    lv_obj_set_align(ui_Slider__Pump_Settings__Slider1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Slider__Pump_Settings__Slider1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Slider__Pump_Settings__Slider1, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Disabled);
    ui_object_set_themeable_style_property(ui_Slider__Pump_Settings__Slider1, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Disabled);

    ui_object_set_themeable_style_property(ui_Slider__Pump_Settings__Slider1, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_Slider__Pump_Settings__Slider1, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Blue);

    lv_obj_set_style_radius(ui_Slider__Pump_Settings__Slider1, 20, LV_PART_KNOB | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Slider__Pump_Settings__Slider1, LV_PART_KNOB | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_White);
    ui_object_set_themeable_style_property(ui_Slider__Pump_Settings__Slider1, LV_PART_KNOB | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_White);
    ui_object_set_themeable_style_property(ui_Slider__Pump_Settings__Slider1, LV_PART_KNOB | LV_STATE_DEFAULT,
                                           LV_STYLE_SHADOW_COLOR, _ui_theme_color_Shadow);
    ui_object_set_themeable_style_property(ui_Slider__Pump_Settings__Slider1, LV_PART_KNOB | LV_STATE_DEFAULT,
                                           LV_STYLE_SHADOW_OPA, _ui_theme_alpha_Shadow);
    lv_obj_set_style_shadow_width(ui_Slider__Pump_Settings__Slider1, 24, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Slider__Pump_Settings__Slider1, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Slider__Pump_Settings__Slider1, 8, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Slider__Pump_Settings__Slider1, 8, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Slider__Pump_Settings__Slider1, 8, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Slider__Pump_Settings__Slider1, 8, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider__Pump_Settings__Slider1,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider__Pump_Settings__Slider1,
                                                                                  lv_obj_get_style_pad_right(ui_Slider__Pump_Settings__Slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Container__Pump_Settings__Footer2 = lv_obj_create(ui_Container__Pump_Settings__Container39);
    lv_obj_remove_style_all(ui_Container__Pump_Settings__Footer2);
    lv_obj_set_height(ui_Container__Pump_Settings__Footer2, 34);
    lv_obj_set_width(ui_Container__Pump_Settings__Footer2, lv_pct(100));
    lv_obj_set_align(ui_Container__Pump_Settings__Footer2, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Container__Pump_Settings__Footer2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Pump_Settings__Footer2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Container__Pump_Settings__Footer2, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_remove_flag(ui_Container__Pump_Settings__Footer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Container__Pump_Settings__Footer2, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Container__Pump_Settings__Footer2, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Dark_blue);

    ui_Label__Pump_Settings__Label32 = lv_label_create(ui_Container__Pump_Settings__Footer2);
    lv_obj_set_width(ui_Label__Pump_Settings__Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Pump_Settings__Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label__Pump_Settings__Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label__Pump_Settings__Label32, "Visit eldex.com/support for manuals and help");
    ui_object_set_themeable_style_property(ui_Label__Pump_Settings__Label32, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Interface);
    ui_object_set_themeable_style_property(ui_Label__Pump_Settings__Label32, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Interface);
    lv_obj_set_style_text_font(ui_Label__Pump_Settings__Label32, &ui_font_P3_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_comp_get_child(ui_Menu__Pump_Settings__Menu2,
                                          UI_COMP_CONTAINER____MENU_MENUBUTTON____MENU_BUTTON_HOME),
                        ui_event_Menu__Pump_Settings__Menu2_MenuButton____Menu_Button_Home, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Menu__Pump_Settings__Menu2,
                                          UI_COMP_CONTAINER____MENU_MENUBUTTON____MENU_BUTTON_SETUP),
                        ui_event_Menu__Pump_Settings__Menu2_MenuButton____Menu_Button_Setup, LV_EVENT_ALL, NULL);
    ui_MenuButton__Pump_Settings__Menu = ui_comp_get_child(ui_Menu__Pump_Settings__Menu2,
                                                           UI_COMP_CONTAINER____MENU_MENUBUTTON____MENU_BUTTON_HOME);
    ui_MenuButton__Pump_Settings__Pump = ui_comp_get_child(ui_Menu__Pump_Settings__Menu2,
                                                           UI_COMP_CONTAINER____MENU_MENUBUTTON____MENU_BUTTON_PUMP);
    ui_MenuButton__Pump_Settings__Setup = ui_comp_get_child(ui_Menu__Pump_Settings__Menu2,
                                                            UI_COMP_CONTAINER____MENU_MENUBUTTON____MENU_BUTTON_SETUP);
    ui_Image__Pump_Settings__USB_Status = ui_comp_get_child(ui_Header__Pump_Settings__Header3,
                                                            UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____USB);
    ui_Image__Pump_Settings__Ethernet_Status = ui_comp_get_child(ui_Header__Pump_Settings__Header3,
                                                                 UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____ETHERNET);
    ui_Image__Pump_Settings__WiFi_Status = ui_comp_get_child(ui_Header__Pump_Settings__Header3,
                                                             UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____WIFI);
    ui_Button__Pump_Settings__Pump1 = ui_TabButton__Pump_Settings__TabButton10;
    ui_Button__Pump_Settings__Pump2 = ui_TabButton__Pump_Settings__TabButton11;
    ui_Button__Pump_Settings__Pump3 = ui_TabButton__Pump_Settings__TabButton12;
    ui_Switch__Pump_Settings__RestartOnPowerup = ui_comp_get_child(ui_Switch__Pump_Settings__Switch,
                                                                   UI_COMP_CONTAINER____SWITCH_SWITCH____SWITCH3);
    ui_Switch__Pump_Settings__StopOnStall = ui_comp_get_child(ui_Switch__Pump_Settings__Switch1,
                                                              UI_COMP_CONTAINER____SWITCH_SWITCH____SWITCH3);
    ui_Dropdown__Pump_Settings__Property = ui_comp_get_child(ui_Dropdown__Pump_Settings__Dropdown1,
                                                             UI_COMP_CONTAINER____DROPDOWN_DROPDOWN____DROP);
    ui_Dropdown__Pump_Settings__Value = ui_comp_get_child(ui_Dropdown__Pump_Settings__Dropdown2,
                                                          UI_COMP_CONTAINER____DROPDOWN_DROPDOWN____DROP);
    ui_Label__Pump_Settings__CompressibilityCompensation_Value = ui_Label__Pump_Settings__Label24;
    ui_Slider__Pump_Settings__CompressibilityCompensation_Value = ui_Slider__Pump_Settings__Slider1;
    ui_Label__Pump_Settings__StatusFooter = ui_Label__Pump_Settings__Label32;

}
