// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Eldex_Optos_Touch

#include "../ui.h"

void ui_Screen__Communications_screen_init(void)
{
    ui_Screen__Communications = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen__Communications, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Screen__Communications, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Screen__Communications, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    ui_object_set_themeable_style_property(ui_Screen__Communications, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Bg_);
    ui_object_set_themeable_style_property(ui_Screen__Communications, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Bg_);
    lv_obj_set_style_pad_left(ui_Screen__Communications, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Screen__Communications, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Screen__Communications, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Screen__Communications, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Screen__Communications, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Screen__Communications, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Header__Communications__Header8 = ui_Container____Header_create(ui_Screen__Communications);
    lv_obj_set_x(ui_Header__Communications__Header8, 0);
    lv_obj_set_y(ui_Header__Communications__Header8, 0);

    lv_obj_remove_flag(ui_comp_get_child(ui_Header__Communications__Header8,
                                         UI_COMP_CONTAINER____HEADER_BUTTON____BACK_BUTTON), LV_OBJ_FLAG_HIDDEN);     /// Flags


    lv_label_set_text(ui_comp_get_child(ui_Header__Communications__Header8, UI_COMP_CONTAINER____HEADER_LABEL____TITLE),
                      "Communications");



    lv_obj_add_flag(ui_comp_get_child(ui_Header__Communications__Header8,
                                      UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____USB), LV_OBJ_FLAG_HIDDEN);    /// Flags

    lv_obj_add_flag(ui_comp_get_child(ui_Header__Communications__Header8,
                                      UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____ETHERNET), LV_OBJ_FLAG_HIDDEN);    /// Flags

    lv_obj_add_flag(ui_comp_get_child(ui_Header__Communications__Header8,
                                      UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____WIFI), LV_OBJ_FLAG_HIDDEN);    /// Flags

    ui_Image__Communications__Image7 = lv_image_create(ui_comp_get_child(ui_Header__Communications__Header8,
                                                                         UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS));
    lv_image_set_src(ui_Image__Communications__Image7, ui_img_logo_png);
    lv_obj_set_width(ui_Image__Communications__Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image__Communications__Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image__Communications__Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image__Communications__Image7, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image__Communications__Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container__Communications__Content = lv_obj_create(ui_Screen__Communications);
    lv_obj_remove_style_all(ui_Container__Communications__Content);
    lv_obj_set_width(ui_Container__Communications__Content, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Communications__Content, 1);
    lv_obj_set_align(ui_Container__Communications__Content, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Communications__Content, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Communications__Content, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Communications__Content,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container__Communications__Content, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Container__Communications__Content, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Container__Communications__Content, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_Container__Communications__Content, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_Container__Communications__Content, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Container__Communications__Content, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Communications__Content, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Communications__Content, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Communications__Content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Communications__Content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Communications__Content, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Communications__Container65 = lv_obj_create(ui_Container__Communications__Content);
    lv_obj_remove_style_all(ui_Container__Communications__Container65);
    lv_obj_set_height(ui_Container__Communications__Container65, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Communications__Container65, 1);
    lv_obj_set_align(ui_Container__Communications__Container65, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Communications__Container65, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Communications__Container65, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Communications__Container65,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container__Communications__Container65, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Communications__Container65, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Communications__Container65, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Communications__Container65, 46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Communications__group = lv_obj_create(ui_Container__Communications__Container65);
    lv_obj_remove_style_all(ui_Container__Communications__group);
    lv_obj_set_width(ui_Container__Communications__group, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Communications__group, 1);
    lv_obj_set_align(ui_Container__Communications__group, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Communications__group, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Communications__group, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Communications__group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container__Communications__group, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Communications__group, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Communications__Container83 = lv_obj_create(ui_Container__Communications__group);
    lv_obj_remove_style_all(ui_Container__Communications__Container83);
    lv_obj_set_width(ui_Container__Communications__Container83, lv_pct(100));
    lv_obj_set_height(ui_Container__Communications__Container83, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Container__Communications__Container83, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Communications__Container83, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Communications__Container83, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Communications__Container83,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container__Communications__Container83, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Communications__Container83, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabButton__Communications__TabButton16 = ui_Button____TabButton_create(ui_Container__Communications__Container83);
    lv_obj_set_height(ui_TabButton__Communications__TabButton16, 36);
    lv_obj_set_flex_grow(ui_TabButton__Communications__TabButton16, 1);
    lv_obj_set_x(ui_TabButton__Communications__TabButton16, 0);
    lv_obj_set_y(ui_TabButton__Communications__TabButton16, 0);
    lv_obj_add_state(ui_TabButton__Communications__TabButton16, LV_STATE_CHECKED);       /// States

    lv_label_set_text(ui_comp_get_child(ui_TabButton__Communications__TabButton16,
                                        UI_COMP_BUTTON____TABBUTTON_LABEL____LABEL), "Serial");

    ui_TabButton__Communications__TabButton17 = ui_Button____TabButton_create(ui_Container__Communications__Container83);
    lv_obj_set_height(ui_TabButton__Communications__TabButton17, 36);
    lv_obj_set_flex_grow(ui_TabButton__Communications__TabButton17, 1);
    lv_obj_set_x(ui_TabButton__Communications__TabButton17, 0);
    lv_obj_set_y(ui_TabButton__Communications__TabButton17, 0);
    lv_obj_remove_state(ui_TabButton__Communications__TabButton17, LV_STATE_CHECKED);     /// States

    lv_label_set_text(ui_comp_get_child(ui_TabButton__Communications__TabButton17,
                                        UI_COMP_BUTTON____TABBUTTON_LABEL____LABEL), "Ethernet");

    ui_TabButton__Communications__TabButton18 = ui_Button____TabButton_create(ui_Container__Communications__Container83);
    lv_obj_set_height(ui_TabButton__Communications__TabButton18, 36);
    lv_obj_set_flex_grow(ui_TabButton__Communications__TabButton18, 1);
    lv_obj_set_x(ui_TabButton__Communications__TabButton18, 0);
    lv_obj_set_y(ui_TabButton__Communications__TabButton18, 0);
    lv_obj_remove_state(ui_TabButton__Communications__TabButton18, LV_STATE_CHECKED);     /// States

    lv_label_set_text(ui_comp_get_child(ui_TabButton__Communications__TabButton18,
                                        UI_COMP_BUTTON____TABBUTTON_LABEL____LABEL), "Wi-fi");

    ui_Container__Communications__Serial_Content = lv_obj_create(ui_Container__Communications__group);
    lv_obj_remove_style_all(ui_Container__Communications__Serial_Content);
    lv_obj_set_width(ui_Container__Communications__Serial_Content, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Communications__Serial_Content, 1);
    lv_obj_set_align(ui_Container__Communications__Serial_Content, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Communications__Serial_Content, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Communications__Serial_Content, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Container__Communications__Serial_Content, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Container__Communications__Serial_Content,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container__Communications__Serial_Content, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Container__Communications__Serial_Content, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_White);
    ui_object_set_themeable_style_property(ui_Container__Communications__Serial_Content, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_White);
    lv_obj_set_style_pad_row(ui_Container__Communications__Serial_Content, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Communications__Serial_Content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Communications__Container88 = lv_obj_create(ui_Container__Communications__Serial_Content);
    lv_obj_remove_style_all(ui_Container__Communications__Container88);
    lv_obj_set_width(ui_Container__Communications__Container88, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Communications__Container88, 1);
    lv_obj_set_align(ui_Container__Communications__Container88, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Communications__Container88, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Communications__Container88, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Communications__Container88,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container__Communications__Container88, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Communications__Container88, 34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Communications__Container92 = lv_obj_create(ui_Container__Communications__Container88);
    lv_obj_remove_style_all(ui_Container__Communications__Container92);
    lv_obj_set_width(ui_Container__Communications__Container92, 369);
    lv_obj_set_height(ui_Container__Communications__Container92, lv_pct(100));
    lv_obj_set_x(ui_Container__Communications__Container92, -21);
    lv_obj_set_y(ui_Container__Communications__Container92, 1);
    lv_obj_set_align(ui_Container__Communications__Container92, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Communications__Container92, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Communications__Container92, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Communications__Container92,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel__Communications__Panel3 = lv_obj_create(ui_Container__Communications__Container92);
    lv_obj_set_width(ui_Panel__Communications__Panel3, 62);
    lv_obj_set_height(ui_Panel__Communications__Panel3, 120);
    lv_obj_set_x(ui_Panel__Communications__Panel3, -22);
    lv_obj_set_y(ui_Panel__Communications__Panel3, 0);
    lv_obj_set_align(ui_Panel__Communications__Panel3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel__Communications__Panel3, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_remove_flag(ui_Panel__Communications__Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Panel__Communications__Panel3, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Panel__Communications__Panel3, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Dark_blue);
    ui_object_set_themeable_style_property(ui_Panel__Communications__Panel3, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_GRAD_COLOR, _ui_theme_color_Blue);
    lv_obj_set_style_bg_grad_dir(ui_Panel__Communications__Panel3, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel__Communications__Panel4 = lv_obj_create(ui_Panel__Communications__Panel3);
    lv_obj_set_width(ui_Panel__Communications__Panel4, 100);
    lv_obj_set_height(ui_Panel__Communications__Panel4, 100);
    lv_obj_set_x(ui_Panel__Communications__Panel4, 1);
    lv_obj_set_y(ui_Panel__Communications__Panel4, -85);
    lv_obj_set_align(ui_Panel__Communications__Panel4, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Panel__Communications__Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel__Communications__Panel4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel__Communications__Panel5 = lv_obj_create(ui_Panel__Communications__Panel3);
    lv_obj_set_width(ui_Panel__Communications__Panel5, 100);
    lv_obj_set_height(ui_Panel__Communications__Panel5, 100);
    lv_obj_set_x(ui_Panel__Communications__Panel5, 1);
    lv_obj_set_y(ui_Panel__Communications__Panel5, 85);
    lv_obj_set_align(ui_Panel__Communications__Panel5, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_Panel__Communications__Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel__Communications__Panel5, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerSmall__Communications__RollerSmall11 = ui_Container____RollerSmall_create(
                                                        ui_Container__Communications__Container92);
    lv_obj_set_x(ui_RollerSmall__Communications__RollerSmall11, 0);
    lv_obj_set_y(ui_RollerSmall__Communications__RollerSmall11, 0);

    lv_obj_add_flag(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall11,
                                      UI_COMP_CONTAINER____ROLLERSMALL_LABEL____TITLE), LV_OBJ_FLAG_HIDDEN);    /// Flags

    lv_roller_set_options(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall11,
                                            UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER), "Pump 1\nPump 2\nPump 3", LV_ROLLER_MODE_NORMAL);

    ui_RollerSmall__Communications__RollerSmall12 = ui_Container____RollerSmall_create(
                                                        ui_Container__Communications__Container92);
    lv_obj_set_height(ui_RollerSmall__Communications__RollerSmall12, lv_pct(100));
    lv_obj_set_width(ui_RollerSmall__Communications__RollerSmall12, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_RollerSmall__Communications__RollerSmall12, 0);
    lv_obj_set_y(ui_RollerSmall__Communications__RollerSmall12, 0);

    lv_obj_add_flag(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall12,
                                      UI_COMP_CONTAINER____ROLLERSMALL_LABEL____TITLE), LV_OBJ_FLAG_HIDDEN);    /// Flags

    lv_roller_set_options(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall12,
                                            UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER), "0-5V Out 1\nNone\n4-20 mA Out 1", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall12,
                                       UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER), LV_SIZE_CONTENT);  /// 140
    lv_obj_set_flex_grow(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall12,
                                           UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER), 1);
    lv_obj_set_style_pad_left(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall12,
                                                UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER), 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall12,
                                                 UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER), 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall12,
                                               UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER), 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall12,
                                                  UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER), 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Communications__Container93 = lv_obj_create(ui_Container__Communications__Container88);
    lv_obj_remove_style_all(ui_Container__Communications__Container93);
    lv_obj_set_height(ui_Container__Communications__Container93, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Communications__Container93, 1);
    lv_obj_set_align(ui_Container__Communications__Container93, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Communications__Container93, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Communications__Container93, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Communications__Container93,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container__Communications__Container94 = lv_obj_create(ui_Container__Communications__Container93);
    lv_obj_remove_style_all(ui_Container__Communications__Container94);
    lv_obj_set_height(ui_Container__Communications__Container94, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Communications__Container94, 1);
    lv_obj_set_align(ui_Container__Communications__Container94, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Communications__Container94,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RollerSmall__Communications__RollerSmall13 = ui_Container____RollerSmall_create(
                                                        ui_Container__Communications__Container94);
    lv_obj_set_x(ui_RollerSmall__Communications__RollerSmall13, 0);
    lv_obj_set_y(ui_RollerSmall__Communications__RollerSmall13, 0);

    lv_label_set_text(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall13,
                                        UI_COMP_CONTAINER____ROLLERSMALL_LABEL____TITLE), "Serial Type");

    lv_roller_set_options(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall13,
                                            UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER), "RS485\nRS232", LV_ROLLER_MODE_NORMAL);

    ui_Container__Communications__Container95 = lv_obj_create(ui_Container__Communications__Container93);
    lv_obj_remove_style_all(ui_Container__Communications__Container95);
    lv_obj_set_height(ui_Container__Communications__Container95, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Communications__Container95, 1);
    lv_obj_set_align(ui_Container__Communications__Container95, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Communications__Container95,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch__Communications__Switch5 = ui_Container____Switch_create(ui_Container__Communications__Container95);
    lv_obj_set_x(ui_Switch__Communications__Switch5, 0);
    lv_obj_set_y(ui_Switch__Communications__Switch5, 0);

    lv_label_set_text(ui_comp_get_child(ui_Switch__Communications__Switch5, UI_COMP_CONTAINER____SWITCH_LABEL____LABEL23),
                      "Remote");



    ui_Container__Communications__Container90 = lv_obj_create(ui_Container__Communications__Serial_Content);
    lv_obj_remove_style_all(ui_Container__Communications__Container90);
    lv_obj_set_width(ui_Container__Communications__Container90, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Communications__Container90, 1);
    lv_obj_set_align(ui_Container__Communications__Container90, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Communications__Container90, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Communications__Container90, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Communications__Container90,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RollerSmall__Communications__RollerSmall6 = ui_Container____RollerSmall_create(
                                                       ui_Container__Communications__Container90);
    lv_obj_set_x(ui_RollerSmall__Communications__RollerSmall6, 0);
    lv_obj_set_y(ui_RollerSmall__Communications__RollerSmall6, 0);

    lv_label_set_text(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall6,
                                        UI_COMP_CONTAINER____ROLLERSMALL_LABEL____TITLE), "Device ID");

    lv_roller_set_options(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall6,
                                            UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER), "17\n18\n19", LV_ROLLER_MODE_NORMAL);

    ui_RollerSmall__Communications__RollerSmall7 = ui_Container____RollerSmall_create(
                                                       ui_Container__Communications__Container90);
    lv_obj_set_x(ui_RollerSmall__Communications__RollerSmall7, 0);
    lv_obj_set_y(ui_RollerSmall__Communications__RollerSmall7, 0);

    lv_label_set_text(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall7,
                                        UI_COMP_CONTAINER____ROLLERSMALL_LABEL____TITLE), "Baud Rate");

    lv_roller_set_options(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall7,
                                            UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER), "4800\n9600\n19200\n38400\n57600\n115200\n230400\n460800\n921600",
                          LV_ROLLER_MODE_NORMAL);

    ui_RollerSmall__Communications__RollerSmall8 = ui_Container____RollerSmall_create(
                                                       ui_Container__Communications__Container90);
    lv_obj_set_x(ui_RollerSmall__Communications__RollerSmall8, 0);
    lv_obj_set_y(ui_RollerSmall__Communications__RollerSmall8, 0);

    lv_label_set_text(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall8,
                                        UI_COMP_CONTAINER____ROLLERSMALL_LABEL____TITLE), "Data Bits");

    lv_roller_set_options(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall8,
                                            UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER), "5\n7\n8\n9", LV_ROLLER_MODE_NORMAL);

    ui_RollerSmall__Communications__RollerSmall9 = ui_Container____RollerSmall_create(
                                                       ui_Container__Communications__Container90);
    lv_obj_set_x(ui_RollerSmall__Communications__RollerSmall9, 0);
    lv_obj_set_y(ui_RollerSmall__Communications__RollerSmall9, 0);

    lv_label_set_text(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall9,
                                        UI_COMP_CONTAINER____ROLLERSMALL_LABEL____TITLE), "Stop Bits");

    lv_roller_set_options(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall9,
                                            UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER), "1\n1.5\n2", LV_ROLLER_MODE_NORMAL);

    ui_RollerSmall__Communications__RollerSmall10 = ui_Container____RollerSmall_create(
                                                        ui_Container__Communications__Container90);
    lv_obj_set_x(ui_RollerSmall__Communications__RollerSmall10, 0);
    lv_obj_set_y(ui_RollerSmall__Communications__RollerSmall10, 0);

    lv_label_set_text(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall10,
                                        UI_COMP_CONTAINER____ROLLERSMALL_LABEL____TITLE), "Parity Bit");

    lv_roller_set_options(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall10,
                                            UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER), "Odd\nEven\nMark\nSpace", LV_ROLLER_MODE_NORMAL);

    ui_Container__Communications__Ethernet_Content = lv_obj_create(ui_Container__Communications__group);
    lv_obj_remove_style_all(ui_Container__Communications__Ethernet_Content);
    lv_obj_set_width(ui_Container__Communications__Ethernet_Content, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Communications__Ethernet_Content, 1);
    lv_obj_set_align(ui_Container__Communications__Ethernet_Content, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Communications__Ethernet_Content, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Communications__Ethernet_Content, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Container__Communications__Ethernet_Content, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Container__Communications__Ethernet_Content,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container__Communications__Ethernet_Content, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Container__Communications__Ethernet_Content, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_White);
    ui_object_set_themeable_style_property(ui_Container__Communications__Ethernet_Content, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_White);
    lv_obj_set_style_pad_left(ui_Container__Communications__Ethernet_Content, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Communications__Ethernet_Content, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Communications__Ethernet_Content, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Communications__Ethernet_Content, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Communications__Ethernet_Content, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Communications__Ethernet_Content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Communications__Container86 = lv_obj_create(ui_Container__Communications__Ethernet_Content);
    lv_obj_remove_style_all(ui_Container__Communications__Container86);
    lv_obj_set_width(ui_Container__Communications__Container86, 181);
    lv_obj_set_height(ui_Container__Communications__Container86, lv_pct(100));
    lv_obj_set_align(ui_Container__Communications__Container86, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Communications__Container86, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Communications__Container86, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Communications__Container86,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container__Communications__Container86, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Communications__Container86, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Input__Communications__Input14 = ui_Container____Input_create(ui_Container__Communications__Container86);
    lv_obj_set_height(ui_Input__Communications__Input14, 64);
    lv_obj_set_width(ui_Input__Communications__Input14, lv_pct(100));
    lv_obj_set_x(ui_Input__Communications__Input14, 0);
    lv_obj_set_y(ui_Input__Communications__Input14, 0);



    lv_label_set_text(ui_comp_get_child(ui_Input__Communications__Input14,
                                        UI_COMP_CONTAINER____INPUT_CONTAINER____LABEL_PADDING_LABEL____LABEL), "IP Address");

    lv_obj_set_width(ui_comp_get_child(ui_Input__Communications__Input14, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                     lv_pct(100));
    lv_obj_set_flex_grow(ui_comp_get_child(ui_Input__Communications__Input14,
                                           UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 1);
    lv_textarea_set_placeholder_text(ui_comp_get_child(ui_Input__Communications__Input14,
                                                       UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), "192.168.1.101");
    lv_obj_set_style_pad_left(ui_comp_get_child(ui_Input__Communications__Input14,
                                                UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_comp_get_child(ui_Input__Communications__Input14,
                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_comp_get_child(ui_Input__Communications__Input14,
                                               UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_comp_get_child(ui_Input__Communications__Input14,
                                                  UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_comp_get_child(ui_Input__Communications__Input14,
                                                UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 14, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_right(ui_comp_get_child(ui_Input__Communications__Input14,
                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_top(ui_comp_get_child(ui_Input__Communications__Input14,
                                               UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 6, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_bottom(ui_comp_get_child(ui_Input__Communications__Input14,
                                                  UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_FOCUSED);



    ui_Input__Communications__Input15 = ui_Container____Input_create(ui_Container__Communications__Container86);
    lv_obj_set_height(ui_Input__Communications__Input15, 64);
    lv_obj_set_width(ui_Input__Communications__Input15, lv_pct(100));
    lv_obj_set_x(ui_Input__Communications__Input15, 0);
    lv_obj_set_y(ui_Input__Communications__Input15, 0);



    lv_label_set_text(ui_comp_get_child(ui_Input__Communications__Input15,
                                        UI_COMP_CONTAINER____INPUT_CONTAINER____LABEL_PADDING_LABEL____LABEL), "Subnet Mask");

    lv_obj_set_width(ui_comp_get_child(ui_Input__Communications__Input15, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                     lv_pct(100));
    lv_obj_set_flex_grow(ui_comp_get_child(ui_Input__Communications__Input15,
                                           UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 1);
    lv_textarea_set_placeholder_text(ui_comp_get_child(ui_Input__Communications__Input15,
                                                       UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), "192.168.1.101");
    lv_obj_set_style_pad_left(ui_comp_get_child(ui_Input__Communications__Input15,
                                                UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_comp_get_child(ui_Input__Communications__Input15,
                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_comp_get_child(ui_Input__Communications__Input15,
                                               UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_comp_get_child(ui_Input__Communications__Input15,
                                                  UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_comp_get_child(ui_Input__Communications__Input15,
                                                UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 14, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_right(ui_comp_get_child(ui_Input__Communications__Input15,
                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_top(ui_comp_get_child(ui_Input__Communications__Input15,
                                               UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 6, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_bottom(ui_comp_get_child(ui_Input__Communications__Input15,
                                                  UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_FOCUSED);



    ui_Input__Communications__Input16 = ui_Container____Input_create(ui_Container__Communications__Container86);
    lv_obj_set_height(ui_Input__Communications__Input16, 64);
    lv_obj_set_width(ui_Input__Communications__Input16, lv_pct(100));
    lv_obj_set_x(ui_Input__Communications__Input16, 0);
    lv_obj_set_y(ui_Input__Communications__Input16, 0);



    lv_label_set_text(ui_comp_get_child(ui_Input__Communications__Input16,
                                        UI_COMP_CONTAINER____INPUT_CONTAINER____LABEL_PADDING_LABEL____LABEL), "Gateway");

    lv_obj_set_width(ui_comp_get_child(ui_Input__Communications__Input16, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                     lv_pct(100));
    lv_obj_set_flex_grow(ui_comp_get_child(ui_Input__Communications__Input16,
                                           UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 1);
    lv_textarea_set_placeholder_text(ui_comp_get_child(ui_Input__Communications__Input16,
                                                       UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), "192.168.1.101");
    lv_obj_set_style_pad_left(ui_comp_get_child(ui_Input__Communications__Input16,
                                                UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_comp_get_child(ui_Input__Communications__Input16,
                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_comp_get_child(ui_Input__Communications__Input16,
                                               UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_comp_get_child(ui_Input__Communications__Input16,
                                                  UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_comp_get_child(ui_Input__Communications__Input16,
                                                UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 14, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_right(ui_comp_get_child(ui_Input__Communications__Input16,
                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_top(ui_comp_get_child(ui_Input__Communications__Input16,
                                               UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 6, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_bottom(ui_comp_get_child(ui_Input__Communications__Input16,
                                                  UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_FOCUSED);



    ui_Input__Communications__Input17 = ui_Container____Input_create(ui_Container__Communications__Container86);
    lv_obj_set_height(ui_Input__Communications__Input17, 64);
    lv_obj_set_width(ui_Input__Communications__Input17, lv_pct(100));
    lv_obj_set_x(ui_Input__Communications__Input17, 0);
    lv_obj_set_y(ui_Input__Communications__Input17, 0);



    lv_label_set_text(ui_comp_get_child(ui_Input__Communications__Input17,
                                        UI_COMP_CONTAINER____INPUT_CONTAINER____LABEL_PADDING_LABEL____LABEL), "DNS");

    lv_obj_set_width(ui_comp_get_child(ui_Input__Communications__Input17, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                     lv_pct(100));
    lv_obj_set_flex_grow(ui_comp_get_child(ui_Input__Communications__Input17,
                                           UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 1);
    lv_textarea_set_placeholder_text(ui_comp_get_child(ui_Input__Communications__Input17,
                                                       UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), "192.168.1.101");
    lv_obj_set_style_pad_left(ui_comp_get_child(ui_Input__Communications__Input17,
                                                UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_comp_get_child(ui_Input__Communications__Input17,
                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_comp_get_child(ui_Input__Communications__Input17,
                                               UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_comp_get_child(ui_Input__Communications__Input17,
                                                  UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_comp_get_child(ui_Input__Communications__Input17,
                                                UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 14, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_right(ui_comp_get_child(ui_Input__Communications__Input17,
                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_top(ui_comp_get_child(ui_Input__Communications__Input17,
                                               UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 6, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_bottom(ui_comp_get_child(ui_Input__Communications__Input17,
                                                  UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_FOCUSED);



    ui_Container__Communications__Container101 = lv_obj_create(ui_Container__Communications__Ethernet_Content);
    lv_obj_remove_style_all(ui_Container__Communications__Container101);
    lv_obj_set_height(ui_Container__Communications__Container101, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Communications__Container101, 1);
    lv_obj_set_align(ui_Container__Communications__Container101, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Communications__Container101, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Communications__Container101, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container__Communications__Container101,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container__Communications__Container96 = lv_obj_create(ui_Container__Communications__Container101);
    lv_obj_remove_style_all(ui_Container__Communications__Container96);
    lv_obj_set_width(ui_Container__Communications__Container96, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Communications__Container96, 1);
    lv_obj_set_align(ui_Container__Communications__Container96, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Communications__Container96, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Communications__Container96, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Communications__Container96,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container__Communications__Container96, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Communications__Container96, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Communications__Container96, -8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Communications__Container96, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Checkbox__Communications__Checkbox2 = lv_checkbox_create(ui_Container__Communications__Container96);
    lv_checkbox_set_text(ui_Checkbox__Communications__Checkbox2, "  DHCP");
    lv_obj_set_width(ui_Checkbox__Communications__Checkbox2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox__Communications__Checkbox2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Checkbox__Communications__Checkbox2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox__Communications__Checkbox2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    ui_object_set_themeable_style_property(ui_Checkbox__Communications__Checkbox2, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Checkbox__Communications__Checkbox2, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(ui_Checkbox__Communications__Checkbox2, &ui_font_P2_SBold, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Checkbox__Communications__Checkbox2, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Checkbox__Communications__Checkbox2, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_White);
    ui_object_set_themeable_style_property(ui_Checkbox__Communications__Checkbox2, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_White);
    ui_object_set_themeable_style_property(ui_Checkbox__Communications__Checkbox2, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_Checkbox__Communications__Checkbox2, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Blue);
    lv_obj_set_style_border_width(ui_Checkbox__Communications__Checkbox2, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Checkbox__Communications__Checkbox2, 6, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Checkbox__Communications__Checkbox2, 6, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Checkbox__Communications__Checkbox2, 6, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Checkbox__Communications__Checkbox2, 6, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Checkbox__Communications__Checkbox2, LV_PART_INDICATOR | LV_STATE_CHECKED,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_Checkbox__Communications__Checkbox2, LV_PART_INDICATOR | LV_STATE_CHECKED,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Blue);
    lv_obj_set_style_bg_image_src(ui_Checkbox__Communications__Checkbox2, ui_img_chack_png,
                                  LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_Switch__Communications__Switch6 = ui_Container____Switch_create(ui_Container__Communications__Container96);
    lv_obj_set_x(ui_Switch__Communications__Switch6, 0);
    lv_obj_set_y(ui_Switch__Communications__Switch6, 0);

    lv_label_set_text(ui_comp_get_child(ui_Switch__Communications__Switch6, UI_COMP_CONTAINER____SWITCH_LABEL____LABEL23),
                      "Remote");



    ui_Container__Communications__Container97 = lv_obj_create(ui_Container__Communications__Container101);
    lv_obj_remove_style_all(ui_Container__Communications__Container97);
    lv_obj_set_height(ui_Container__Communications__Container97, 201);
    lv_obj_set_width(ui_Container__Communications__Container97, lv_pct(100));
    lv_obj_set_align(ui_Container__Communications__Container97, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Communications__Container97,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Numpad_M__Communications__Numpad_M1 = ui_Keyboard____Numpad_M_create(ui_Container__Communications__Ethernet_Content);
    lv_obj_set_width(ui_Numpad_M__Communications__Numpad_M1, 527);
    lv_obj_set_height(ui_Numpad_M__Communications__Numpad_M1, 209);
    lv_obj_set_x(ui_Numpad_M__Communications__Numpad_M1, 12);
    lv_obj_set_y(ui_Numpad_M__Communications__Numpad_M1, 7);
    lv_obj_set_align(ui_Numpad_M__Communications__Numpad_M1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Numpad_M__Communications__Numpad_M1, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_remove_flag(ui_Numpad_M__Communications__Numpad_M1, LV_OBJ_FLAG_HIDDEN);      /// Flags
    lv_obj_set_style_pad_left(ui_Numpad_M__Communications__Numpad_M1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Numpad_M__Communications__Numpad_M1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Numpad_M__Communications__Numpad_M1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Numpad_M__Communications__Numpad_M1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Communications__WiFi_Content = lv_obj_create(ui_Container__Communications__group);
    lv_obj_remove_style_all(ui_Container__Communications__WiFi_Content);
    lv_obj_set_width(ui_Container__Communications__WiFi_Content, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Communications__WiFi_Content, 1);
    lv_obj_set_x(ui_Container__Communications__WiFi_Content, 2);
    lv_obj_set_y(ui_Container__Communications__WiFi_Content, 0);
    lv_obj_set_align(ui_Container__Communications__WiFi_Content, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Communications__WiFi_Content, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Communications__WiFi_Content, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Communications__WiFi_Content,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container__Communications__WiFi_Content, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Container__Communications__WiFi_Content, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_White);
    ui_object_set_themeable_style_property(ui_Container__Communications__WiFi_Content, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_White);
    lv_obj_set_style_pad_left(ui_Container__Communications__WiFi_Content, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Communications__WiFi_Content, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Communications__WiFi_Content, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Communications__WiFi_Content, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Communications__WiFi_Content, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Communications__WiFi_Content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Communications__Container99 = lv_obj_create(ui_Container__Communications__WiFi_Content);
    lv_obj_remove_style_all(ui_Container__Communications__Container99);
    lv_obj_set_width(ui_Container__Communications__Container99, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Communications__Container99, 1);
    lv_obj_set_align(ui_Container__Communications__Container99, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Communications__Container99, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Communications__Container99, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Communications__Container99,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container__Communications__Container99, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Communications__Container99, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Communications__Container99, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Communications__Container99, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Communications__Container100 = lv_obj_create(ui_Container__Communications__Container99);
    lv_obj_remove_style_all(ui_Container__Communications__Container100);
    lv_obj_set_height(ui_Container__Communications__Container100, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Communications__Container100, 1);
    lv_obj_set_align(ui_Container__Communications__Container100, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Communications__Container100, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Communications__Container100, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Communications__Container100,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Container__Communications__Container100, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_Container__Communications__Container100, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_Container__Communications__Container100, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container__Communications__Container100, LV_BORDER_SIDE_RIGHT,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Container__Communications__Container100, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Communications__Container100, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Communications__Container100, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Communications__Container100, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Communications__Container100, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Communications__Container100, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Input__Communications__Input19 = ui_Container____Input_create(ui_Container__Communications__Container100);
    lv_obj_set_height(ui_Input__Communications__Input19, 64);
    lv_obj_set_width(ui_Input__Communications__Input19, lv_pct(100));
    lv_obj_set_x(ui_Input__Communications__Input19, 0);
    lv_obj_set_y(ui_Input__Communications__Input19, 0);



    lv_label_set_text(ui_comp_get_child(ui_Input__Communications__Input19,
                                        UI_COMP_CONTAINER____INPUT_CONTAINER____LABEL_PADDING_LABEL____LABEL), "SSID");

    lv_obj_set_width(ui_comp_get_child(ui_Input__Communications__Input19, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                     lv_pct(100));
    lv_obj_set_height(ui_comp_get_child(ui_Input__Communications__Input19,
                                        UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), LV_SIZE_CONTENT);   /// 1
    lv_textarea_set_placeholder_text(ui_comp_get_child(ui_Input__Communications__Input19,
                                                       UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), "SSID");
    lv_obj_set_style_pad_left(ui_comp_get_child(ui_Input__Communications__Input19,
                                                UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_comp_get_child(ui_Input__Communications__Input19,
                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_comp_get_child(ui_Input__Communications__Input19,
                                               UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_comp_get_child(ui_Input__Communications__Input19,
                                                  UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_comp_get_child(ui_Input__Communications__Input19,
                                                UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 14, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_right(ui_comp_get_child(ui_Input__Communications__Input19,
                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_top(ui_comp_get_child(ui_Input__Communications__Input19,
                                               UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 6, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_bottom(ui_comp_get_child(ui_Input__Communications__Input19,
                                                  UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_FOCUSED);



    ui_RollerSmall__Communications__RollerSmall14 = ui_Container____RollerSmall_create(
                                                        ui_Container__Communications__Container100);
    lv_obj_set_width(ui_RollerSmall__Communications__RollerSmall14, lv_pct(100));
    lv_obj_set_flex_grow(ui_RollerSmall__Communications__RollerSmall14, 1);
    lv_obj_set_x(ui_RollerSmall__Communications__RollerSmall14, 0);
    lv_obj_set_y(ui_RollerSmall__Communications__RollerSmall14, 0);
    lv_obj_set_style_pad_row(ui_RollerSmall__Communications__RollerSmall14, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_RollerSmall__Communications__RollerSmall14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_label_set_text(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall14,
                                        UI_COMP_CONTAINER____ROLLERSMALL_LABEL____TITLE), "Security Type");

    lv_roller_set_options(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall14,
                                            UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER), "WEP\nWPA\nWPA2\nWPA3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall14,
                                       UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER), lv_pct(100));
    lv_obj_set_flex_grow(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall14,
                                           UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER), 1);

    ui_Container__Communications__Container103 = lv_obj_create(ui_Container__Communications__Container99);
    lv_obj_remove_style_all(ui_Container__Communications__Container103);
    lv_obj_set_height(ui_Container__Communications__Container103, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Communications__Container103, 1);
    lv_obj_set_align(ui_Container__Communications__Container103, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Communications__Container103, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Communications__Container103, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Communications__Container103,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Container__Communications__Container103, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_Container__Communications__Container103, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_Container__Communications__Container103, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container__Communications__Container103, LV_BORDER_SIDE_RIGHT,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Container__Communications__Container103, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Communications__Container103, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Communications__Container103, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Communications__Container103, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Communications__Container103, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Communications__Container103, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Input__Communications__Input18 = ui_Container____Input_create(ui_Container__Communications__Container103);
    lv_obj_set_height(ui_Input__Communications__Input18, 64);
    lv_obj_set_width(ui_Input__Communications__Input18, lv_pct(100));
    lv_obj_set_x(ui_Input__Communications__Input18, 0);
    lv_obj_set_y(ui_Input__Communications__Input18, 0);



    lv_label_set_text(ui_comp_get_child(ui_Input__Communications__Input18,
                                        UI_COMP_CONTAINER____INPUT_CONTAINER____LABEL_PADDING_LABEL____LABEL), "Password");

    lv_obj_set_width(ui_comp_get_child(ui_Input__Communications__Input18, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                     lv_pct(100));
    lv_obj_set_flex_grow(ui_comp_get_child(ui_Input__Communications__Input18,
                                           UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 1);
    lv_textarea_set_placeholder_text(ui_comp_get_child(ui_Input__Communications__Input18,
                                                       UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), "Password");
    lv_textarea_set_password_mode(ui_comp_get_child(ui_Input__Communications__Input18,
                                                    UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), true);
    lv_obj_set_style_pad_left(ui_comp_get_child(ui_Input__Communications__Input18,
                                                UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_comp_get_child(ui_Input__Communications__Input18,
                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_comp_get_child(ui_Input__Communications__Input18,
                                               UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_comp_get_child(ui_Input__Communications__Input18,
                                                  UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_comp_get_child(ui_Input__Communications__Input18,
                                                UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 14, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_right(ui_comp_get_child(ui_Input__Communications__Input18,
                                                 UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_top(ui_comp_get_child(ui_Input__Communications__Input18,
                                               UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 6, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_bottom(ui_comp_get_child(ui_Input__Communications__Input18,
                                                  UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1), 3, LV_PART_MAIN | LV_STATE_FOCUSED);



    ui_RollerSmall__Communications__RollerSmall15 = ui_Container____RollerSmall_create(
                                                        ui_Container__Communications__Container103);
    lv_obj_set_width(ui_RollerSmall__Communications__RollerSmall15, lv_pct(100));
    lv_obj_set_flex_grow(ui_RollerSmall__Communications__RollerSmall15, 1);
    lv_obj_set_x(ui_RollerSmall__Communications__RollerSmall15, 0);
    lv_obj_set_y(ui_RollerSmall__Communications__RollerSmall15, 0);
    lv_obj_set_style_pad_row(ui_RollerSmall__Communications__RollerSmall15, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_RollerSmall__Communications__RollerSmall15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_label_set_text(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall15,
                                        UI_COMP_CONTAINER____ROLLERSMALL_LABEL____TITLE), "Networks");

    lv_roller_set_options(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall15,
                                            UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER), "One Tech Wifi\nZero Tech Wifi\nTwo Tech Wifi",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall15,
                                       UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER), lv_pct(100));
    lv_obj_set_flex_grow(ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall15,
                                           UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER), 1);

    ui_Container__Communications__Container104 = lv_obj_create(ui_Container__Communications__Container99);
    lv_obj_remove_style_all(ui_Container__Communications__Container104);
    lv_obj_set_height(ui_Container__Communications__Container104, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container__Communications__Container104, 1);
    lv_obj_set_align(ui_Container__Communications__Container104, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Communications__Container104, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container__Communications__Container104, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Communications__Container104,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container__Communications__Container104, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Communications__Container104, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch__Communications__Switch8 = ui_Container____Switch_create(ui_Container__Communications__Container104);
    lv_obj_set_x(ui_Switch__Communications__Switch8, 0);
    lv_obj_set_y(ui_Switch__Communications__Switch8, 0);

    lv_label_set_text(ui_comp_get_child(ui_Switch__Communications__Switch8, UI_COMP_CONTAINER____SWITCH_LABEL____LABEL23),
                      "Remote");



    ui_Secondarybtn__Communications__Select_Options12 = ui_Button____Secondarybtn_create(
                                                            ui_Container__Communications__Container104);
    lv_obj_set_width(ui_Secondarybtn__Communications__Select_Options12, 180);
    lv_obj_set_height(ui_Secondarybtn__Communications__Select_Options12, 64);
    lv_obj_set_x(ui_Secondarybtn__Communications__Select_Options12, 0);
    lv_obj_set_y(ui_Secondarybtn__Communications__Select_Options12, 0);
    lv_obj_set_align(ui_Secondarybtn__Communications__Select_Options12, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_Secondarybtn__Communications__Select_Options12, LV_OBJ_FLAG_HIDDEN);      /// Flags
    lv_obj_set_style_pad_left(ui_Secondarybtn__Communications__Select_Options12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Secondarybtn__Communications__Select_Options12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Secondarybtn__Communications__Select_Options12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Secondarybtn__Communications__Select_Options12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_height(ui_Secondarybtn__Communications__Select_Options12, 64, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_height(ui_Secondarybtn__Communications__Select_Options12, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_width(ui_comp_get_child(ui_Secondarybtn__Communications__Select_Options12,
                                       UI_COMP_BUTTON____SECONDARYBTN_LABEL____LABEL), LV_SIZE_CONTENT);  /// 100
    lv_obj_set_height(ui_comp_get_child(ui_Secondarybtn__Communications__Select_Options12,
                                        UI_COMP_BUTTON____SECONDARYBTN_LABEL____LABEL), LV_SIZE_CONTENT);   /// 100
    lv_label_set_text(ui_comp_get_child(ui_Secondarybtn__Communications__Select_Options12,
                                        UI_COMP_BUTTON____SECONDARYBTN_LABEL____LABEL), "Forget");

    ui_Primarybtn__Communications__Next10 = ui_Button____Primarybtn_create(ui_Container__Communications__Container104);
    lv_obj_set_width(ui_Primarybtn__Communications__Next10, 180);
    lv_obj_set_height(ui_Primarybtn__Communications__Next10, 64);
    lv_obj_set_x(ui_Primarybtn__Communications__Next10, 0);
    lv_obj_set_y(ui_Primarybtn__Communications__Next10, 0);
    lv_obj_set_align(ui_Primarybtn__Communications__Next10, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_pad_left(ui_Primarybtn__Communications__Next10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Primarybtn__Communications__Next10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Primarybtn__Communications__Next10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Primarybtn__Communications__Next10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_label_set_text(ui_comp_get_child(ui_Primarybtn__Communications__Next10, UI_COMP_BUTTON____PRIMARYBTN_LABEL____LABEL),
                      "Connect");
    lv_obj_set_style_text_align(ui_comp_get_child(ui_Primarybtn__Communications__Next10,
                                                  UI_COMP_BUTTON____PRIMARYBTN_LABEL____LABEL), LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container__Communications__Container102 = lv_obj_create(ui_Container__Communications__WiFi_Content);
    lv_obj_remove_style_all(ui_Container__Communications__Container102);
    lv_obj_set_height(ui_Container__Communications__Container102, 44);
    lv_obj_set_width(ui_Container__Communications__Container102, lv_pct(100));
    lv_obj_set_align(ui_Container__Communications__Container102, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container__Communications__Container102, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container__Communications__Container102, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container__Communications__Container102,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container__Communications__Container102, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container__Communications__Container102, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container__Communications__Container102, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container__Communications__Container102, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container__Communications__Container102, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container__Communications__Container102, 28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch__Communications__Switch7 = ui_Container____Switch_create(ui_Container__Communications__Container102);
    lv_obj_set_x(ui_Switch__Communications__Switch7, 0);
    lv_obj_set_y(ui_Switch__Communications__Switch7, 0);
    lv_obj_set_flex_flow(ui_Switch__Communications__Switch7, LV_FLEX_FLOW_ROW_REVERSE);
    lv_obj_set_flex_align(ui_Switch__Communications__Switch7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_row(ui_Switch__Communications__Switch7, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Switch__Communications__Switch7, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_label_set_text(ui_comp_get_child(ui_Switch__Communications__Switch7, UI_COMP_CONTAINER____SWITCH_LABEL____LABEL23),
                      "Hidden\nNetworks");
    lv_obj_set_style_text_align(ui_comp_get_child(ui_Switch__Communications__Switch7,
                                                  UI_COMP_CONTAINER____SWITCH_LABEL____LABEL23), LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Checkbox__Communications__Checkbox3 = lv_checkbox_create(ui_Container__Communications__Container102);
    lv_checkbox_set_text(ui_Checkbox__Communications__Checkbox3, "  Automatic Connection");
    lv_obj_set_width(ui_Checkbox__Communications__Checkbox3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox__Communications__Checkbox3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Checkbox__Communications__Checkbox3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox__Communications__Checkbox3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    ui_object_set_themeable_style_property(ui_Checkbox__Communications__Checkbox3, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Checkbox__Communications__Checkbox3, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Dark_blue);
    lv_obj_set_style_text_font(ui_Checkbox__Communications__Checkbox3, &ui_font_P2_SBold, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Checkbox__Communications__Checkbox3, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Checkbox__Communications__Checkbox3, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_White);
    ui_object_set_themeable_style_property(ui_Checkbox__Communications__Checkbox3, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_White);
    ui_object_set_themeable_style_property(ui_Checkbox__Communications__Checkbox3, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_Checkbox__Communications__Checkbox3, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Blue);
    lv_obj_set_style_border_width(ui_Checkbox__Communications__Checkbox3, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Checkbox__Communications__Checkbox3, 6, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Checkbox__Communications__Checkbox3, 6, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Checkbox__Communications__Checkbox3, 6, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Checkbox__Communications__Checkbox3, 6, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Checkbox__Communications__Checkbox3, LV_PART_INDICATOR | LV_STATE_CHECKED,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_Checkbox__Communications__Checkbox3, LV_PART_INDICATOR | LV_STATE_CHECKED,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Blue);
    lv_obj_set_style_bg_image_src(ui_Checkbox__Communications__Checkbox3, ui_img_chack_png,
                                  LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_Container__Communications__Footer8 = lv_obj_create(ui_Container__Communications__Content);
    lv_obj_remove_style_all(ui_Container__Communications__Footer8);
    lv_obj_set_width(ui_Container__Communications__Footer8, 800);
    lv_obj_set_height(ui_Container__Communications__Footer8, 34);
    lv_obj_set_align(ui_Container__Communications__Footer8, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Container__Communications__Footer8, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_remove_flag(ui_Container__Communications__Footer8,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Container__Communications__Footer8, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Dark_blue);
    ui_object_set_themeable_style_property(ui_Container__Communications__Footer8, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Dark_blue);

    ui_Label__Communications__Label42 = lv_label_create(ui_Container__Communications__Footer8);
    lv_obj_set_width(ui_Label__Communications__Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Communications__Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label__Communications__Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label__Communications__Label42, "Visit eldex.com/support for manuals and help");
    ui_object_set_themeable_style_property(ui_Label__Communications__Label42, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Interface);
    ui_object_set_themeable_style_property(ui_Label__Communications__Label42, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Interface);
    lv_obj_set_style_text_font(ui_Label__Communications__Label42, &ui_font_P3_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardL__Communications__KeyboardWifi = ui_Keyboard____KeyboardL_create(ui_Screen__Communications);
    lv_obj_set_height(ui_KeyboardL__Communications__KeyboardWifi, 255);
    lv_obj_set_width(ui_KeyboardL__Communications__KeyboardWifi, lv_pct(100));
    lv_obj_set_x(ui_KeyboardL__Communications__KeyboardWifi, 0);
    lv_obj_set_y(ui_KeyboardL__Communications__KeyboardWifi, 0);
    lv_obj_add_flag(ui_KeyboardL__Communications__KeyboardWifi,
                    LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags

    lv_obj_add_event_cb(ui_comp_get_child(ui_Header__Communications__Header8,
                                          UI_COMP_CONTAINER____HEADER_BUTTON____BACK_BUTTON), ui_event_Header__Communications__Header8_Button____Back_Button,
                        LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input__Communications__Input14,
                                          UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                        ui_event_Input__Communications__Input14_Textarea__Communications__Input14_TextAreaIP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input__Communications__Input15,
                                          UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                        ui_event_Input__Communications__Input15_Textarea__Communications__Input15_TextAreaSUB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input__Communications__Input16,
                                          UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                        ui_event_Input__Communications__Input16_Textarea__Communications__Input16_TextAreaGate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input__Communications__Input17,
                                          UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                        ui_event_Input__Communications__Input17_Textarea__Communications__Input17_TextAreaDNS, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Numpad_M__Communications__Numpad_M1, ui_comp_get_child(ui_Input__Communications__Input14,
                                                                                       UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1));
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input__Communications__Input19,
                                          UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                        ui_event_Input__Communications__Input19_Textarea__Communications__Input19_TextAreaSSID, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Input__Communications__Input18,
                                          UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1),
                        ui_event_Input__Communications__Input18_Textarea__Communications__Input18_TextAreaPAss, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardL__Communications__KeyboardWifi,
                             ui_comp_get_child(ui_Input__Communications__Input19, UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1));
    lv_obj_add_event_cb(ui_KeyboardL__Communications__KeyboardWifi,
                        ui_event_KeyboardL__Communications__KeyboardWifi_Keyboard____KeyboardL, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen__Communications, ui_event_Screen__Communications, LV_EVENT_ALL, NULL);
    ui_Button__Communications__Back = ui_comp_get_child(ui_Header__Communications__Header8,
                                                        UI_COMP_CONTAINER____HEADER_BUTTON____BACK_BUTTON);
    ui_Image__Communications__USB_Status = ui_comp_get_child(ui_Header__Communications__Header8,
                                                             UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____USB);
    ui_Image__Communications__Ethernet_Status = ui_comp_get_child(ui_Header__Communications__Header8,
                                                                  UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____ETHERNET);
    ui_Image__Communications__WiFi_Status = ui_comp_get_child(ui_Header__Communications__Header8,
                                                              UI_COMP_CONTAINER____HEADER_CONTAINER____ICONS_IMAGE____WIFI);
    ui_Button__Communications__Serial = ui_TabButton__Communications__TabButton16;
    ui_Button__Communications__Ethernet = ui_TabButton__Communications__TabButton17;
    ui_Button__Communications__WiFi = ui_TabButton__Communications__TabButton18;
    ui_Label__Communications__Serial_PumpSelector_Title = ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall11,
                                                                            UI_COMP_CONTAINER____ROLLERSMALL_LABEL____TITLE);
    ui_Roller__Communications__Serial_SelectPump = ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall11,
                                                                     UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER);
    ui_Label__Communications__Serial_AnalogControlPortSelector_Title = ui_comp_get_child(
                                                                           ui_RollerSmall__Communications__RollerSmall12, UI_COMP_CONTAINER____ROLLERSMALL_LABEL____TITLE);
    ui_Roller__Communications__Serial_PumpAnalogControlPort = ui_comp_get_child(
                                                                  ui_RollerSmall__Communications__RollerSmall12, UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER);
    ui_Roller__Communications__Serial_ProtocolTypeStandard = ui_comp_get_child(
                                                                 ui_RollerSmall__Communications__RollerSmall13, UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER);
    ui_Switch__Communications__Serial_RemoteControl = ui_comp_get_child(ui_Switch__Communications__Switch5,
                                                                        UI_COMP_CONTAINER____SWITCH_SWITCH____SWITCH3);
    ui_Roller__Communications__Serial_DeviceID = ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall6,
                                                                   UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER);
    ui_Roller__Communications__Serial_BaudRate = ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall7,
                                                                   UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER);
    ui_Roller__Communications__Serial_DatabitsPerBaud = ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall8,
                                                                          UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER);
    ui_Roller__Communications__Serial_StopBitAmount = ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall9,
                                                                        UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER);
    ui_Roller__Communications__Serial_ParityBitType = ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall10,
                                                                        UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER);
    ui_Textarea__Communications__Ethernet_IPaddress = ui_comp_get_child(ui_Input__Communications__Input14,
                                                                        UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1);
    ui_Textarea__Communications__Ethernet_SubnetMask = ui_comp_get_child(ui_Input__Communications__Input15,
                                                                         UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1);
    ui_Textarea__Communications__Ethernet_GatewayIP = ui_comp_get_child(ui_Input__Communications__Input16,
                                                                        UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1);
    ui_Textarea__Communications__Ethernet_DNSaddress = ui_comp_get_child(ui_Input__Communications__Input17,
                                                                         UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1);
    ui_Checkbox__Communications__Ethernet_DHCP = ui_Checkbox__Communications__Checkbox2;
    ui_Switch__Communications__Ethernet_RemoteControl = ui_comp_get_child(ui_Switch__Communications__Switch6,
                                                                          UI_COMP_CONTAINER____SWITCH_SWITCH____SWITCH3);
    ui_Keyboard__Communications__Ethernet_IPAddressEntry = ui_Numpad_M__Communications__Numpad_M1;
    ui_Container__Communications__WiFi__LeftSide = ui_Container__Communications__Container100;
    ui_Container__Communications__WiFi__SSID = ui_Input__Communications__Input19;
    ui_Textarea__Communications__WiFi_SSID = ui_comp_get_child(ui_Input__Communications__Input19,
                                                               UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1);
    ui_Container__Communications__WiFi__SecurityType = ui_RollerSmall__Communications__RollerSmall14;
    ui_Roller__Communications__WiFi_SecurityType = ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall14,
                                                                     UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER);
    ui_Container__Communications__WiFi__RightSide = ui_Container__Communications__Container103;
    ui_Container__Communications__WiFi__Password = ui_Input__Communications__Input18;
    ui_Textarea__Communications__WiFi_Password = ui_comp_get_child(ui_Input__Communications__Input18,
                                                                   UI_COMP_CONTAINER____INPUT_TEXTAREA____TEXTAREA1);
    ui_Container__Communications__WiFi__SSIDlist = ui_RollerSmall__Communications__RollerSmall15;
    ui_Roller__Communications__WiFi_SSIDlist = ui_comp_get_child(ui_RollerSmall__Communications__RollerSmall15,
                                                                 UI_COMP_CONTAINER____ROLLERSMALL_ROLLER____ROLLER);
    ui_Switch__Communications__WiFi_RemoteControl = ui_comp_get_child(ui_Switch__Communications__Switch8,
                                                                      UI_COMP_CONTAINER____SWITCH_SWITCH____SWITCH3);
    ui_Button__Communications__WiFi_ForgetConnection = ui_Secondarybtn__Communications__Select_Options12;
    ui_Button__Communications__WiFi_Connect = ui_Primarybtn__Communications__Next10;
    ui_Switch__Communications__WiFi_ConnectToHiddenNetwork = ui_comp_get_child(ui_Switch__Communications__Switch7,
                                                                               UI_COMP_CONTAINER____SWITCH_SWITCH____SWITCH3);
    ui_Checkbox__Communications__WiFi_AutomaticConnection = ui_Checkbox__Communications__Checkbox3;
    ui_Label__Communications__StatusFooter = ui_Label__Communications__Label42;
    ui_Keyboard__Communications__WiFi_AuthenticationDataEntry = ui_KeyboardL__Communications__KeyboardWifi;

}
